### ISSUE TITLE
Generate new ZEN patch?

### ISSUE THREAD

**Issue by ghost** [zen-kernel/zen-kernel#106]
Can we generate a new zen-patch for the most stable vanilla kernel?

For example, get the 4.12.5 zen patch for the 4.12.5 kernel

**Comment by Techwolf** [comment]
See my comment for the "magic" command. :-)

https://github.com/zen-kernel/zen-kernel/issues/98#issuecomment-298108816

**Comment by damentz** [comment]
@Techwolf has the solution, closing.
