### ISSUE TITLE
Unable to set BFQ

### ISSUE THREAD

**Issue by guzzard** [zen-kernel/zen-kernel#107]
I'm unable to set IO scheduler BFQ. Bug or am I missing something?

Kernel: 4.12.5-1-zen #1 ZEN SMP PREEMPT Sun Aug 6 23:14:47 UTC 2017 x86_64 GNU/Linux

$ dmesg | grep -i bfq
[    1.079744] io scheduler bfq registered

\# echo bfq > /sys/block/sdc/queue/scheduler
bash: echo: write error: Invalid argument

$ cat /sys/block/sdc/queue/scheduler
noop deadline [cfq]

BFQ is not listed, and not possible to set it as scheduler?

**Comment by heftig** [comment]
In 4.12, the MQ version of BFQ was mainlined. Unfortunately, the BFQ developers have not released patches to add the non-MQ version to 4.12.

If you want to use BFQ MQ, add `scsi_mod.use_blk_mq=1` to your kernel command line. I consistently get hard lockups with MQ and heavy disk usage, though, no matter the scheduler, so I advise against this.

**Comment by guzzard** [comment]
@heftig understood! Many thanks for the quick reply!
