### ISSUE TITLE
Are include/linux/elevator.h or block/bfq-mq-iosched.c out of date?

### ISSUE THREAD

**Issue by spoonm** [zen-kernel/zen-kernel#108]
I get the following errors while compiling:

```
block/bfq-mq-iosched.c:5558:4: error: 'struct elevator_mq_ops' has no member named 'prepare_request'; did you mean 'requeue_request'?
block/bfq-mq-iosched.c:5559:4: error: 'struct elevator_mq_ops' has no member named 'finish_request'; did you mean 'former_request'?
```

The two members are present in torvalds/linux's `include/linux/elevator.h`, but not in this repo's, so I imagine either the header is out of date or changes weren't taken into account for `block/bfq-mq-iosched.c`.

I know next to nothing about the inner workings of the base or zen kernel, so please let me know if I'm talking out of my ass here and I screwed something up.

**Comment by heftig** [comment]
Yes, `MQ_IOSCHED_BFQ` is broken. `IOSCHED_BFQ_SQ` and `IOSCHED_BFQ` should build, though.

**Comment by heftig** [comment]
Fine since 4.14.
