### ISSUE TITLE
bfq-mq patches break compilation

### ISSUE THREAD

**Issue by aenertia** [zen-kernel/zen-kernel#110]
Fails to compile with latest merged patch

commit ffbef333e8073db7c4ad9d36a9ce95eadad3080f (HEAD -> 4.12/master, origin/HEAD, origin/4.12/master)
Merge: ccb1617eb318 467cb627e65a
Author: Steven Barrett <steven@liquorix.net>
Date:   Wed Sep 13 19:36:41 2017 -0500

    Merge branch '4.12/bfq' into 4.12/master

`
  CC      block/bfq-mq-iosched.o
block/bfq-mq-iosched.c:5570:4: error: ‘struct elevator_mq_ops’ has no member named ‘prepare_request’; did you mean ‘requeue_request’?
   .prepare_request        = bfq_prepare_request,
    ^~~~~~~~~~~~~~~
    requeue_request
block/bfq-mq-iosched.c:5570:29: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
   .prepare_request        = bfq_prepare_request,
                             ^~~~~~~~~~~~~~~~~~~
block/bfq-mq-iosched.c:5570:29: note: (near initialization for ‘iosched_bfq_mq.ops.mq.init_sched’)
block/bfq-mq-iosched.c:5571:4: error: ‘struct elevator_mq_ops’ has no member named ‘finish_request’; did you mean ‘former_request’?
   .finish_request         = bfq_finish_request,
    ^~~~~~~~~~~~~~
    former_request
block/bfq-mq-iosched.c:5571:29: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
   .finish_request         = bfq_finish_request,
                             ^~~~~~~~~~~~~~~~~~
block/bfq-mq-iosched.c:5571:29: note: (near initialization for ‘iosched_bfq_mq.ops.mq.exit_sched’)
cc1: some warnings being treated as errors
scripts/Makefile.build:302: recipe for target 'block/bfq-mq-iosched.o' failed
make[1]: *** [block/bfq-mq-iosched.o] Error 1
Makefile:1023: recipe for target 'block' failed
make: *** [block] Error 2
'

**Comment by damentz** [comment]
I would recommend not using bfq-mq from this patch series and stick with mainline if you really need to use the blk-mq bfq version.  This is just a workaround since blk-mq has problems with suspend on 4.12 and there's no proper port of bfq-sq to 4.12 since Paolo is focusing on 4.13+.

Unfortunately, there's no official port of MuQSS to 4.13 either, so this is what we're left with.  I'll accept patches removing bfq-mq out-of-tree from Kconfig or a patch to fix the build.

**Comment by heftig** [comment]
Just removing the Kconfig variables is probably effective enough.

**Comment by heftig** [comment]
Fine since 4.14.
