### ISSUE TITLE
A wiki page with a list of patches included / their original source.

### ISSUE THREAD

**Issue by kurumushi** [zen-kernel/zen-kernel#111]
Since zen-kernel.org apparently redirects here now, It would be nice to have at least some sort of list of what is actually included in the kernel, and preferably either a set of individual patches, or a link to their original source.

**Comment by Sudokamikaze** [comment]
@kurumushi https://liquorix.net/

**Comment by alvin998179** [comment]
suggestion:add new features:
1.zstd compression support for initramfs.
2.uksm
3.tcp bbr v2
4.PDS-MQ CPU Scheduler

**Comment by damentz** [comment]
@alvin998179 can you submit each of those as separate issues and include links to the best place to get patches/commits that enable those features?  Worst case if you can't find the true upstream, you can link to commits from other kernel sources (pf-kernel / xanmod), and we can do research from there.

One feature we won't add is UKSM, however.  Unless something has changed, it's never ran stable on any of my systems.
