### ISSUE TITLE
livepatch error on 4.14.5

### ISSUE THREAD

**Issue by loxdegio** [zen-kernel/zen-kernel#113]
`kernel/livepatch/transition.c: In function ‘klp_try_switch_task’:
kernel/livepatch/transition.c:294:2: error: unknown type name ‘rq_flags_t’
  rq_flags_t flags;
  ^
kernel/livepatch/transition.c:317:26: error: passing argument 2 of ‘task_rq_lock’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  rq = task_rq_lock(task, &flags);
                          ^
In file included from kernel/livepatch/transition.c:27:0:
kernel/livepatch/../sched/sched.h:1703:12: note: expected ‘struct rq_flags *’ but argument is of type ‘int *’
 struct rq *task_rq_lock(struct task_struct *p, struct rq_flags *rf)
            ^
kernel/livepatch/transition.c:336:27: error: passing argument 3 of ‘task_rq_unlock’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  task_rq_unlock(rq, task, &flags);
                           ^
In file included from kernel/livepatch/transition.c:27:0:
kernel/livepatch/../sched/sched.h:1715:1: note: expected ‘struct rq_flags *’ but argument is of type ‘int *’
 task_rq_unlock(struct rq *rq, struct task_struct *p, struct rq_flags *rf)
 ^
cc1: some warnings being treated as errors`

This is the error I got today compiling from sources.

Can you please check?

**Comment by heftig** [comment]
MuQSS is incompatible with kernel live patching. Fixed in 4.14/master.

**Comment by loxdegio** [comment]
I disabled MuQSS before compile.
Anyway pulled the correction same error.
I'll try re-enabling it, maybe if MuQSS is disabled some include could be missed

**Comment by loxdegio** [comment]
Enabling MuQSS it seems not show the error anymore

**Comment by heftig** [comment]
Should be fixed now.

**Comment by loxdegio** [comment]
It seems it is solved now, thank you :)
