### ISSUE TITLE
too few arguments to function ‘delayacct_blkio_end’

### ISSUE THREAD

**Issue by loxdegio** [zen-kernel/zen-kernel#117]
kernel/sched/MuQSS.c: In function ‘try_to_wake_up’:
kernel/sched/MuQSS.c:1970:3: error: too few arguments to function ‘delayacct_blkio_end’
   delayacct_blkio_end();
   ^
In file included from kernel/sched/MuQSS.c:41:0:
./include/linux/delayacct.h:125:20: note: declared here
 static inline void delayacct_blkio_end(struct task_struct *p)
                    ^
kernel/sched/MuQSS.c: In function ‘try_to_wake_up_local’:
kernel/sched/MuQSS.c:2033:4: error: too few arguments to function ‘delayacct_blkio_end’
    delayacct_blkio_end();
    ^
In file included from kernel/sched/MuQSS.c:41:0:
./include/linux/delayacct.h:125:20: note: declared here
 static inline void delayacct_blkio_end(struct task_struct *p)

Can you please check?

**Comment by perfect7gentleman** [comment]
confirm

**Comment by krasCGQ** [comment]
krasCGQ/linux-vanadium@489442aa5e7b
