### ISSUE TITLE
idle cpu usage issue

### ISSUE THREAD

**Issue by csoyuncu** [zen-kernel/zen-kernel#119]
I want to update my servers to Centos 7, but the server program I am using has too many CPUs when idle. As an example, if I use CentOS 5, the server program uses 0% CPU, but when I install CentOS 7 (in any modern kernel) my server program uses 4-7% CPU. I want to solve this. Thank you.

**Comment by damentz** [comment]
Are you reporting an issue for CentOS or Zen Kernel?  We will need more information like:

What CPU usage are you getting in the latest mainline kernel matching zen-kernel?
Is this different than when you run the same version with Zen Kernel?
Did you enable or disable MuQSS?

**Comment by csoyuncu** [comment]
i enabled and disable MUQSS, i tried both. But result is same. program uses %5 cpu at idle mod.

**Comment by damentz** [comment]
Well it sounds like your program is actually using 5% CPU at idle.

Closing ticket, this isn't a zen-kernel problem, if a problem at all.

**Comment by csoyuncu** [comment]
bro i dont report centos kernel. I use centos 7 and i compiled your zen kernel. But later my program started %5 cpu at idle. But this problem was no at centos 5 or centos 7 default kernel. When i installed your kernel, problem starting. Did you understand ? i dont know good english. do you know turkish?
