### ISSUE TITLE
Network Performance Degradation

### ISSUE THREAD

**Issue by zhouxiaobo500** [zen-kernel/zen-kernel#121]
I'm running on Arch Linux, using two versions of zen kernels: 4.14.5-1 and 4.15.1-2.
After the rolling update, the new kernels drops its network performance up to A-HALF, compared with SCP transmission. (eg. 100M/s vs. 50M+/s)
Testing environment keeps the system configuration remains the same excepts the versions of linux-zen and linux-zen-headers are different.

I don't know if the problem comes from upstream or not.

**Comment by heftig** [comment]
Does `sysctl net.ipv4.tcp_congestion_control=cubic` help?

**Comment by zhouxiaobo500** [comment]
After reloading the kernels and rebooting 4+ times, it seems as normal. Weird bug..
Anyway, tks your help!

**Comment by zhouxiaobo500** [comment]
The bug appears again..
Maybe it really comes from upstream..

![screenshot_20180208_181444](https://user-images.githubusercontent.com/3312865/35968063-add3be6e-0cba-11e8-9196-e15db1fe73be.png)
![screenshot_20180208_181945](https://user-images.githubusercontent.com/3312865/35968079-b8f67afc-0cba-11e8-9d18-5f5f11d4bc80.png)

The screenshot is captured from the client, while the host is using linux-zen 4.14.5-1.
