### ISSUE TITLE
[Arch Linux] Zen kernel only displays on HDMI and not on Laptop screen

### ISSUE THREAD

**Issue by staalmannen** [zen-kernel/zen-kernel#128]
As in title. Early during boot, the laptop screen goes black. This strange effect is not seen on the vanilla ARCH kernel.

Hardware:
ASUS K751Y laptop (AMD A8-7410)

**Comment by damentz** [comment]
Can you add the output of `inxi -b`?

Also, when at your desktop environment, does xrandr believe the screen is connected?

**Comment by damentz** [comment]
No response after 10 days, closing issue.  If this is still an issue, you can create a new ticket, but please provide more information about your system.
