### ISSUE TITLE
release tar balls not signed

### ISSUE THREAD

**Issue by deep-42-thought** [zen-kernel/zen-kernel#129]
Please sign the release tar balls. Otherwise we have to clone the repository (~2.1GB) to verify the signature instead of downloading the tar ball (~160MB).

**Comment by heftig** [comment]
There are no release tarballs to sign. Please use git. You don't have to download the entire repository on every release (if you do, fix your build process).

**Comment by deep-42-thought** [comment]
That's, what I meant:
https://github.com/zen-kernel/zen-kernel/archive/v4.18.9-zen1.tar.gz
linked from here:
https://github.com/zen-kernel/zen-kernel/releases/tag/v4.18.9-zen1
archbuild does a complete git clone - or am I missing some option there?

**Comment by damentz** [comment]
I think the github issue itself is confusing - the tags are signed, but the pkgbuild is doing a full clone on the tag before building: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/linux-zen

Maybe there's a way to specify a shallow clone?  Otherwise, the build could be updated to use the archive that github generates on every tag here, for instance: https://github.com/zen-kernel/zen-kernel/archive/v4.18.10-zen1.tar.gz

**Comment by heftig** [comment]
@deep-42-thought The GitHub archives aren't really official tarballs that we produce. GitHub just automatically links those from every tag created.

@damentz If the clone already exists, makepkg will just fetch, see https://git.archlinux.org/pacman.git/tree/scripts/libmakepkg/source/git.sh.in. Shallow clones aren't supported, I believe.

**Comment by deep-42-thought** [comment]
@damentz I'm referring to the linux-zen package.
@heftig Is it possible to upload signatures to the "not really official tarballs" from github as assets? - Look, how we're doing it with our keyring when we were still on github: https://github.com/archlinux32/archlinux32-keyring/releases
The problem with the "the next build will only fetch" assumption is, that this is only true if you're building on the same box and noone cleaned your source directory in the meantime - both is not true on archlinux32 build slaves.

**Comment by damentz** [comment]
@heftig this sounds like something we can make a common script for.  Specifically, https://developer.github.com/v3/repos/releases/#upload-a-release-asset

On every signed tag we publish, we can delete any assets produced by github, then upload a patch (.xz?) with its signature that applies to the base kernel.  I think that will make most package maintainers happy.

**Comment by damentz** [comment]
@deep-42-thought I wrote a script to turn a tag into a release and add an xzip compressed patch plus a detached signature.  Here's an example of the result:

https://github.com/zen-kernel/zen-kernel/releases/tag/v4.18.12-lqx1

And the script that created this release is under the liquorix-package repo: https://github.com/damentz/liquorix-package/blob/master/scripts/zk-update-assets.sh

Of course, this script will need to be run by @heftig (or a variation of it) on -zenNN tags.  Will this work for you?

**Comment by deep-42-thought** [comment]
yes, that would be perfect - thanks!

**Comment by heftig** [comment]
https://github.com/zen-kernel/zen-kernel/releases/tag/v4.18.13-zen1
