### ISSUE TITLE
occasionally wireless network failure with intel 3165

### ISSUE THREAD

**Issue by yw662** [zen-kernel/zen-kernel#134]
It use mac80211 and iwlwifi.

When it happens, the network will be disconnected suddenly, and will not recover for about 1 min, during which wpa_supplicant cannot start.

This seems to happen more often when the traffic is heavy.

There is nothing in dmesg, wpa_supplicant log and dhcpcd log during or before it happens.

**Comment by heftig** [comment]
We don't patch 80211 or iwlwifi stuff so this is an upstream issue.
