### ISSUE TITLE
BFQ build error

### ISSUE THREAD

**Issue by Defortio** [zen-kernel/zen-kernel#139]
kernel 4.20.14
Today..
`>git pull`
bfq ++++++++/--         (example)

`>make rpm-pkg`
.
.
.
ld: block/bfq-wf2q.o: in function `bfq_pid_to_str':
bfq-wf2q.c:(.text+0x3a0): multiple definition of `bfq_pid_to_str'; block/bfq-iosched.o:bfq-iosched.c:(.text+0x19b0): first defined here
ld: block/bfq-cgroup.o: in function `bfq_pid_to_str':
bfq-cgroup.c:(.text+0x330): multiple definition of `bfq_pid_to_str'; block/bfq-iosched.o:bfq-iosched.c:(.text+0x19b0): first defined here
make[3]: *** [scripts/Makefile.build:488: block/bfq.o] Error 1
make[2]: *** [Makefile:1062: block] Error 2

**Comment by heftig** [comment]
Should be fixed in master.
