### ISSUE TITLE
bfq error

### ISSUE THREAD

**Issue by Defortio** [zen-kernel/zen-kernel#144]
Hi, Steven/
After last update today >git fetch
any +++/--- bfq

ld: block/bfq-mq-iosched.o: in function `__bfq_bfqd_reset_in_service':
bfq-mq-iosched.c:(.text+0x45f0): multiple definition of `__bfq_bfqd_reset_in_service'; block/bfq-sq-iosched.o:bfq-sq-iosched.c:(.text+0x4560): first defined here
make[2]: *** [Makefile:1032: vmlinux] Error 1

**Comment by Defortio** [comment]
4.19/master

**Comment by damentz** [comment]
I resynced our bfq branch with Paolo's algodev-github/bfq-mq/bfq-mq-on-4.19 branch.  Seems like he rewrite some history and some commits we already cherry-picked were changed.
