### ISSUE TITLE
linux-zen 5.1.2.zen1-1 isn't found

### ISSUE THREAD

**Issue by sevenday4** [zen-kernel/zen-kernel#146]
I was trying to download and install linux-zen 5.1.2.zen1-1. But, this is the result I'm getting:

**Packages (1) linux-zen-headers-5.0.13.zen1-1

Total Download Size:   17.64 MiB
Total Installed Size:  99.28 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
error: failed retrieving file 'linux-zen-headers-5.0.13.zen1-1-x86_64.pkg.tar.xz' from mirror.dc02.hackingand.coffee : The requested URL returned error: 404
error: failed retrieving file 'linux-zen-headers-5.0.13.zen1-1-x86_64.pkg.tar.xz' from arch.mirror.constant.com : The requested URL returned error: 404
error: failed retrieving file 'linux-zen-headers-5.0.13.zen1-1-x86_64.pkg.tar.xz' from mirror.dc02.hackingand.coffee : The requested URL returned error: 404
error: failed retrieving file 'linux-zen-headers-5.0.13.zen1-1-x86_64.pkg.tar.xz' from mirror.sergal.org : The requested URL returned error: 404
error: failed retrieving file 'linux-zen-headers-5.0.13.zen1-1-x86_64.pkg.tar.xz' from mirror.sergal.org : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.**
Arch linux is lagging in update it's repo

**Comment by heftig** [comment]
Your primary mirror is lagging.
