### ISSUE TITLE
updated Linux-zen and linux-zen-headers not in arch repo

### ISSUE THREAD

**Issue by sevenday4** [zen-kernel/zen-kernel#147]
I was trying to download and install linux-zen 5.1.2.zen1-1. But, this is the result I'm getting:

**Packages (1) linux-zen-headers-5.0.13.zen1-1

Total Download Size:   17.64 MiB
Total Installed Size:  99.28 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
error: failed retrieving file 'linux-zen-headers-5.0.13.zen1-1-x86_64.pkg.tar.xz' from mirror.dc02.hackingand.coffee : The requested URL returned error: 404
error: failed retrieving file 'linux-zen-headers-5.0.13.zen1-1-x86_64.pkg.tar.xz' from arch.mirror.constant.com : The requested URL returned error: 404
error: failed retrieving file 'linux-zen-headers-5.0.13.zen1-1-x86_64.pkg.tar.xz' from mirror.dc02.hackingand.coffee : The requested URL returned error: 404
error: failed retrieving file 'linux-zen-headers-5.0.13.zen1-1-x86_64.pkg.tar.xz' from mirror.sergal.org : The requested URL returned error: 404
error: failed retrieving file 'linux-zen-headers-5.0.13.zen1-1-x86_64.pkg.tar.xz' from mirror.sergal.org : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.**

Packages (1) linux-zen-5.0.13.zen1-1

Total Download Size:   74.28 MiB
Total Installed Size:  79.01 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
error: failed retrieving file 'linux-zen-5.0.13.zen1-1-x86_64.pkg.tar.xz' from mirror.dc02.hackingand.coffee : The requested URL returned error: 404
error: failed retrieving file 'linux-zen-5.0.13.zen1-1-x86_64.pkg.tar.xz' from arch.mirror.constant.com : The requested URL returned error: 404
error: failed retrieving file 'linux-zen-5.0.13.zen1-1-x86_64.pkg.tar.xz' from mirror.dc02.hackingand.coffee : The requested URL returned error: 404
error: failed retrieving file 'linux-zen-5.0.13.zen1-1-x86_64.pkg.tar.xz' from mirror.sergal.org : The requested URL returned error: 404
error: failed retrieving file 'linux-zen-5.0.13.zen1-1-x86_64.pkg.tar.xz' from mirror.sergal.org : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.

**Comment by heftig** [comment]
Your primary mirror is lagging. Also, make sure to use `pacman -Syu`.

**Comment by sevenday4** [comment]
Thank you @heftig, I figured that the repo was behind. Linux-zen and headers are now installing like it's supposed to. I tried sudo pacman -Syu first thing, but it didn't work at the time. Could have been an issue at the aur or an issue with another package. But anyway, the issue is resolved.
