### ISSUE TITLE
exFAT could be back..

### ISSUE THREAD

**Issue by arter97** [zen-kernel/zen-kernel#151]
I've been working on making a better exFAT Linux kernel module since the existing one haven't been updated for a long time.

It's based on much newer sdFAT base by Samsung.

It supports regular Linux distros such as Ubuntu and inline kernel builds.

I remember zen-kernel having exFAT support before by using the unmaintained exfat-nofuse. Please consider reviewing the link below and adding exFAT support back to zen-kernel.

https://github.com/arter97/exfat-linux

Thanks :)

**Comment by heftig** [comment]
Are you submitting this one to the staging tree?

**Comment by arter97** [comment]
If you mean mainline staging tree, I asked mainline guys to have a look.

https://lore.kernel.org/lkml/20190914133951.16501-1-qkrwngud825@gmail.com/

**Comment by heftig** [comment]
We've been merging an updated exFAT (patchset v13 from the fsdevel list).
