### ISSUE TITLE
fsync support

### ISSUE THREAD

**Issue by SR-dude** [zen-kernel/zen-kernel#153]
Is there a branch that includes Valves experimental FUTEX_WAIT_MULTIPLE?
This is needed for fsync support. 

[link](https://lkml.org/lkml/2019/7/30/1399)

**Comment by damentz** [comment]
This feature was merged a while ago and recently had an opcode fix applied so proton can use it properly.

https://github.com/zen-kernel/zen-kernel/issues/150
https://github.com/zen-kernel/zen-kernel/issues/152

You can search closed issues next time if you want to see if features like this have already been asked/requested.
