### ISSUE TITLE
HID: Increase maximum report size allowed by hid_field_extract()

### ISSUE THREAD

**Issue by JanusDC** [zen-kernel/zen-kernel#154]
I have plenty of lines like the this one in the output of dmesg:
[ 1199.948962] hid-sensor-hub 001F:8087:0AC2.0004: hid_field_extract() called with n (192) > 32! (kworker/3:2)

The issue is easily fixable with this patch:
https://patchwork.kernel.org/patch/10844177/

Could you please consider adding such a patch?

**Comment by damentz** [comment]
Added patch to our 4.19, 5.2, and 5.3 misc branches and merged misc to master.

4.19: https://github.com/zen-kernel/zen-kernel/commit/face163a2ef728af8ed4d4923b56711ff882b350
5.2: https://github.com/zen-kernel/zen-kernel/commit/6e4dd2fd9f8b916202cbf01af304f7f1eca46eb7
5.3: https://github.com/zen-kernel/zen-kernel/commit/6ce1046e9255f4b1801ed618422e24ba00ca0a86
