### ISSUE TITLE
Updating Arch to linux-zen 5.3.8.1-1 renders system unbootable

### ISSUE THREAD

**Issue by soekarmana** [zen-kernel/zen-kernel#155]
installed linux-zen 5.3.8.1-1 because latest zen kernel headers point to this version, so i have no choice
dkms installed, reboot
arch cant find vmlinuz
troubleshooting with chroot, reinstall again linux-zen 5.3.8.1-1 from there
no vmlinuz found on /boot, and doesn't seems to generate initrd too
fortunately linux-zen-5.3.7 still on the pacman cache
downgrading to that version, vmlinuz and initrd generated successfully

opened the **linux-zen-5.3.8.1-1-x86_64.pkg.tar.xz** and **linux-zen-5.3.7.zen1-2-x86_64.pkg.tar.xz** with archive manager to inspect the content

**there are no :**
-  /boot/vmlinuz-linux.zen 
- /etc/mkinitcpio.d/linux-zen.preset
on the **linux-zen-5.3.8.1-1-x86_64.pkg.tar.xz**

is this supposed to be like this?
or am i doing something wrong here?
can i somehow install the linux-zen-5.3.7.zen1-2 kernel headers?

**Comment by heftig** [comment]
This is not a ZEN-specific issue. Please seek help in the Arch community.
