### ISSUE TITLE
Makefile contains unresolved conflict at branch 4.19/master

### ISSUE THREAD

**Issue by JesusRodriguezAcosta** [zen-kernel/zen-kernel#156]
Hi all.

I'm testing this branch due it is the last LTS one and because there is an unresolved bug on BFQ at 5.3 which is freezing the system when using KVM.

Just at the first lines of the file "Makefile" at root of the project you'll see and unresolved conflict.

Thanks for your time,
Jesus.

**Comment by damentz** [comment]
Hello, sorry about that. I resolved this earlier today while merging commits from 4.19.85: https://github.com/zen-kernel/zen-kernel/commit/9cd005ec59fb8e7d2c6847cea3595d8279dcbd5f
