### ISSUE TITLE
HP ACPI Fix - Not Sure if This Will Get Upstreamed Or Not

### ISSUE THREAD

**Issue by ilikenwf** [zen-kernel/zen-kernel#157]
Just an FYI, this seems to fix all the ACPI error spam on my Spectre, it apparently happens on most/all HP laptops including AMD.

1/2
https://lore.kernel.org/stable/20191122185641.60711-1-hdegoede@redhat.com/
2/2
https://lore.kernel.org/patchwork/patch/1158181/

**Comment by heftig** [comment]
This has been part of upstream v5.4.2.
