### ISSUE TITLE
TPM issue - IdeaPad 710s

### ISSUE THREAD

**Issue by linuxandria** [zen-kernel/zen-kernel#158]
I have the issue outlined here:
https://askubuntu.com/questions/926738/cant-load-failed-to-claim-resource-1

From that link, it states that this means my kernel doesn't support my TPM module. Any fix for this? Kinda an incovenience and security issue for windows

**Comment by damentz** [comment]
This looks to be a Lenovo specific problem with this laptop.  Here's a news article[1] pointing out that the "Linux only" BIOS is the only way to access your drives.  There doesn't appear to be a way to have Windows and Linux coexist on your laptop.

[1] https://www.laptopmag.com/articles/lenovo-yoga-900-ideapad-710s-linux

**Comment by linuxandria** [comment]
> This looks to be a Lenovo specific problem with this laptop. Here's a news article[1] pointing out that the "Linux only" BIOS is the only way to access your drives. There doesn't appear to be a way to have Windows and Linux coexist on your laptop.
> 
> [1] https://www.laptopmag.com/articles/lenovo-yoga-900-ideapad-710s-linux

Which is why of course this issue only occurs on Zen kernel and not the standard one 😊

**Comment by damentz** [comment]
What distribution are you running?  Can you provide the output of **inxi -b**?

**Comment by damentz** [comment]
@heftig can you take a look?  Might be a configuration difference to stock Arch.  Or it could be a custom patch in another distribution's stock kernel.

**Comment by heftig** [comment]
I have no idea what's going on here. The linked StackOverflow thread only mentions Ubuntu.

**Comment by damentz** [comment]
Ok, well pending more information, we'll close this issue out.  What we're looking for is what to compare Zen to.  If it's Arch stock to Zen, then we can compare the patches/config.  If it's Ubuntu to Zen, that's a more difficult difference to look through, but still possible.

**Comment by linuxandria** [comment]
To be 100% fair I no longer have the device. But it was Ubuntu 19.10
