### ISSUE TITLE
5.5-zen1: Fsync not working

### ISSUE THREAD

**Issue by ryester27** [zen-kernel/zen-kernel#160]
Fsync is not being detected by Proton/Steam when using the 5.5-zen1 kernel. Proton logs say that it is defaulting to esync when this kernel is installed. Downgraded back to 5.4.15.zen1-1, and appears to be working fine.

Using Arch Linux. Could also be a package problem since 5.5 is still in the testing repo

**Comment by heftig** [comment]
Yeah, I forgot to port it from 5.4. Glad to hear it's in use, at least.

Fixed in 5.5/master, pending next release. 5.5-zen1 will not leave Arch's [testing] anyway. 5.5.1-zen1 might.

**Comment by ryester27** [comment]
> Glad to hear it's in use, at least.

I'm glad you did :) The binary kernel provided by Valve isn't usually kept up-to-date, and all the other solutions on Arch require kernel compiling
