### ISSUE TITLE
no blkio.throttle.*

### ISSUE THREAD

**Issue by SlavaGavrilin** [zen-kernel/zen-kernel#161]
```
root@host /sys/fs/cgroup/blkio # ls
backup                                blkio.bfq.io_serviced_recursive  cgroup.sane_behavior  system.slice
blkio.bfq.io_service_bytes            blkio.reset_stats                lxc                   tasks
blkio.bfq.io_service_bytes_recursive  cgroup.clone_children            notify_on_release     user.slice
blkio.bfq.io_serviced                 cgroup.procs                     release_agent

```
blkio.throttle.read_bps_device
blkio.throttle.read_iops_device
blkio.throttle.write_bps_device
blkio.throttle.write_iops_device

do not exists, impossible to use io throttling with cgroup

**Comment by heftig** [comment]
`uname -a` please.

**Comment by SlavaGavrilin** [comment]
cat /proc/version
Linux version 5.4.14-zen-skylake (root@host.mypc.net) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #1 ZEN SMP Fri Jan 24 11:21:12 CET 2020

**Comment by SlavaGavrilin** [comment]
damn. it looks like a reason:
grep -i throttl .config
# CONFIG_BLK_DEV_THROTTLING is not set

**Comment by heftig** [comment]
Yes, whoever configured your kernel did not enable the necessary config. This isn't an issue with our sources.
