### ISSUE TITLE
Recently updated to 5.5.1-zen1-1-zen, but sound card is missing

### ISSUE THREAD

**Issue by dragonation** [zen-kernel/zen-kernel#163]
Laptop: Google ChromeBook Pixel 2015
UEFI: Mr.ChromeBox
System: ArchLinux
The bdw-rt5677 is missing in the new build, and no sound device is detected in the new release of kernel

Maybe this reference is related to the issue:

https://bugzilla.kernel.org/show_bug.cgi?id=204237

I have checked to kernel config:
```
CONFIG_SND_SOC_INTEL_SST_TOPLEVEL=y
CONFIG_SND_SOC_SOF_INTEL_TOPLEVEL=y
```

According to the reference above, this may cause some conflicts

**Comment by damentz** [comment]
This looks like a combination of bug/misconfiguration that might get resolved in the future.  In the meantime, on Liquorix, I disabled SOF drivers where classic drivers already exist:

https://github.com/damentz/liquorix-package/commit/350b4b4f1d633c130006fbd38895c757218d64c9

Maybe the official zen kernel should take a similar approach until drivers are fixed.  Assigning to @heftig so he can take a look.

**Comment by heftig** [comment]
5.5 added a new `snd-intel-dspcfg` module which centralizes driver selection. Please try booting with `snd_intel_dspcfg.dsp_driver=2`.

**Comment by dragonation** [comment]
> 5.5 added a new `snd-intel-dspcfg` module which centralizes driver selection. Please try booting with `snd_intel_dspcfg.dsp_driver=2`.

It works! Thanks a lot.
