### ISSUE TITLE
zram

### ISSUE THREAD

**Issue by SlavaGavrilin** [zen-kernel/zen-kernel#167]
What parameters should be adjusted to enable Zram?
It doesn't work by default as expected.

**Comment by damentz** [comment]
Both Arch and Gentoo have good resources on setting up zram on your system:

https://wiki.archlinux.org/index.php/Improving_performance
https://wiki.gentoo.org/wiki/Zram

I've personally used gentoo's wiki since their documentation using udev is better than Arch's.

**Comment by SlavaGavrilin** [comment]
I installed zram-config service and it failed to start. checked-just one /dev/zram0 was created. actually zram works, only script failiing.
