### ISSUE TITLE
linux-zen 5.6.5 have a performance issue

### ISSUE THREAD

**Issue by alium** [zen-kernel/zen-kernel#169]
Hi,
I have been using linux-zen for some time now. thank you for it.
After the last update 5.6.4 -> 5.6.5, linux-zen encountered performance issues.
The bug was already in 5.6.5-zen1, but zen3 has the same problem.
The error is reflected for example in the game Cities: Skylines, where loading the game takes almost 6 minutes instead of the usual 1:25 min. The whole game then lags. 

Unfortunately, I didn't find any bug or any announcement in dmesg. After the downgrade to 5.6.4 the bug is gone, so I tested Archlinux's linux-5.6.5, where the bug does not occur. So it is probably in some patch for linux-zen-5.6.5.

**Comment by alium** [comment]
dmesg:
[linux-zen.txt](https://github.com/zen-kernel/zen-kernel/files/4503329/linux-zen.txt)
[linux.txt](https://github.com/zen-kernel/zen-kernel/files/4503331/linux.txt)

lspci:
[lscpi.txt](https://github.com/zen-kernel/zen-kernel/files/4503333/lscpi.txt)

some screenshots:
![bug](https://user-images.githubusercontent.com/1759414/79749934-5e1e9780-8310-11ea-8139-f374c94bbcac.png)
![normal](https://user-images.githubusercontent.com/1759414/79750011-7db5c000-8310-11ea-98b1-df8553a50365.png)

**Comment by heftig** [comment]
linux-zen 5.6.4.zen1-1 to 5.6.5.zen1-1 contains the same changes as linux 5.6.4.arch1-1 to 5.6.5.arch1-1.

**Comment by heftig** [comment]
5.6.5.zen2-1 added more stuff, though. Are you sure you mean zen1 and not zen2?

**Comment by alium** [comment]
sorry, you are right I tested zen2 (has this performace bug and this shutdown problem)
[2020-04-19T11:59:22+0200] [ALPM] upgraded linux-zen (5.6.4.zen1-1 -> 5.6.5.zen2-1)
[2020-04-19T11:59:25+0200] [ALPM] upgraded linux-zen-headers (5.6.4.zen1-1 -> 5.6.5.zen2-1)

**Comment by heftig** [comment]
@damentz Sounds like the fragmentation fix hurts a lot.

**Comment by damentz** [comment]
@heftig I reverted the patch, can you push out a new release?

**Comment by alium** [comment]
tested, reverting that patch resolved the performance issue. Thank you.

**Comment by damentz** [comment]
Great!  Marking issue as resolved.
