### ISSUE TITLE
systemd-modules-load[289]: Failed to find module 'vboxpci'

### ISSUE THREAD

**Issue by bkalpa9** [zen-kernel/zen-kernel#171]
I was unable to mount and use USB devices like usb hdd, usb wificard on VirtualBox guests. After some troubleshooting, it seems like vboxpci module was missing in the kernel source. I am using Archlinux, installed and updated virtualbox-host-dkms 6.1.6-1, linux-zen-headers 5.6.11.zen1-1, but still having the issue. 
Here is log:

arch# modprobe vboxpci
modprobe: FATAL: Module vboxpci not found in directory /lib/modules/5.6.11-zen1-1-zen

arch# /usr/lib/systemd/systemd-modules-load
Failed to find module 'vboxpci'

**Comment by heftig** [comment]
VirtualBox 6.1 dropped PCI passthrough support.

https://www.virtualbox.org/wiki/Changelog
