### ISSUE TITLE
OpenRGB patch piix4 duplicated 

### ISSUE THREAD

**Issue by lolzballs** [zen-kernel/zen-kernel#176]
I noticed that I was able to get OpenRGB working out of the box a few patches ago but since 5.7.6 (I think) it has no longer worked for me. My system is an AMD system which relies on the `i2c-piix4` part of the patch.

Looking through the sources I noticed that 2c54a16 was introduced by the mainline kernel which adds the piix4 part of the OpenRGB patch. However it's slightly modified so that the initialization is [duplicated](https://github.com/zen-kernel/zen-kernel/blob/af58394d801922787a81d867085534b76e899886/drivers/i2c/busses/i2c-piix4.c#L979-L988). The first initialization succeeds which causes the second one to always fail with `EBUSY`, which means `piix4_add_adapter` is never called right below it.

For reference this is the dmesg output:
```
[    5.646649] piix4_smbus 0000:00:14.0: SMBus Host Controller at 0xb00, revision 0
[    5.646651] piix4_smbus 0000:00:14.0: Using register 0x02 for SMBus port selection
[    5.646734] piix4_smbus 0000:00:14.0: Auxiliary SMBus Host Controller at 0xb20
[    5.646756] piix4_smbus 0000:00:14.0: SMBus region 0xb20 already in use!
```

You can see that it outputs that 0xb20 is already in use, which means `piix4_setup_sb800` has returned with `EBUSY`.

I would create a patch to fix this but I really have no idea where to submit it :disappointed:

**Comment by damentz** [comment]
@lolzballs next release of Zen and Liquorix will have the deduped init code for piix4_setup_sb800.  And thanks for opening an issue, we wouldn't have noticed it otherwise :smile:

**Comment by lolzballs** [comment]
Wow that was quick! I've been wanting to get more involved in the things I use so it's my pleasure to help out.

**Comment by Battler624** [comment]
Is this still an issue? I tried Linux-Zen and opened OpenRGB but my dram didn't showup (asus mobo), I am guessing this is reason?
