### ISSUE TITLE
black screen with mouse cursor after login with kernel 5.7.14 on Braswell and Cherrytrail

### ISSUE THREAD

**Issue by RJVB** [zen-kernel/zen-kernel#177]
I installed the 5.7.0.14.1-liquorix kernel on Devuan Beowulf (from the Debian Buster repo). After logging in I'm getting an all-black screen with just the mouse cursor visible on my Braswell (N3150) and Cherrytrail (some Atom CPU in a Chuwi hybrid PC) PCs.  The SDDM greeter screen is fine (as long as I don't invoke the DE switcher) and the VTYs work fine too. Hitting Shift-Alt-F12 gives me a somewhat wonky view on the Konsole kpart (but not any window decoration or panel).

If I boot an HP laptop with a somewhat recent i3 with this install the desktop appears just fine.

I've seen this exact same issue with a stock 5.7.14-ck1 kernel I built myself so the issue is either upstream or in the ck1 patch ... but maybe you can find and fix whatever regression is causing this?

**Comment by damentz** [comment]
Have you tried running 5.7.13 at any point?  The 5.7.14 kernel resolves a vulnerability with Linux's random implementation and has no other functional change.

**Comment by RJVB** [comment]
Sorry, no.

Checking back the changelogs the last 5.7 version that mentions i915 is 5.7.11 (or 5.7.10 which has a change that seems more relevant). I'd be working my way back through versions were it not for the fact that both systems take too much time to install a new kernel and build the ZFS kmods I need; the Baytrail is the one I can reboot at will BUT I currently can't have it on mains power when booted off the Linux USB drive...

**Comment by RJVB** [comment]
Actually, Devuan's linux-image-5.7.0-0 contains 5.7.10 . There's a patch for Baytrail tablets in 5.7.9 IIRC, but its description sounds so specific that it seems unlikely to cause the same issue on a Cherrytrail notebook...

**Comment by RJVB** [comment]
<OT>

Out of curiosity I installed the 5.6.0.19 liquorix kernel on my Baytrail tablet which according to inxi in fact appears to be a Cherrytrail one
1st thing I noticed upon logging in: this kernel detects the powersupply and battery... yay! :)

Do you include the patch to make zswap use B-Trees? And I presume you don't include the one that re-exports __begin,end_fpu()? If I want to rebuild the Liquorix kernel with those 2 patches plus Westmere compiler optimisation (like Clear Linux does IIUC), how would I best grab the sources so I don't have to apply all other patches myself?
</OT>

```
System:    Host: Bacxa Kernel: 5.6.0-19.1-liquorix-amd64 x86_64 bits: 64 Console: N/A 
           Distro: Devuan GNU/Linux 3 (beowulf) 
Machine:   Type: Desktop System: CHUWI INNOVATION AND (SHENZHEN) product: Hi10 pro tablet v: Reserve 
           serial: xxxx 
           Mobo: Morshow model: Cherry Trail CR v: V100 serial: xxxx UEFI: American Megatrends 
           v: C109D_X_T.301 date: 05/24/2019 
Battery:   ID-1: axp288_fuel_gauge charge: 44% condition: N/A 
CPU:       Topology: Quad Core model: Intel Atom x5-Z8350 bits: 64 type: MCP L2 cache: 1024 KiB 
           Speed: 559 MHz min/max: 480/1441 MHz Core speeds (MHz): 1: 480 2: 844 3: 1743 4: 867 
Graphics:  Device-1: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Configuration Registers 
           driver: i915 v: kernel 
           Display: server: X.Org 1.20.4 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1200~55Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics (Cherrytrail) v: 4.5 Mesa 18.3.6 
Audio:     Device-1: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series Imaging Unit 
           driver: intel_atomisp2_pm 
           Sound Server: ALSA v: k5.6.0-19.1-liquorix-amd64 
Network:   Message: No Device data found. 
           Device-1: Ralink RT5372 Wireless Adapter type: USB driver: rt2800usb 
           IF: wlx9cefd5fcf14b state: up mac: 9c:ef:d5:fc:f1:4b 
           IF-ID-1: wlan0 state: down mac: 58:b3:fc:2f:ed:bb 
Drives:    Local Storage: total: 118.00 GiB used: 13.99 GiB (11.9%) 
           ID-1: /dev/mmcblk0 model: S0J9F8 size: 58.24 GiB 
           ID-2: /dev/sda type: USB vendor: Samsung model: Flash Drive FIT size: 59.75 GiB 
Partition: ID-1: / size: 31.56 GiB used: 13.99 GiB (44.3%) fs: btrfs dev: /dev/sda3 
Swap:      ID-1: swap-1 type: partition size: 8.00 GiB used: 0 KiB (0.0%) dev: /dev/sda5 
Sensors:   System Temperatures: cpu: 50.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Info:      Processes: 233 Uptime: 5m Memory: 3.77 GiB used: 591.9 MiB (15.3%) Shell: sh inxi: 3.1.05 
```

Hmmm, `driver: modesetting unloaded` ... I do not have `nomodeset` appear anywhere AFAIK; could this be what causes my issue with 5.7.x?

**Comment by RJVB** [comment]
Sorry for the mix-up in CPU/CPU codenames...

Interesting observation: kernel 5.6.19 (liquorix or a home build with just the ck2 patchset and -march=westmere) requires slightly different i915 parameter settings depending on the userland on my N3150 system:

- when I run it with Devuan Beowulf, graphics behave fine with `enable_psr=1 fastboot=1 enable_fbc=1`
- when I run it on my KUbuntu 14.04 system (with among others updates to Mesa) I need to set `enable_psr=0` in order to avoid a bad case of flickering.

**Comment by damentz** [comment]
@RJVB is this still an issue with 5.9?

**Comment by RJVB** [comment]
I'll try to install and this from a pre-built repo ASAP and report back. My N3150 is back to an older 4.14 kernel (4.14.193 froze on unsuspend too often).

**Comment by RJVB** [comment]
Apparently not on the Cherrytrail tablet PC. I can't check on the other one for now because it uses ZFS and the 0.8.4 version I have installed doesn't support newer than kernel 5.6 .

**Comment by RJVB** [comment]
Let's hope Intel finally got their act together and worked the kinks out of the i915 driver...
