### ISSUE TITLE
5.7/upstream-updates is missing "Linux 5.7.15" update

### ISSUE THREAD

**Issue by Techwolf** [zen-kernel/zen-kernel#178]
As the title says, "Linux 5.7.15" was not merged into 5.7/upstream-updates. This makes creating a patch by using "git diff remotes/origin/5.7/upstream-updates...remotes/origin/5.7/master" fail to make a patch that work with upstream 5.7.15. While said patch does work with 5.7.14, the build packing system that I use, "gentoo", will try to apply that patch to 5.7.15 and fails.

**Comment by damentz** [comment]
Sorry about that, I forgot to push up my local branch after generating a patch for Liquorix 5.7.15-lqx1.

5.7/upstream-updates now points to 5.7.15: https://github.com/zen-kernel/zen-kernel/commit/0e446529d34888ac57fe059ec32e9114a381c800

**Comment by Techwolf** [comment]
Thank you for the fast fix. Was not expecting that so soon.
