### ISSUE TITLE
Config 4.19.10-zen1 for archlinux

### ISSUE THREAD

**Issue by 88cretin88** [zen-kernel/zen-kernel#181]
hello, I wanted to build kernel version 4.19.10-zen1 for archlinux. I need a configuration file for this distribution, where can I get this config?  Thank you in advance.

**Comment by sirlucjan** [comment]
It is probably quite obvious that here:

https://git.archlinux.org/svntogit/packages.git/tree/trunk/config?h=packages/linux-zen&id=b2db1c8b8e85f16a7351843ecdadceeb3be97743

There is no newer config for version 4.19 - the next modification took place with the release of version 4.20.

**Comment by heftig** [comment]
Yes, thanks. That was the config used.

**Comment by 88cretin88** [comment]
many thanks for the help
