### ISSUE TITLE
Anbox modules installing error

### ISSUE THREAD

**Issue by azatserikbaev** [zen-kernel/zen-kernel#183]
Hello! I'm running linux-zen 5.8.12.zen1-1 kernel and trying to install Anbox. 
When i try to install ashmem and binder modules it returns an 
"dkms install --no-depmod -m anbox-modules-binder -v r1282.170f1e0 -k 5.8.11-zen1-1-zen' returned 10" error (same with 5.8.12.zen1-1 version).

I guess it is because the following entries are missing in kernel config:
CONFIG_ASHMEM=y
CONFIG_ANDROID=y
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"

Tried to use [anbox-modules-dkms-git](https://aur.archlinux.org/packages/anbox-modules-dkms-git/) from AUR, but it return same error as above.

Is it possible to add these entries to upstream?

Thank you.

**Comment by damentz** [comment]
@heftig can you enable the android modules required?  I added these modules recently to Liquorix and there's been no issues:
https://github.com/damentz/liquorix-package/commit/76b6f0457999bd55eedaee44f2fe238336cb0bb3

**Comment by azatserikbaev** [comment]
Successful build with  
`CONFIG_ANDROID_BINDERFS=y`


Thank you very much!

**Comment by heftig** [comment]
It doesn't build.

```
ERROR: modpost: "init_ipc_ns" [drivers/android/binder_linux.ko] undefined!
ERROR: modpost: "put_ipc_ns" [drivers/android/binder_linux.ko] undefined!
make[1]: *** [scripts/Makefile.modpost:111: Module.symvers] Error 1
```

**Comment by heftig** [comment]
Fixed: `CONFIG_ANDROID_BINDERFS` needs to be off.

**Comment by azatserikbaev** [comment]
Well, that's strange.
Here's my /proc/config.gz
Lines 8729-8734:
```
#
# Android
#
CONFIG_ASHMEM=y
# CONFIG_ION is not set
# end of Android
```
Lines 9742-9750:
```
#
# Android
#
CONFIG_ANDROID=y
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"
# CONFIG_ANDROID_BINDER_IPC_SELFTEST is not set
# end of Android
```
Here's my config when building.
Lines 9743-9750:
```
#
# Android
CONFIG_ASHMEM=y
CONFIG_ANDROID=y
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"
# end of Android
```
Also, there's an empty block, idk if it changes something
Lines 8732-8735:
```
#
# Android
#
# end of Android
```

**Comment by azatserikbaev** [comment]
Anyway, it works. Thanks again
