### ISSUE TITLE
Heavy IO causing Stuttering/5-second-pause when writing to USB3 devices?

### ISSUE THREAD

**Issue by SoftwareGuy** [zen-kernel/zen-kernel#187]
Greetings,

I'm not sure if this is a Zen Kernel specific issue or if it's a quirk that's known but I'm getting stuttering when I'm doing heavy IO to USB3 Hard Disks. I noticed this today when I was copying data from a LVM slice on a SATA SSD to a disk image on a NTFS-formatted USB3 disk, where the system would pause for a few seconds, then unpause. DDRescue would then report a "spike" up to 400MB/s, then going back down to the normal 150 - 180MB/s copy rate.

During this pause, if I had music playing it would actually pause as well (VLC would say it's playing but just "hang"). The mouse cursor would freely be able to move around, however my clicks wouldn't be registered until the system responded again, which would cause the whole "trigger happy" speed up sometimes seen under heavy load on GUIs. One of the hangs actually caused the nvidia kernel driver to report a memory allocation failure triggered by `kwin_x11` but I doubt that's related to Zen patches itself since the Arch Linux nVidia DKMS modules have been working fine.

Dmesg does not reveal any kernel hung tasks or oops/warnings, everything seems to be running normally. The only other thing I could think of was I hadn't restarted my workstation in some time and it had about 600MB of data in swap.

Could muQSS or another modification be affecting IO performance? I'm thinking muQSS is more CPU task scheduling and not disk scheduling. Or does muQSS handle disk IO as well as CPU activity?

Is there anything we can do to see if it's a kernel quirk, or something lower-level (hardware)?

**Hardware:**
MB: ASUS PRIME X570 PRO/CSM
CPU: Ryzen 5 2600 @ Stock Clocks
RAM: 32GB DDR4-2666
OS: Arch Linux w. `linux-zen` kernel
`uname -a`: `Linux tenryuu-kai-san 5.8.14-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 08 Oct 2020 00:01:25 +0000 x86_64 GNU/Linux`

Note: I was the same one who reported the high load averages on Funtoo, however I have since migrated to Arch Linux.

**Comment by damentz** [comment]
I believe this is actually a bug from the latest nvidia short lived release, 455.23.04.  When I experienced this same issue I switched to nvidia's latest vulkan drivers, they don't seem to have that problem.

Try either downgrading or switching to a different driver release from nvidia and your stuttering will go away.

**Comment by SoftwareGuy** [comment]
It looks like I might have the latest version according to Arch as I did run an update after the stuttering was going on, and pacman reports the latest installed version is 455.28. I will do some heavy IO today to the external USB3 drive in question and see if this stuttering reappears.

**Comment by damentz** [comment]
Closing this issue out, latest drivers don't cause this issue for me.

**Comment by damentz** [comment]
And referencing actual issue: https://forums.developer.nvidia.com/t/455-23-04-page-allocation-failure-in-kernel-module-at-random-points/155250/9

Nvidia has acknowledged the issue.
