### ISSUE TITLE
Fsync not working (5.9.1-zen1-1-zen)

### ISSUE THREAD

**Issue by BrosephJ** [zen-kernel/zen-kernel#188]
As of now Lutris is telling me FSYNC_NOT_SUPPORTED even though it was working before I updated to 5.9.1-zen1-1-zen from 5.8.14. Has this functionality been removed or is this simply an oopsy?
![Screenshot_2020-10-17_17-03-28](https://user-images.githubusercontent.com/5185864/96355799-cf11f280-109a-11eb-9462-f07a23b121aa.png)

**Comment by heftig** [comment]
The v3 patch series posted is incompatible with 5.9 and there have been no updates since then.

It might be a simple fix, but I'm not willing to maintain a patchset that Valve doesn't seem to care about.

**Comment by BrosephJ** [comment]
I swapped to a [different 5.9 kernel](https://github.com/Frogging-Family/linux-tkg/tree/master/linux59-tkg) with fsync working so maybe it is just a simple thing? There's a [patch file](https://github.com/Frogging-Family/linux-tkg/blob/master/linux59-tkg/linux59-tkg-patches/0007-v5.9-fsync.patch) you may want to check out.

Perhaps @Plagman can chime in on this. I was originally not planning to add any [third party repos](https://lonewolf.pedrohlc.com/chaotic-aur/) to my install but no fsync on this kernel made me. ;-(

**Comment by heftig** [comment]
AFAIU Proton can run without it with a minor performance hit so I don't think this feature is particularly important.

**Comment by Plagman** [comment]
We definitely care - the work upstream has morphed into a larger task of redoing the whole futex syscall, so it's taking a while. The current series is very useful in the meantime, so we'd be happy to do the rebasing work on our end if it's non-obvious. While you're right that it's a minor perf difference compared to the esync alternative, some games cannot work with esync and need this to perform acceptably.

**Comment by heftig** [comment]
Thanks for your feedback.

I'll try to rebase the patches. It seems the needed change is just removing the `put_futex_key` calls, which were already no-ops in v5.8.

**Comment by heftig** [comment]
@BrosephJ  Please test 5.9.1-zen2.

**Comment by BrosephJ** [comment]
> @BrosephJ Please test 5.9.1-zen2.

Working! Much appreciated. I'm honestly surprised it showed up in the Arch repos that fast. Not sure I could live without this distro.
![yeehaw](https://media.giphy.com/media/WDtCGLCXBAgow/source.gif)
