### ISSUE TITLE
After following instructions, still getting: ==> ERROR: A failure occurred in build()

### ISSUE THREAD

**Issue by SwankyBarbecue4** [zen-kernel/zen-kernel#192]
Hi,

After running ```yay -S linux-zen```, I still get this error. I have already followed these instructions and ran ```makepkg```, which  was able to successfully built the kernel.

What do I do now?

Thanks! :)
```
==> WARNING: This package does not ship a kernel config.

==> WARNING: Thus it is up to you to create a one that fits your needs.
==> WARNING: Navigate to '/home/mj/.cache/yay/linux-zen-git/src/build'
==> WARNING: and either run 'make menuconfig' or if you want to use an existing config,
==> WARNING: save it as '.config' and run 'make oldconfig' in order to update it.
==> WARNING: You could also grab the one used for the mainline zen-kernel package from
==> WARNING: https://raw.githubusercontent.com/archlinux/svntogit-packages/packages/linux-zen/trunk/config
==> WARNING: Having done that you can run 'makepkg' again.

==> ERROR: A failure occurred in build().
    Aborting...
error making: linux-zen-git
```

**Comment by heftig** [comment]
Use `pacman -S linux-zen` to install th Zen kernel on Arch Linux. Any other method is inappropriate.

**Comment by SwankyBarbecue4** [comment]
@heftig Sorry, but I am a bit confused. Isn't linux-zen an AUR package, and therefore cannot be found by pacman? `sudo pacman -S linux-zen' returns 'error: target not found: linux-zen'

**Comment by heftig** [comment]
linux-zen is part of the `extra` repository.
