### ISSUE TITLE
"setfattr -h" fails silently

### ISSUE THREAD

**Issue by LHLaurini** [zen-kernel/zen-kernel#193]
When building Linux from Scratch, the test suite for attr fails. When I switch back to the vanilla kernel, it passes.

I'm able to reproduce the issue manually:

Zen kernel:
```sh
$ touch f
$ ln -s f l
$ setfattr -n user.filename -v f l
$ getfattr -d f l
# file: f
user.filename="f"

# file: l
user.filename="f"

$ setfattr -h -n user.filename -v f l
$ echo $?
0
$ 
```

`setfattr -h` should fail with `setfattr: l: Operation not permitted`, but it doesn't.

Vanilla:
```
$ touch f
$ ln -s f l
$ setfattr -n user.filename -v f l
$ getfattr -d f l
# file: f
user.filename="f"

# file: l
user.filename="f"

$ setfattr -h -n user.filename -v f l
setfattr: l: Operation not permitted
$ 
```

Also, it works as expected with both kernels only when run as root.

I'm running Arch:
```sh
$ pacman -Q linux{,-zen}
linux 5.9.9.arch1-1
linux-zen 5.9.9.zen1-1
```

**Comment by heftig** [comment]
The cause is f50081c9e83eb1bf9607a2bdd36576ea9064a94f, part of the clearlinux patchset. @damentz

**Comment by damentz** [comment]
Reverted the patch. It's probably a feature used on clearlinux itself, but no one asked for it before merging clear linux patches to Zen Kernel, so it's safe to remove.
