### ISSUE TITLE
Where exactly do I apply the patches?

### ISSUE THREAD

**Issue by Fire100265** [zen-kernel/zen-kernel#195]
I have tried applying the patches to the kernels from kernel.org and I get the error that the patch has already been applied. Where can I use the patches?

**Comment by damentz** [comment]
The patches part of release tags apply to the base kernel, not the minor versions.  For example, if you wanted to apply the patch at https://github.com/zen-kernel/zen-kernel/releases/download/v5.10.6-lqx1/v5.10.6-lqx1.patch.xz, you use the base kernel at https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.10.tar.xz.

**Comment by Fire100265** [comment]
Thank you for your reply. I'll use the patches with kernel 5.10.
