### ISSUE TITLE
Few problematic patches from Clear Linux

### ISSUE THREAD

**Issue by arter97** [zen-kernel/zen-kernel#198]
There are several patches from Clear Linux that are problematic when used on regular distros.

1. 1ad3ad217d84343cfc1dc9d668cb26ad76a7c993 ("nvme workaround")

This effectively disables NVMe's APST for presumably better performance.
This should be done only for desktop devices as it increases power consumption. It also prevents package C state to reach lower levels than PC3.

This can be checked by
```
nvme get-feature -f 0x0c -H /dev/nvme0n1
```

This should be reverted and the user must opt-in to disabling APST themselves, if they want to maximize NVMe performance.

2. 4da6578980b7c4832946a1263213559710b1449d ("print fsync count for bootchart")

This is for debugging purposes, increases the size of `struct task_struct` needlessly, performs unnecessary operations through the block layer.

3. 86fb7d6d7744cac27bd5d5a664bd85a845da3412 ("intel_idle: tweak cpuidle cstates")

As mentioned in the original commit:
```
Tune intel_idle to be a bit less agressive;
Clear linux is cleaner in hygiene (wakupes) than the average linux,
so we can afford changing these in a way that increases
performance while keeping power efficiency
```

The commit message itself contradicts the general target audience for zen-kernel.

**Comment by damentz** [comment]
@arter97 I agree with all your points made.  Most of the ClearLinux patches were added without too much review with the assumption that it was improving performance as a whole.  Seems that there's a lot of quirky patches for their specific use cases that don't represent the average desktop and laptop.
