### ISSUE TITLE
binder and ashmem support

### ISSUE THREAD

**Issue by lgoette** [zen-kernel/zen-kernel#199]
Since the latest 5.10.13 release it seems like binder and ashmem modules are not included anymore. It worked 2 days ago but now they seem gone.

modprobe -a binder-linux ashmem-linux
modprobe: WARNING: Module binder-linux not found in directory /lib/modules/5.10.13-zen1-1-zen
modprobe: WARNING: Module ashmem-linux not found in directory /lib/modules/5.10.13-zen1-1-zen

**Comment by heftig** [comment]
Yes, I've decided to drop them as they were not enough to run Anbox.

**Comment by oleg-rom** [comment]
> Yes, I've decided to drop them as they were not enough to run Anbox.

I am sorry, I don't understand. It worked before for me, now for sure there is no way to run Anbox. Or is there?

**Comment by lgoette** [comment]
> > Yes, I've decided to drop them as they were not enough to run Anbox.
> 
> I am sorry, I don't understand why the support for android was dropped. It worked fine before for me, now for sure there is no way to run Anbox. Or is there? Please help.

The way is: build a kernel or revert to the old zen kernel. (I don't recommend either)

**Comment by oleg-rom** [comment]
> The way is: build a kernel or revert to the old zen kernel. (I don't recommend either)

ok, if either is not recommended, what would be the better option?

**Comment by heftig** [comment]
Was my information wrong, then? Also, https://aur.archlinux.org/packages/linux-zen-anbox/ existed all this time to _add_ Anbox support because the kernel in [extra] did not work.

**Comment by lgoette** [comment]
> > The way is: build a kernel or revert to the old zen kernel. (I don't recommend either)
> 
> ok, if either is not recommended, what would be the better option?

When you ask like this, it would be the outdated kernel release mentioned above. I am not an it-sec expert. Can someone give insights on using an kernel which is no longer updated. My guess is if an unknown security issue exists, you have to decide between using anbox and getting a fixed kernel version.

**Comment by lgoette** [comment]
> Was my information wrong, then? Also, https://aur.archlinux.org/packages/linux-zen-anbox/ existed all this time to _add_ Anbox support because the kernel in [extra] did not work.

I dont know what you are exactly talking about but I was using the zen release from the official repositories and anbox worked for me to the point you dropped the modules. The Aur package you mentioned seems like just the v5.10.12-zen1 release or am I wrong and it is an anbox support addition to the latest zen release?

**Comment by damentz** [comment]
The real issue here is that the patches from Debian appear to be incomplete or incompatible with 5.10.  `linux-zen` built the android config options without `binderfs`, a requirement for Anbox to work: https://github.com/archlinux/svntogit-packages/commit/f77b539170cb031785fa2eb97b2c62343684f2a9#diff-6503b30d816e211d1909eed3e1eff5f9105fdc48f5735921a59f4906f99415beL8879

And here's documentation specifying binderfs must be enabled.  Maybe it should be removed if it's wrong? https://wiki.archlinux.org/index.php/Anbox#Necessary_config_options

After building some of the options as modules in Liquorix, I got reports that Anbox stopped working: https://techpatterns.com/forums/viewtopic.php?p=13784.  Liquorix still builds these modules statically, so hopefully that "fixed" Anbox after it "broke" when converted to modules.

The real problem here is Google developed code for Linux that don't work as modules without a magic configuration or compiler (that is unknown to us).  And as static code that's always on, the attack surface of the running kernel increases unnecessarily.  I'm ok leaving these options on in Liquorix since I don't think they'll seriously be used in an attack.  But @heftig maintains `linux-zen`, so it's his call what risks he's willing to tolerate for the features enabled in his build.

**Comment by Joshix-1** [comment]
> Was my information wrong, then? Also, https://aur.archlinux.org/packages/linux-zen-anbox/ existed all this time to _add_ Anbox support because the kernel in [extra] did not work.

comments on the package say that it doesn't add binder and ashmen back. So it isn't an alternative.

**Comment by Saancreed** [comment]
@heftig Anbox was also working for me back when `ashmem` and `binder` were compiled as modules.

@damentz

> `linux-zen` built the android config options without `binderfs`, a requirement for Anbox to work

`binderfs` is not hard a requirement. `binder` is one, but `binderfs` serves as _replacement_ for `binder`. Anbox documentation mentions this [here](https://github.com/anbox/anbox/blob/master/docs/install.md#verify-that-kernel-modules-are-loaded).

> And here's documentation specifying binderfs must be enabled. Maybe it should be removed if it's wrong? https://wiki.archlinux.org/index.php/Anbox#Necessary_config_options

That very section has `CONFIG_ANDROID_BINDERFS=n` as valid example config, and the next section below mentions `binderfs`:

> Not everybody was happy with the binder module in Linux. To address the issues, binderfs was created. One has to choose between the old and the new way when compiling the kernel. With the options below one will use binderfs instead.

On my machine, Anbox was satisfied with `binder` module even if `binderfs` was not available.

> > Was my information wrong, then? Also, https://aur.archlinux.org/packages/linux-zen-anbox/ existed all this time to _add_ Anbox support because the kernel in [extra] did not work.
> 
> comments on the package say that it doesn't add binder and ashmen back. So it isn't an alternative.

@Joshix-1 [It does, just not as modules but compiled into the kernel.](https://aur.archlinux.org/cgit/aur.git/tree/config?h=linux-zen-anbox#n10303)

**Comment by Airwan** [comment]
So if I understand well, there is no problem to revert android config in the kernel options to linux-zen. Personally I switch from ubuntu to arch recently and I was working on 20.04LTS with ashmem and binder without binderfs.

**Comment by heftig** [comment]
I've enabled built-in binder (without any default devices, but binderfs) and ashmem in linux-zen 5.11.zen2-2. Is this sufficient?

**Comment by Saancreed** [comment]
> I've enabled built-in binder (without any default devices, but binderfs) and ashmem in linux-zen 5.11.zen2-2. Is this sufficient?

Yup, seems like it is. Thank you!

```
$ uname -r
5.11.0-zen2-2-zen
$ ls /dev/ashmem
/dev/ashmem
$ mount | grep binder
none on /dev/binderfs type binder (rw,relatime,max=1048576)
$ ls /dev/binderfs
binder1  binder-control
$ anbox check-features
Your computer does meet all requirements to run Anbox
```
