### ISSUE TITLE
AMDGPU failure since 5.10.14-lqx2 and 5.10.15-zen1

### ISSUE THREAD

**Issue by Atemu** [zen-kernel/zen-kernel#200]
Since 5.10.14-lqx2 or 5.10.15-zen1, Xorg crashes with the following error on startup:

https://gist.github.com/Atemu/218e49417eb2d5357a4f29166ef73009

5.10.14-lqx**1** for comparison:

https://gist.github.com/Atemu/a9b1a3fee3f1c5614a5c48e0142da542

GPU is an Sapphire Radeon RX 570 Pulse 8GB.

Reproduce my exact system:

https://github.com/Atemu/nixpkgs/tree/c047ae967a19638761836f84a5da44919ebda298
https://github.com/Atemu/nixos-config/tree/52099de8d8cfc9f3401f50f41e6964cbf3a218a5 (HEPHAISTOS config)

**Comment by Atemu** [comment]
Vanilla 5.10.15 works just fine, so this is must be an issue with the zen patches.

**Comment by heftig** [comment]
```
[   25.103054] [drm:amdgpu_pci_probe [amdgpu]] *ERROR* amdgpu requires firmware installed
```

I think this is actually the expected result of https://github.com/zen-kernel/zen-kernel/commit/789af38db7fe47a34799bb71a0dfde6cb38767b7. You need to make sure the firmware is installed.

**Comment by Atemu** [comment]
That'd be it, there is no `/usr/lib/` on NixOS. We (and other non-FHS distros) would have to patch that patch.

Is it even needed anymore? It's >8Y/>2Y old at this point, I'd assume radeon/amdgpu would handle absent firmware better by now.

**Comment by Atemu** [comment]
With the patch reverted, 5.10.14-lqx2 works as expected again and I assume 5.10.15 would too.

**Comment by Atemu** [comment]
Fixed by commit above, thank you @damentz and @heftig!
