### ISSUE TITLE
5.10.15-zen1 fails to cold boot on Ryzen 7 system.

### ISSUE THREAD

**Issue by texstar** [zen-kernel/zen-kernel#201]
Grub locks up after selecting 5.10.15-zen1 from a cold boot. Pressing the reset button then it works or rebooting from another kernel also works. Not sure what is going on with being able to boot it after turning on the computer.

**Comment by heftig** [comment]
Assuming you're running Arch Linux, is 5.10.15-arch1 affected as well?

**Comment by texstar** [comment]
No. I built it on PCLInuxOS 2021. Also a user with a Ryzen 3 laptop had the same issue. It cold boots OK on my Intel Chromebook converted Square.

**Comment by Atemu** [comment]
5.10.15-zen1 boots on my Ryzen 5 3600 + B550 combo.

(AMDGPU is broken though, see #200)

Does 5.10.14-lqx**2** boot on your machine @texstar? It exhibits the same AMDGPU issue on mine, so it might be the same root cause.

**Comment by texstar** [comment]
Ok, thanks for the feedback Atemu. I simply dropped the zen-source tarball in as a replacement for official kernel sources to build our rpm packages as a test. Apparently there must be a conflict within our patchset and the zen-source tarball. Please disregard this bug report.
