### ISSUE TITLE
Suggestion: include Futex2 patches

### ISSUE THREAD

**Issue by nariox** [zen-kernel/zen-kernel#203]
Seems like Steam is moving to this new futex implementation ([LINK](https://gitlab.collabora.com/tonyk/linux/-/commits/futex2-stable-5.11)). Since the earlier futex patches have been merged into zen, I wonder if you'd be willing to add the futex2 patches as well.

**Comment by rejedai** [comment]
I suppose it would be great to add these patches in 5.11. https://gitlab.collabora.com/tonyk/linux/-/tree/futex2-stable-5.11

**Comment by damentz** [comment]
@nariox @rejedai merged latest stable futex2 into 5.11/master: https://github.com/zen-kernel/zen-kernel/commit/4815108129eceb0a7f5a2166b215b6a8a500d46f

I have a version staged for 5.10 in https://github.com/zen-kernel/zen-kernel/tree/5.10/futex2, however, the syscalls are numbered and had to be re-enumerated to backport.  I see that there's support for using a sysctl to select the syscall number/id, but not sure how it'll work in practice, so it may not work well on 5.10 with proton.

**Comment by nariox** [comment]
I see, I think we can close this one then, I imagine 5.11 will come when the time is right. Unless you want me to keep it open(?).
