### ISSUE TITLE
ixgbe driver support for 5.11

### ISSUE THREAD

**Issue by ben-burns** [zen-kernel/zen-kernel#204]
Hello,

I believe the ixgbe driver may be out of date for 5.11 kernel support ([ixgbe-5.11.3](https://sourceforge.net/projects/e1000/files/ixgbe%20stable/5.11.3/) adds 5.11 support and was released start of the month).  Is there any chance of incorporating the `5.11` compatible ixgbe driver in the near future?

Thanks

**Comment by damentz** [comment]
@heftig I replaced the ixgbe driver with the source from https://sourceforge.net/projects/e1000/files/ixgbe%20stable/5.11.3/, the open branch that's not yet merged here: https://github.com/zen-kernel/zen-kernel/tree/5.11/intel-ethernet-devel

Do you have any objections?  A lot of code changed and most of the boilerplate is for building the kernel module piecemeal.  But otherwise the module does build correctly with the one tweak regarding `common.mk`.

**Comment by heftig** [comment]
Is the existing driver inadequate?

**Comment by heftig** [comment]
Most of the code changes seem to be reformatting, debug statements and replacements for kernel compatibility.

**Comment by damentz** [comment]
> Most of the code changes seem to be reformatting, debug statements and replacements for kernel compatibility.

From skimming through the code, it's a combination of reformatting, old kernel compatibility, and actual functionality changes.  I'm sure there's bug fixes and enhancements that haven't made it to mainline yet.  But yes, those "bug fixes" and "enhancements" appear to probably be less than 5% of the changes we see by importing the "stable" ixgbe driver from Intel's sourceforge distribution.



> Is the existing driver inadequate?

@ben-burns can you comment on what advantage this out-of-tree module has over mainline?

**Comment by ben-burns** [comment]
The primary issues I've been facing on 5.11 are general instability and kernel panics as the interface comes up.  5.10 works just fine, but as soon as I roll 5.11, it becomes interesting.  Ultimately, I can resolve this myself but figured I would check if we would see the "5.11 compatible" ixgbe module released alongside 5.11.

**Comment by damentz** [comment]
@ben-burns have you've tried this out-of-tree module first to see if it helps?

**Comment by ben-burns** [comment]
@damentz The OOT module provided some general interface stability.  However, it did not resolve the kernel panic.  I wrapped up some testing tonight and determined the problem is actually due to a [regression in `skb_seq_state`](https://patchwork.kernel.org/project/netdevbpf/patch/20210301150944.138500-1-willemdebruijn.kernel@gmail.com/) within 5.11 versus 5.10.  A specific iptables rule (similar to the one described in [Bug #211911 ](https://bugzilla.kernel.org/show_bug.cgi?id=211911#c0)) is inducing it.

With that being said, I do not think the OOT module is going to provide much improvement to anyone with the more concerning issue on-hand, which is the kernel panic due to the `skb_seq_state` regression in 5.11.

**Comment by damentz** [comment]
@ben-burns merged the commit that might solve it into 5.11/fixes and master.  Next release from Zen Kernel and Liquorix should resolve the kernel panic you get.

**Comment by ben-burns** [comment]
@damentz Much appreciated!
