### ISSUE TITLE
Does Zen require GCC 11 now?

### ISSUE THREAD

**Issue by JoshyPHP** [zen-kernel/zen-kernel#205]
The current 5.11/master branch contains the following warning against using GCC <11 (7bf0685dd2fe1e2772dfdd16644866b2feaf38a9)

```
WARNING
This patch works with gcc versions 11.0+ and with kernel version 5.8+ and should
NOT be applied when compiling on older versions of gcc due to key name changes
of the march flags introduced with the version 4.9 release of gcc.[1]
```

It also warns against selecting native optimizations on AMD CPUs. Are those warnings accurate? Considering GCC 11 hasn't been released yet and AMD CPUs are quite popular, it may be desirable to either feature this warning more prominently or check for compatibility programmatically.

**Comment by damentz** [comment]
That's a comment left by the author of the commit.  All it's saying is that some available architectures don't exist in older GCC.  If you don't pick those options then it doesn't matter which version of GCC you use.

**Comment by heftig** [comment]
The previous processor family options should work as normal; only the recently added ones require GCC 11.
