### ISSUE TITLE
Newest Zen kernel + Nvidia drivers dont work :/

### ISSUE THREAD

**Issue by LyXAsuna** [zen-kernel/zen-kernel#212]
Zen kernel and nvidia drivers make xorg crash when i do startx (freezes the system) (Arch)
Is there a fix/patch for it? (Downgraded my kernel + drivers for now)

**Comment by Valachord** [comment]
+1, having the exact same issue.

**Comment by damentz** [comment]
@LyXAsuna how are you installing the nvidia drivers?  I'm using the TKG package here and haven't had any issues: https://github.com/Frogging-Family/nvidia-all

Maybe we're missing a patch in Arch that's also in the TKG maintained PKGBUILD?

**Comment by heftig** [comment]
I don't know what's up with our nvidia drivers. I just poke the maintainer to fix them when they fail to build.

**Comment by LyXAsuna** [comment]
> @LyXAsuna how are you installing the nvidia drivers?  I'm using the TKG package here and haven't had any issues: https://github.com/Frogging-Family/nvidia-all
> 
> Maybe we're missing a patch in Arch that's also in the TKG maintained PKGBUILD?
> 
> EDIT: And overall, we already have an open issue regarding freezes with nvidia here: https://github.com/zen-kernel/zen-kernel/issues/210.  May or may not be related.

Using yay to get nvidia-dkms (i use zen kernel)

**Comment by AsessionGuy** [comment]
Hi, today I installed Garuda with zen-kernel and I had a really bad time installing Nvidia proprietary drivers... The installation finished using garuda's settings manager but after some minutes the system froze (Ryzen 5 3600, 32Gb RAM and NVIDIA RTX 2060 SUPER) and didn't passed over "initial ramdisk" during boot. With log-level=7 in grub I could see that it stuck at applying kernel variables.
I spent like 5 hours trying to solve it but lastly I used timdshift to restore a snapshot made before updating the drivers and it boot normally. GCC version is 11.1.0 and I installed linux-zen-headers. I tried installing the drivers with sudo pacman -S nvidia-dkms but didn't work either.
Any solution to make them work?

**Comment by AsessionGuy** [comment]
Also tried with 390xx dkms and dkms performance but none of them worked and got the same problem at boot. @LyXAsuna which version did you downgraded to?

**Comment by LyXAsuna** [comment]
> Also tried with 390xx dkms and dkms performance but none of them worked and got the same problem at boot. @LyXAsuna which version did you downgraded to?

I use nvidia-dkms 460.67
make sure u get everything 460.67 too
like nvidia-utils 460.67
lib32-nvidia-utils 460.67
nvidia-settings doesnt matter as well as:
libxnvctrl, libvdpau

**Comment by heftig** [comment]
Has this changed?

**Comment by damentz** [comment]
I think it's best that we just close this out and wait for a new issue with more information.  Maybe on the next report we'll identify the unique configuration that prevents some users from using the nvidia driver on Zen Kernel, but as it stands today, the current reports and anecdotes seem random and arbitrary to me with no information to go off of.

Closing; if you are still having problems, I recommend submitting a new issue with _a lot_ of information (Xorg logs, Xorg config, kernel logs, initramfs config, etc), so we can better figure out what's really happening here.
