### ISSUE TITLE
5.12 usb-audio branch changes lead to hard lockup of system as soon as usb-audio dac is accessed (audacious, pavucontrol, etc.)

### ISSUE THREAD

**Issue by kernelOfTruth** [zen-kernel/zen-kernel#214]
with https://github.com/zen-kernel/zen-kernel/commits/5.12/alsa merged (testing zen-kernel 5.12.8 or 5.12.9 based) leads to hard lockup of system as soon as attempt to play sound, start pavucontrol or other sound hardware related software

tested hardware was Lusya Fever DAC

**Comment by damentz** [comment]
Yup, that's about right, it never worked on my system either.  That was a test branch to test the lower latency USB audio patches, but it looks like it needs more work or I was missing a dependency for it to work properly.

Either way, I just now deleted it, I never meant to keep it up on github.
