### ISSUE TITLE
outdated info in liquorix.net

### ISSUE THREAD

**Issue by hakavlad** [zen-kernel/zen-kernel#221]
1.
```
Mem dirty before bg writeback..:  10 %  ->  20 %
Mem dirty before sync writeback:  20 %  ->  50 %
```
Seems like it's not true for the latest lqx.
2. zswap enabled. Please indicate this in the description. 
3. mg-LRU enabled. Please indicate this in the description. 
4. le9 exists with clean_low=256M, but not works due to mg-LRU enabled by default.
5. There is no lqx for Debian Stretch (I use stretch, but not found lqx in repo).

**Comment by damentz** [comment]
Thanks, I'll update the site and point out the above.

As for Debian Stretch, that's Debian old stable.  I stopped building for it once builds stopped working.  At this point building a modern kernel on a distribution that old is more risky and less likely to get the results you're looking for.

**Comment by hakavlad** [comment]
>building a modern kernel on a distribution that old is more risky

btw, no problem with xanmod kernel on stretch. And no problem with vanilla 513.

**Comment by damentz** [comment]
Ok, updated website, marking issue as closed.
