### ISSUE TITLE
Enable PSI by default

### ISSUE THREAD

**Issue by hakavlad** [zen-kernel/zen-kernel#222]
Seems like PSI metrics are not provided by the kernel by default:
```
$ cat /proc/pressure/memory
cat: /proc/pressure/memory: No such file or directory
$ uname -a
Linux debian 5.12.0-18.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix
5.12-26.1~bullseye (2021-07-19) x86_64 GNU/Linux
```
https://facebookmicrosites.github.io/psi/

PSI metrics are used by userspace OOM handlers (oomd, systemd-oomd, nohang etc).

Could you enable `CONFIG_PSI=y`, please?

**Comment by damentz** [comment]
PSI is incompatible with MuQSS, so it's disabled in Liquorix.

**Comment by hakavlad** [comment]
>PSI is incompatible with MuQSS, so it's disabled in Liquorix.

I found that Linux kernels without `CONFIG_CGROUP_CPUACCT=y` (linux-ck, for example) provide incorrect PSI metrics, look at the issue: https://github.com/hakavlad/nohang/issues/25#issuecomment-643716504

But there is no problem with kernels with `CONFIG_CGROUP_CPUACCT=y`.

PSI works well out of the box with `CONFIG_SCHED_MUQSS=y`: https://github.com/hakavlad/nohang/issues/25#issuecomment-643723726.

It would be nice to try to build a kernel with PSI support and check the result.

**Comment by hakavlad** [comment]
OK, `CONFIG_SCHED_MUQSS` disables `CONFIG_CGROUP_CPUACCT`.

But what about CFS? Seems like CFS is used by lqx:
```
--- CPU Scheduler (CFS) --------------------------------

Scheduling latency.............:   6    ->   3    ms
Minimal granularity............:   0.75 ->   0.3  ms
Wakeup granularity.............:   1    ->   0.5  ms
CPU migration cost.............:   0.5  ->   0.25 ms
Bandwidth slice size...........:   5    ->   3    ms
```
https://liquorix.net/

**Comment by hakavlad** [comment]
Seems like `CONFIG_SCHED_MUQSS=y` coexists with `CONFIG_CGROUP_CPUACCT=y`:
```
user@debian:~$ _=`uname -r`; cat `find /boot |grep -e "/boot/config-$_"` |grep CPUACC
CONFIG_CGROUP_CPUACCT=y
CONFIG_CGROUP_CPUACCT=y
CONFIG_CGROUP_CPUACCT=y
CONFIG_CGROUP_CPUACCT=y
user@debian:~$ uname -a
Linux debian 5.12.0-18.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.12-26.1~bullseye (2021-07-19) x86_64 GNU/Linux
user@debian:~$ _=`uname -r`; cat `find /boot |grep -e "/boot/config-$_"` |grep MUQ
CONFIG_SCHED_MUQSS=y
```
So, what about to try to enable `CONFIG_PSI`?

**Comment by damentz** [comment]
Ok, per the commit above, PSI is built into the kernel now on the latest Liquorix.  However, it's disabled by default in-case there's some conflict with how MuQSS uses it.

Let me know if it ends up working well for you on (passing `psi=1` into kernel params), and I can make it default on later.

**Comment by hakavlad** [comment]
>Let me know

OK, thank you!

**Comment by hakavlad** [comment]
@damentz 
tested v5.12.19-lqx3. 
PSI is broken:
cpu pressure is constantly 100, 
some memory pressure is constantly 75 even with no workload.
