### ISSUE TITLE
[mgLRU] Early OOM and double kill with 5.12.19-zen2

### ISSUE THREAD

**Issue by hakavlad** [zen-kernel/zen-kernel#225]
The problem exists and is easily reproduced. No problem with mg-LRU disabled.

Previous thread: https://github.com/zen-kernel/zen-kernel/issues/223#issuecomment-885642946

**Comment by yuzhaogoogle** [comment]
So with "tail /dev/zero", you can constantly reproduce the following:

1) the mainline LRU kills one app (no freeze)
2) the MGLRU kills two apps (no freeze)

Is my understanding correct? If so, could you post the logs from both cases please?

Thanks.

**Comment by hakavlad** [comment]
@yuzhaogoogle MemTotal=9.6G, SwapTotal=19.1G. Running firefox, run 
```
python3 -c "with open('/dev/zero', 'rb') as f: f.read()"
```

The result: double kill (`python3`, `firefox-esr`) and early OOM (with a lot of free swap space).

dmesg: https://pastebin.com/1QPE65qg

PSI log: https://pastebin.com/RzsfZBLt

mem log: https://pastebin.com/h2zs6auk (OOM with 8.5G swap used, 11G swap free)

the kernel config: https://pastebin.com/YgaQPQeV

```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:           9782         985        8246         225         550        8329
Swap:         19565         423       19142
```

```
$ cat /proc/swaps
Filename				Type		Size		Used		Priority
/dev/zram0                              partition	20034988	432896		100
```

With mgLRU=0: swap space fills up completely without problems while the GUI is responsive (except short freeze when SwapFree=0), the killer only kills one process after running out of free swap space. 
In this case, the problem I have is reproduced in most attempts. Sometimes it happens (early OOM) even at the beginning of the swap.

**Comment by yuzhaogoogle** [comment]
Well, I need logs from both cases, i.e., mgLRU=1 and 0, so that I can compare them.

**Comment by hakavlad** [comment]
With mgLRU disabled:
- dmesg: https://pastebin.com/ayZFJVUD
- vm sysctl: https://pastebin.com/6PkeAFHu
- mem: https://pastebin.com/5pK4xi1s
- psi: https://pastebin.com/bLk52nE2

**Comment by hakavlad** [comment]
>dmesg: https://pastebin.com/1QPE65qg

Look at this:
```
[ 9087.194214] Free swap  = 11132332kB
[ 9087.194214] Total swap = 20034988kB
```

>with "tail /dev/zero", you can constantly reproduce

Not constantly, but in many cases. But it's more easily to reproduce with `python3 -c "with open('/dev/zero', 'rb') as f: f.read()"`.

**Comment by hakavlad** [comment]
Yet another dmesg with mgLRU=1: https://pastebin.com/J9zgSsWj

**Comment by hakavlad** [comment]
>the mainline LRU kills one app (no freeze)

>the MGLRU kills two apps (no freeze)

Short freeze with both in near-OOM condition.

**Comment by hakavlad** [comment]
Yet another dmesg https://pastebin.com/2MjnAJ4i with killed `tail` and `Web Content`.
```
[ 7039.354701] Free swap  = 4292212kB
...
[ 7039.354871] Out of memory: Killed process 5508 (tail) total-vm:21796260kB, anon-rss:7937344kB, file-rss:256kB, shmem-rss:0kB, UID:1000 pgtables:42700kB oom_score_adj:0
...
[ 7039.356575] Free swap  = 4303392kB
...
[ 7039.356855] Out of memory: Killed process 5286 (Web Content) total-vm:3971104kB, anon-rss:40940kB, file-rss:20092kB, shmem-rss:620532kB, UID:1000 pgtables:3884kB oom_score_adj:0
...
[ 7040.709165] oom_reaper: reaped process 5508 (tail), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by hakavlad** [comment]
mgLRU and stress: freeze, early OOM (Several streams of stress were killed). Video: https://www.youtube.com/watch?v=TlTlb6abJuE
```
$ timeout 180 stress -m 6 --vm-bytes 3G
stress: info: [8195] dispatching hogs: 0 cpu, 0 io, 6 vm, 0 hdd
stress: FAIL: [8195] (415) <-- worker 8201 got signal 9
stress: WARN: [8195] (417) now reaping child worker processes
stress: FAIL: [8195] (421) kill error: No such process
stress: FAIL: [8195] (415) <-- worker 8200 got signal 9
stress: WARN: [8195] (417) now reaping child worker processes
stress: FAIL: [8195] (421) kill error: No such process
stress: FAIL: [8195] (415) <-- worker 8197 got signal 9
stress: WARN: [8195] (417) now reaping child worker processes
stress: FAIL: [8195] (421) kill error: No such process
^C
```

dmesg: http://okturing.com/src/11711/body

mem: http://okturing.com/src/11712/body

psi: http://okturing.com/src/11713/body

**Comment by hakavlad** [comment]
Playing supertux with stress and mainline LRU:
```
$ timeout 180 stress -m 6 --vm-bytes 3G
stress: info: [11660] dispatching hogs: 0 cpu, 0 io, 6 vm, 0 hdd
```
No freeze, no OOM.

psi: http://okturing.com/src/11715/body

mem: http://okturing.com/src/11714/body

**Comment by yuzhaogoogle** [comment]
Yeah, I see the problem. Apparently my last fix wasn't entirely correct. I'll send another sometime next week.

**Comment by hakavlad** [comment]
Fixed, thanks!
