### ISSUE TITLE
Fsync doesn't work from 5.13 and onwards

### ISSUE THREAD

**Issue by fredfredburger** [zen-kernel/zen-kernel#228]
Fsync doesn't work on the latest version of the zen kernel when running Proton  
![](https://i.imgur.com/VIHIZNl.png)  
Downgrade to 5.12.15-zen1 and fsync works again  
![](https://i.imgur.com/DLNsdjQ.png)

**Comment by damentz** [comment]
Interesting, I thought the futex2 issues were resolved with https://github.com/zen-kernel/zen-kernel/issues/217, but instead it looks like the TKG patch set for futex2 just doesn't work at all.

Considering a new patch set was posted by Andre and merges somewhat cleanly with 5.13, I'll swap out the futex2 implementation we're running with that.

**Comment by damentz** [comment]
Well, it also turns out the futex-multiple-wait-v3 branch was never merged to 5.13/master.  That probably wasn't helping.  Next release of Liquorix and/or Zen Kernel should resolve futex2/futex-multiple-wait issues.

**Comment by damentz** [comment]
Ok, I ended up keeping the TKG futex2 patch set but simply merging the futex-multiple-wait-v3 branch.  I tried using the newer futex2 patch from August 5th, but it modified futex.c in a way that merging futex multiple wait was not possible.

**Comment by damentz** [comment]
In latest Liquorix release, running a game through proton in Steam now returns `fsync: up and running.` in the terminal.  Next release of Zen Kernel will also include this fix.  Marking as resolved.
