### ISSUE TITLE
5.13.8 and 5.13.9 compiling error

### ISSUE THREAD

**Issue by shrisha108** [zen-kernel/zen-kernel#235]
No rule to make target '/lib/modules/5.13.8-zen/kernel/arch/x86/crypto/aegis128-aesni.ko', needed by '__modinst'

Been compiling and installing zen kernel on Fedora for a past few years. Just using as base Fedora's config file and just modified by oldconfig and menuconfig commands. Thats first time I've got such error. I'm not really an advance user but it is not difficult task anyway. So error is appeared when I was starting kernel and modules installation. Just week ago when I compiled and installed 5.13.7 everything went smoothly as usual.

**Comment by shrisha108** [comment]
Fixed by CONFIG_SUSPEND=y in config file. Weird, before 5.13.8 that's never make any problems.

**Comment by damentz** [comment]
This is probably an upstream issue, but considering almost no one turns off CONFIG_SUSPEND, I think this is a non-issue.  Closing issue.
