### ISSUE TITLE
only little difference for CFS scheduler settings between linux-zen and arch default

### ISSUE THREAD

**Issue by mabod** [zen-kernel/zen-kernel#238]
With former linux-zen version (kernels before 5.13) I see a significant difference in the CFS scheduler settings between linux-zen and arch default:

I use the following command to check the settings:

`sysctl -A 2>/dev/null | grep "sched" | grep -v "domain" | sort > scheduler-zen-default.txt`

With the older kernel I get the following diff :

```
14# diff scheduler-arch-default.txt scheduler-zen-default.txt
2c2
< kernel.sched_cfs_bandwidth_slice_us = 5000
---
> kernel.sched_cfs_bandwidth_slice_us = 3000
7,11c7,11
< kernel.sched_latency_ns = 24000000
< kernel.sched_migration_cost_ns = 500000
< kernel.sched_min_granularity_ns = 3000000
< kernel.sched_nr_migrate = 32
< kernel.sched_rr_timeslice_ms = 90
---
> kernel.sched_latency_ns = 16000000
> kernel.sched_migration_cost_ns = 250000
> kernel.sched_min_granularity_ns = 1600000
> kernel.sched_nr_migrate = 128
> kernel.sched_rr_timeslice_ms = 100
19c19
< kernel.sched_wakeup_granularity_ns = 4000000
---
> kernel.sched_wakeup_granularity_ns = 2000000

```

This is expected. But with kernel 5.13 I only see two values changed:
```
16# diff scheduler-arch-default-5.13.txt scheduler-zen-default-5.13.txt
2c2
< kernel.sched_cfs_bandwidth_slice_us = 5000
---
> kernel.sched_cfs_bandwidth_slice_us = 3000
7c7
< kernel.sched_rr_timeslice_ms = 90
---
> kernel.sched_rr_timeslice_ms = 100
```

This seems wrong because commit https://github.com/zen-kernel/zen-kernel/commit/1eb5e3fe1b2094e9d50c442ff4d7feb59cfe9f60#diff-02e6057517474f1cfa234bb77eb4f675a81fb1c7136a000ae8b58b63e11a546d
contains a lot more changes.

What am I missing here? I am compiling the `linux-zen` kernel from arch PKGBUILD but with znver2 optimizations:

```
scripts/config --disable CONFIG_GENERIC_CPU
scripts/config --enable  CONFIG_MZEN2
```

Can this have something to do with it?

EDIT:
I just checked the official binary package `linux-zen 5.13.13.zen1-1` and it shows the same short list of parameters.

**Comment by damentz** [comment]
@mabod is CONFIG_ZEN_INTERACTIVE=y in your config?

**Comment by mabod** [comment]
Yes,`CONFIG_ZEN_INTERACTIVE=y` is set.

This seems to be an issue with sysctl and kernel 5.13.  

With kernel 5.10 the command “sysctl -A | grep -v domain” shows 19 variables:

```
kernel.sched_autogroup_enabled = 1
kernel.sched_cfs_bandwidth_slice_us = 5000
kernel.sched_child_runs_first = 0
kernel.sched_deadline_period_max_us = 4194304
kernel.sched_deadline_period_min_us = 100
kernel.sched_energy_aware = 1
kernel.sched_latency_ns = 24000000
kernel.sched_migration_cost_ns = 500000
kernel.sched_min_granularity_ns = 3000000
kernel.sched_nr_migrate = 32
kernel.sched_rr_timeslice_ms = 100
kernel.sched_rt_period_us = 1000000
kernel.sched_rt_runtime_us = 950000
kernel.sched_schedstats = 0
kernel.sched_tunable_scaling = 1
kernel.sched_util_clamp_max = 1024
kernel.sched_util_clamp_min = 1024
kernel.sched_util_clamp_min_rt_default = 1024
kernel.sched_wakeup_granularity_ns = 4000000
```

While with kernel 5.13 the list has only 13 variables:

```
kernel.sched_autogroup_enabled = 1
kernel.sched_cfs_bandwidth_slice_us = 5000
kernel.sched_child_runs_first = 0
kernel.sched_deadline_period_max_us = 4194304
kernel.sched_deadline_period_min_us = 100
kernel.sched_energy_aware = 1
kernel.sched_rr_timeslice_ms = 90
kernel.sched_rt_period_us = 1000000
kernel.sched_rt_runtime_us = 950000
kernel.sched_schedstats = 0
kernel.sched_util_clamp_max = 1024
kernel.sched_util_clamp_min = 1024
kernel.sched_util_clamp_min_rt_default = 1024
```
The list for kernel 5.13 is missing 6 important scheduler variables:

```
kernel.sched_latency_ns = 24000000
kernel.sched_migration_cost_ns = 500000
kernel.sched_min_granularity_ns = 3000000
kernel.sched_nr_migrate = 32
kernel.sched_tunable_scaling = 1
kernel.sched_wakeup_granularity_ns = 4000000
```

That means that with kernel 5.13 I can not check what linux-zen is changing. This is weird.

PS
This is with  `sysctl from procps-ng 3.3.17`
and `linux-lts 5.10.61-1`, `linux 5.13.13.arch1-1` and `linux-zen 5.13.13.zen1-1`

**Comment by mabod** [comment]
Can this have something to do with this commit to kernel source:

https://github.com/torvalds/linux/commit/18765447c3b7867b3f8cccde52dc9d822852e71b#diff-2d3218f0c67a0b82a21c07d1950ecfde0de172bcbad3abcdb59a433574b9b7f3

**Comment by mabod** [comment]
I found the missing variables. They are now in debugfs and can be found here:
`/sys/kernel/debug/sched`

sysctl is no longer seeing them
