### ISSUE TITLE
No wifi 5.14.3-zen1

### ISSUE THREAD

**Issue by Pross** [zen-kernel/zen-kernel#240]
I was using 5.14.1-zen1 that seemed fine, upgraded to 5.14.3-zen1 last night and I have no wifi, also rebooting takes agaes or hangs.

[dmesg.txt](https://github.com/zen-kernel/zen-kernel/files/7153947/dmesg.txt)

[config.txt](https://github.com/zen-kernel/zen-kernel/files/7153949/config.txt)

**Comment by heftig** [comment]
MuQSS is known to be broken.

**Comment by Pross** [comment]
Disabling muqss boots with no issues.

**Comment by heftig** [comment]
Duplicate of #241.
