### ISSUE TITLE
MuQSS Does Not Boot With 5.14

### ISSUE THREAD

**Issue by damentz** [zen-kernel/zen-kernel#241]
The 5.14 branch of MuQSS does not boot properly.  There's no specific errors from MuQSS itself and no stack trackes, but one observation is the behavior of MuQSS booting changes drastically with and without `threadirqs`.  This leads me to believe that IRQs are being mishandled with the current 5.14 port.

We may need to attempt a second port that doesn't include upstream's runqueue locking refactoring, as it may be that it's completely incompatible with how MuQSS handles locks/irqs.  Symptoms of this theory can be found in some code that needed to be macro'd out in these two commits:
https://github.com/zen-kernel/zen-kernel/commit/1b37f0566b443b6e94458fed7c6e6a5b2984d45b
https://github.com/zen-kernel/zen-kernel/commit/3104c885d8a960a39923e5839c546cd472b361be

**Comment by spica234** [comment]
In  my case with ```threadrqs``` grub parameters,

It boot slowly , about almost 15 mins of wait, I can see login screen of ```MintOS```
And at that point, my laptop is ```freezed``` and ```unresponsive```, I have to hard-boot
Unfortunately i cant capture ```journalctl/dmesg```

**Comment by gnusenpai** [comment]
Using my usual MuQSS config from 5.10, booting to tty is timely and seems to work without issues. No errors show up in dmesg (I will double check and edit this when I find time). However, when I try to start X, the system hard-locks and cannot be SSH'd into so a hard reset is necessary.
Something to note: I do not force threaded IRQs on my kernels since it seems to lock up my sound card pretty quickly, regardless of the CPU scheduler.

**Comment by damentz** [comment]
I'm not sure Zen Kernel will adopt MuQSS in the future.  At the moment, the sched/alt framework part of Project-C seems to be the best option for low latency computing when the Periodic Deadline Scheduler is used.  This is what Liquorix has adopted and so far so good.

Not to mention, the Project-C patches play nicely with the rest of mainline and don't make invasive changes that continually interact badly with mainline updates.  So with that all said, we're closing this out and recommending PDS if one desires the behavior and latency targets MuQSS is traditionally good at.
