### ISSUE TITLE
USB keyboard does not work properly

### ISSUE THREAD

**Issue by renaldofreire** [zen-kernel/zen-kernel#243]
USB keyboard C does not work correctly, making it impossible to enter my unlock password into LUKS disk encryption. The same problem does not occur in the LTS version.

OS: Arch Linux x86_64 
CPU: Genuine Intel 0000 (COFFEE LAKE QNCT) (12) @ 3.600GHz

If you need any further information, I am happy to help.

**Comment by heftig** [comment]
This doesn't seem like a ZEN-specific issue.

**Comment by renaldofreire** [comment]
> This doesn't seem like a ZEN-specific issue.

When I change the kernel to the linux-lts version the same error does not occur, so I thought it might be related.

**Comment by renaldofreire** [comment]
The problem was solved. I had to redo the commands:

`# mkinitcpio -P`

and 

`# grub-mkconfig -o /boot/grub/grub.cfg`
