### ISSUE TITLE
Question: CacULE scheduler by default

### ISSUE THREAD

**Issue by RiverOnVenus** [zen-kernel/zen-kernel#244]
Hey, I saw [this commit](https://github.com/archlinux/svntogit-packages/commit/dce1b699554201bd72df4d7d2a7a4a4caeaa4830#) today, will the zen kernel always or for a long time have the CacULE scheduler as default?

```
CONFIG_CACULE_SCHED=y
CONFIG_CACULE_RDB=y
CONFIG_RDB_INTERVAL=19
```
Regards.

**Comment by damentz** [comment]
We modified CacULE so it's not enabled by default:

```
config CACULE_SCHED
        bool "CacULE CPU scheduler"
        default n
        help
          The CacULE CPU scheduler is based on interactivity score mechanism.
          The interactivity score is inspired by the ULE scheduler (FreeBSD
          scheduler).

          If unsure, say N here.
```

So I'm assuming that enabling this scheduler by default is deliberate and probably a good choice.  @heftig can you confirm?

**Comment by RiverOnVenus** [comment]
I started using CacULE about three months ago, I can tell that CacULE works well on my PC.

**Comment by heftig** [comment]
It wasn't unmaintained when we evaluated it.

I will not be using a non-CFS scheduler for `linux-zen` as I require cgroup scheduling.

**Comment by RiverOnVenus** [comment]
It is not unmaintained, ptr1337 is continuing to maintain it.

See [here](https://github.com/CachyOS/cacule-cpu-scheduler).

**Comment by heftig** [comment]
CacULE has some issues, see #245 .
