### ISSUE TITLE
Compilation with BBR/BBRv2 fails

### ISSUE THREAD

**Issue by Rasenkai** [zen-kernel/zen-kernel#247]
```
FAILED unresolved symbol bbr_min_tso_segs
make: *** [Makefile:1173: vmlinux] Error 255
make: *** Deleting file 'vmlinux'
```
This happens if i set either BBR or BBRv2 as default, no other changes in defconfig.
i am using the archlinux [config](https://github.com/archlinux/svntogit-packages/blob/packages/linux-zen/trunk/config)

**Comment by damentz** [comment]
What about the Zen Kernel or Liquorix configuration?  Archlinux stock doesn't account for the extra patches we've added.

**Comment by Rasenkai** [comment]
> What about the Zen Kernel or Liquorix configuration? Archlinux stock doesn't account for the extra patches we've added.

Thank you, Liquorix config compiled and booted fine.
Any particular reason why BBRv2 patches are added if it's unused on archlinux?

**Comment by damentz** [comment]
@heftig any thoughts on the above? :point_up: .

**Comment by heftig** [comment]
They're not unused. linux-zen is built with `CONFIG_TCP_CONG_BBR2=m`.
