### ISSUE TITLE
error in combination with gdm: Couldn't move process to requested cgroup

### ISSUE THREAD

**Issue by mabod** [zen-kernel/zen-kernel#248]
I just realized today that gdm throws an error in the jorunal whenever I boot with linux-zen. I see errors starting with 5.14.4. Before that I did not play around with gdm/gnome.

The error says:

```
Sep 25 12:46:45 rakete systemd[9938]: Started Application launched by gnome-session-binary.
Sep 25 12:46:45 rakete systemd[9938]: app-gnome-wallpaper\x2donce-13237.scope: Couldn't move process 13237 to requested cgroup '/user.slice/user-1000.slice/user@1000.service/app.slice/app-gnome-wallpaper\x2donce-13237.scope': No such process
Sep 25 12:46:45 rakete systemd[9938]: app-gnome-wallpaper\x2donce-13237.scope: Failed to add PIDs to scope's control group: No such process
Sep 25 12:46:45 rakete systemd[9938]: app-gnome-wallpaper\x2donce-13237.scope: Failed with result 'resources'.
Sep 25 12:46:45 rakete systemd[9938]: Failed to start Application launched by gnome-session-binary.
```
This error happens during login. And it does not happen with vanilla arch kernel. I can reproduce the error with every boot in a linux-zen kernel.

**Comment by heftig** [comment]
Looks like a race in gnome-session. I guess with the linux-zen kernel, the scheduling is different enough that gnome-wallpaper exits before gnome-session can do the resource management, thus considers it failed.

gnome-session should probably not exec the application before the resource management is done.

**Comment by mabod** [comment]
And after several more trials I see the error now for the first time also in the vanilla arch kernel.
I am closing this issue. sorry for the noise
