### ISSUE TITLE
Enable CONFIG_NFT_REDIR_IPV4/6

### ISSUE THREAD

**Issue by sigmaSd** [zen-kernel/zen-kernel#249]
Hello,
I would like to be able to use *redirect* in the ruleset with nftables.

According to https://wiki.nftables.org/wiki-nftables/index.php/Building_and_installing_nftables_from_sources#Installing_Linux_kernel_with_nftables_support this requires CONFIG_NFT_REDIR_IPV4 and CONFIG_NFT_REDIR_IPV6 set.

Would be great if they were enabled.

**Comment by heftig** [comment]
These variables do not exist. `CONFIG_NFT_REDIR` is enabled, though.
