### ISSUE TITLE
server reboots every 6-12 hours

### ISSUE THREAD

**Issue by Eridanin** [zen-kernel/zen-kernel#250]
Hello,

I have heavy workload on my server running archlinux with linux-zen for 3 months. After last upgrade to the latest linux-zen the server started rebooting every 6-12 hours. Switching back to linux or linux-hardened stops this issue.
In the logs I see that systemd receives siginit.

BR,
Eridaninn

**Comment by damentz** [comment]
Hi @Eridanin, there's a known issue with BFQ on Zen that was just fixed in the latest release.  Can you verify this is happening on https://github.com/zen-kernel/zen-kernel/releases/tag/v5.14.9-zen2 ?

**Comment by Eridanin** [comment]
Hi, with the patch my server is stable for more than a day and half. So looks like it is solved. Just performance slightly decreased. Thanks.
