### ISSUE TITLE
systemd-oomd works with linux-zen but doesn't work with linux-lqx

### ISSUE THREAD

**Issue by BigmenPixel0** [zen-kernel/zen-kernel#254]
systemd-oomd service log (linux-zen)
```
● systemd-oomd.service - Userspace Out-Of-Memory (OOM) Killer
     Loaded: loaded (/usr/lib/systemd/system/systemd-oomd.service; enabled; vendor preset: disabled)
     Active: active (running) since Sun 2021-10-31 16:14:12 UTC; 3min 54s ago
       Docs: man:systemd-oomd.service(8)
   Main PID: 527 (systemd-oomd)
     Status: "Processing requests..."
      Tasks: 1 (limit: 4377)
     Memory: 1.1M (min: 64.0M low: 64.0M)
        CPU: 348ms
     CGroup: /system.slice/systemd-oomd.service
             └─527 /usr/lib/systemd/systemd-oomd

ArchLinux-PC systemd[1]: Starting Userspace Out-Of-Memory (OOM) Killer...
ArchLinux-PC systemd[1]: Started Userspace Out-Of-Memory (OOM) Killer.
```
systemd-oomd service log (linux-lqx)
```
○ systemd-oomd.service - Userspace Out-Of-Memory (OOM) Killer
     Loaded: loaded (/usr/lib/systemd/system/systemd-oomd.service; enabled; vendor preset: disabled)
     Active: inactive (dead)
  Condition: start condition failed at Sun 2021-10-31 16:18:41 UTC; 38s ago
             └─ ConditionPathExists=/proc/pressure/memory was not met
       Docs: man:systemd-oomd.service(8)

ArchLinux-PC systemd[1]: Condition check resulted in Userspace Out-Of-Memory (OOM) Killer being skipped.
```
ArchLinux with 5.14.15-lqx1-1-lqx and 5.14.14-zen1-1-zen

**Comment by damentz** [comment]
Does it work if you pass `psi=1` into your kernel boot parameters?  Liquorix has it disabled by default since custom process schedulers typically misbehave with it enabled.  However, it may work with PDS (completely untested by me), the scheduler Liquorix switched to after MuQSS was discontinued by Con.

**Comment by BigmenPixel0** [comment]
> Does it work if you pass `psi=1` into your kernel boot parameters? Liquorix has it disabled by default since custom process schedulers typically misbehave with it enabled. However, it may work with PDS (completely untested by me), the scheduler Liquorix switched to after MuQSS was discontinued by Con.

Yes, it work.

**Comment by damentz** [comment]
Ok, great!  Liquorix will keep this option off by default, I recommend force enabling it if you intend to use something like `systemd-oomd`.  Marking as closed.

**Comment by hakavlad** [comment]
@BigmenPixel0 PSI may work incorrect with lqx:

https://github.com/hakavlad/nohang/issues/25#issuecomment-643716504

https://github.com/zen-kernel/zen-kernel/issues/222#issuecomment-886181540

**Comment by damentz** [comment]
@hakavlad Liquorix uses PDS now, which is compatible with PSI (per your testing of BMQ).  However, Liquorix will keep it off by default since it does impact runtime performance, and changes in mainline may make it unreliable or decrease stability without notice.
