### ISSUE TITLE
Issue with certain Realtek wireless LAN devices

### ISSUE THREAD

**Issue by TwilightRavens** [zen-kernel/zen-kernel#255]
Realtek Semiconductor Co., Ltd. RTL8822CE 802.11ac PCIe Wireless Network Adapter to be specific, using Garuda Linux Spotted Eagle ASUS A15 Laptop, Ryzen 5 4600H APU, Nvidia GTX 1650, and 16GB of RAM, wifi does not reconnect and cannot find any networks after resuming from sleep unless I do a full system reboot, repeatable on every sleep/suspend regardless of duration. Does not happen on mainline kernel.

**Comment by damentz** [comment]
Can you provide the output of `inxi -Nxx`?

**Comment by damentz** [comment]
Ok, I did some quick research, I think you have a wireless chip that doesn't play well with linux: https://github.com/rtlwifi-linux/rtk_wifi_driver_rtl8822ce/issues/3

Looks like a lot of people hate this card for its poor performance and bad behavior.  I recommend you replace it immediately with an Intel AX200 type m.2 card.  You can find a ton of them on Amazon, Newegg, and Ebay.

This is one of those, it's sort of expected that your wireless card has issues.  The fact that it misbehaves on Zen/Liquorix but not mainline means that the driver can't tolerate anything besides the most low performance configuration (low tick rate, voluntary preemption or less, etc).

I'm sure this is not the answer you wanted, but the Linux community already went through this with Broadcom.  It's not worth anyone's time to go through the whole troubleshooting cycle on another Linux unfriendly wireless vendor.
