### ISSUE TITLE
MuQSS Leftovers

### ISSUE THREAD

**Issue by travankor** [zen-kernel/zen-kernel#258]
In the ondemand cpu governor (`drivers/cpufreq/cpufreq_ondemand.c`), there still is a reference to `CONFIG_SCHED_MUQSS` which should be removed since it currently does nothing.

Secondly, the `CONFIG_FORCE_IRQ_THREADING` references MuQSS.

**Comment by damentz** [comment]
For cpufreq/ondemand, resolved in https://github.com/zen-kernel/zen-kernel/commit/75f3489d9621042e379e77736f2befa496894e8a and https://github.com/zen-kernel/zen-kernel/commit/776bded2cf3b004f783d7dc52d9d74aeab966cd3

As for forced irq threading, it was already removed in 5.15/zen-sauce, but not 5.14.  Reverted in 5.14/zen-sauce as well as part of https://github.com/zen-kernel/zen-kernel/commit/d25120345bf402cddbd7554029b556ae298b7d81
