### ISSUE TITLE
Application hang 5.15.3.zen1-1

### ISSUE THREAD

**Issue by Cifer9516** [zen-kernel/zen-kernel#261]
Some applications fail to launch, get stuck in a starting process and prevent system from rebooting. Examples are Steam Proton games, MPV player and such
Rolled back to 5.14.16zen1-1 and issue is gone. Vanilla kernel 5.15.3.arch1-1 is working flawlessly as well.

Distro: Arch Linux
DE: Gnome 41
Session: Wayland
RAM: 16 GB
GPU Driver: NVIDIA 495.44
GPU: NVIDIA NVIDIA GeForce RTX 2080 Ti
CPU: Intel Core i9-9900K @ 3.60GHz

**Comment by heftig** [comment]
Threads getting stuck in kernel mode should have traces printed after 120 seconds of being stuck. Did you get any?

**Comment by Cifer9516** [comment]
> Threads getting stuck in kernel mode should have traces printed after 120 seconds of being stuck. Did you get any?

Not sure what do you mean by that or where to look. Should i launch program in console verbosely?

**Comment by heftig** [comment]
No, it would be `dmesg`.

**Comment by damentz** [comment]
@Cifer9516 there were a lot of regressions in 5.15.3, can you try 5.13.4?

**Comment by lavilao** [comment]
Hi, I just updated to linux-zen-5.15.3 and now every time I open svp (after the initial performance benchmark) the entire system hangs, also a few moments ago opening firefox (this just happened once) froze my system, do you guys think is related?

**Comment by damentz** [comment]
Right, I mentioned to upgrade to 5.13.4, not 5.13.3 (which has known regressions).  It may be in testing, and if that's the case you'll need to add testing to pacman temporarily.

**Comment by Cifer9516** [comment]
> @Cifer9516 there were a lot of regressions in 5.15.3, can you try 5.13.4?
5.15.4-zen1-1-zen is working nicely.
