### ISSUE TITLE
complete system hang since 5.15.3

### ISSUE THREAD

**Issue by lavilao** [zen-kernel/zen-kernel#263]
Hi, I am having complete system hangs while opening svp (can happen on other apps too but this is the more consistent) ever since linux-zen-5.15.3, tried on 5.15.4 and it did not hang... at the begining then tried to open firefox and it hanged, and after that it hanged on adobe flash player, I downgraded and today I upgraded to 5.15.5 to test and the behavior is the same that on 5.15.3 (as soon as svp is opened the system freeze) this does not happen with 5.15.2, anyone have a clue what it can be? I am currently running Garuda linux with swaywm

**Comment by lavilao** [comment]
[inxy.txt](https://github.com/zen-kernel/zen-kernel/files/7609671/inxy.txt)
here is my inxy -Fazy

**Comment by heftig** [comment]
Is the non-zen `linux` kernel also affected?

**Comment by lavilao** [comment]
ni idea, I have only zen installed, there were other issues about linux-zen-5.15.3 and hanges but those have been fixed with 5.15.4

**Comment by lavilao** [comment]
Just tested linux-xanmod-tt-5.15.5, it also hangs so I guess its an upstream bug?

**Comment by damentz** [comment]
That sounds about right, how are the current kernels working for you?  We're on 5.15.10, so I'm assuming if what you experienced was widespread, it should be fixed by now.

**Comment by lavilao** [comment]
yeah, its fixed (at least for me)
