### ISSUE TITLE
Patches to merge upstream?

### ISSUE THREAD

**Issue by clin1234** [zen-kernel/zen-kernel#266]
Have previous patches been merged to the upstream linux-next repo, and what is the policy to merge this repo upstream?

**Comment by heftig** [comment]
We consume the patches of others and do not upstream patches ourselves.

**Comment by clin1234** [comment]
Aside from these pull requests on GitHub, what sources do you merge in patches here?

**Comment by damentz** [comment]
Pretty much anything that makes the desktop experience objectively or subjectively, better.
