### ISSUE TITLE
Wake on LAN not working since version 5.15.6-zen1-1-zen.

### ISSUE THREAD

**Issue by aloksrk** [zen-kernel/zen-kernel#268]
Wake on LAN not working since version 5.15.6-zen1-1-zen.
Ethernet controller: Intel Corporation Ethernet Connection I217-LM (rev 04)
	DeviceName:  Onboard LAN
	Subsystem: Dell Device 05a4
	Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0
	Interrupt: pin A routed to IRQ 31
	Region 0: Memory at f7f00000 (32-bit, non-prefetchable) [size=128K]
	Region 1: Memory at f7f3d000 (32-bit, non-prefetchable) [size=4K]
	Region 2: I/O ports at f080 [size=32]
	Capabilities: [c8] Power Management version 2
		Flags: PMEClk- DSI+ D1- D2- AuxCurrent=0mA PME(D0+,D1-,D2-,D3hot+,D3cold+)
		Status: D0 NoSoftRst- PME-Enable- DSel=0 DScale=1 PME-
	Capabilities: [d0] MSI: Enable+ Count=1/1 Maskable- 64bit+
		Address: 00000000fee002f8  Data: 0000
	Capabilities: [e0] PCI Advanced Features
		AFCap: TP+ FLR+
		AFCtrl: FLR-
		AFStatus: TP-
	Kernel driver in use: e1000e
	Kernel modules: e1000e

**Comment by heftig** [comment]
Is the regular `linux` kernel affected as well?

**Comment by mabod** [comment]
wake-on-lan works for me with regular linux-zen 5.15.8 on Arch Linux

**Comment by aloksrk** [comment]
Issue resolved in release 5.15.10, Thanks
