### ISSUE TITLE
[patch] Add unoficial bfs

### ISSUE THREAD

**Issue by StefanescuCristian** [zen-kernel/zen-kernel#27]
I've made a simple patch for adding unofficial BFS on top of commit eec84aa1752bb93c33a8ab664801480a6c587d1a. It's taken from pfactum's pf-kernel, and applied on top of your last 4.1/master commit.

I'm running it now and I don't see any problems. We could use this if you want until something official is released.

http://paste.ubuntu.com/11827851/

**Comment by heftig** [comment]
Merged CK's BFS v0.463.
