### ISSUE TITLE
hid-nintendo driver not included 

### ISSUE THREAD

**Issue by heavysink** [zen-kernel/zen-kernel#273]
Hi,

I found that the Nintendo Switch controller driver (drivers/hid/hid-nintendo.c) which is present in 5.16 is not here in the zen kernel. Do you have plans to migrate it?

Thank you.

**Comment by ZLima12** [comment]
You mean [this](https://github.com/zen-kernel/zen-kernel/blob/324c17fb68f7cd0e17900baee0bce60dd8198fd6/drivers/hid/hid-nintendo.c)?

**Comment by heavysink** [comment]
Oh I found it in 5.16/master... I looked at the wrong branch (5.15). Sorry for that.
