### ISSUE TITLE
Liquorix Project Request: Replace PDS with BMQ

### ISSUE THREAD

**Issue by B3HOID** [zen-kernel/zen-kernel#274]
Considering the goals of the project (offer a kernel with maximum responsiveness) I feel like it makes more sense to use BMQ instead of PDS. I can't comment on other people's experiences, but BMQ did use to have issues with priority thread management when CPU usage is maxed out, leading people to complain about not being able to watch videos or play games under high CPU load from another running process. But this seems to have completely changed now, and at least in my experience, I am getting far better responsiveness with BMQ. 

An notable anecodote of mine is with playing emulators like Project Neko for PC98 games. With a stress-ng test, the game has big lags and is generally unplayable with PDS. Changing nice values and scheduling policies does not work, only making it so stress-ng ran on 1 or 2 CPUs worked. With BMQ the same thing thing happens out of the box, but changing the game's scheduling policy to SCHED_RR immediately relieves the issue and the game is smooth as water instead of mollassses even under the high CPU load. 

Now ofc, this may just be my experience that BMQ happens to work nicely with low core/thread CPUs (I have an i5-6200 Skylake, 2.8 Ghz with 2 cores hyperthreaded to 4 threads) but I have seen other people reporting about similar experiences with PDS even on higher end CPUs. I think it's safe to say it's a good experiment to give BMQ a try for a few releases and if it does not work as intended, switch back to PDS for stability's sake.

**Comment by damentz** [comment]
I wanted to respond to this before I forgot.  As much as I'd like to switch to BMQ if it's better at some things, the author of the two schedulers has deprecated the BMQ scheduling in favor for more work on PDS.  It was more of an experiment but it seems like PDS will be the way going forward.

**Comment by ruby-R53** [comment]
> the author of the two schedulers has deprecated the BMQ scheduling in favor for more work on PDS.

did he? the latest prjc v7.1-r1 patch does still include the BMQ scheduler, and it's from a month ago, unless the code is actually the exact same as when he announced that
