### ISSUE TITLE
futex2 status

### ISSUE THREAD

**Issue by skygrango** [zen-kernel/zen-kernel#278]
Hi

I want to know what is the current state of futex2

I remember that futex2 was merged into the mainline in kernel 5.16

I checked my kernel 5.17.1-zen1-1.1-zen and found that CONFIG_FUTEX2 is not set

I would like to ask why futex2 is not currently enabled ? Will enabling it cause any regression ?

**Comment by sirlucjan** [comment]
As far as I know, what was known as futex2 ended up in kernel 5.16 as a rewrite of futex from scratch.

https://www.kernel.org/doc/html/latest/userspace-api/futex2.html

**Comment by damentz** [comment]
@sirlucjan is correct, FUTEX2 got merged in 5.16 and does not require a new configuration option.  We _do_ merge a compatibility patch that implements a prototype syscall used by older proton releases so those versions of proton continue to support fsync: https://github.com/zen-kernel/zen-kernel/commit/1e2c0d7256ff61665eece820476d0a7531f18d34

We may drop the above in the future as older proton releases are dropped or no longer used by anyone.
