### ISSUE TITLE
What is prjc?

### ISSUE THREAD

**Issue by notquitesane** [zen-kernel/zen-kernel#280]
In trying to decide which branch of 5.17 to use, despite grepping this repository and the web, I could not find what the letters stand for, and as such no way to decide if I need it.

For those who come after me with similar questions:

bbr2: BBR TCP (Bottleneck Bandwidth and RTT) <https://wiki.geant.org/pages/releaseview.action?pageId=121340614>

mglru: The multi-generational LRU <https://lwn.net/Articles/851184/>

rcu: What is RCU? – “Read, Copy, Update” <https://www.kernel.org/doc/html/latest/RCU/whatisRCU.html>

Again, as in title, what do the letters prjc stand for?

Thanks, 

nqs

**Comment by damentz** [comment]
You can look at the commits in the branch to figure out what it is: https://github.com/zen-kernel/zen-kernel/commits/5.17/prjc.  This is one of those cases where the code changed in the branch _is_ the documentation of what it is.

If you're not aware of the upstream repository we pull from, you can find it here: https://gitlab.com/alfredchen/linux-prjc

Project-C is an alternative scheduler project for Linux that combines both BMQ and PDS into the same patch set.  Liquorix is the primary user of this and is configured to use PDS with a 2ms deadline.
