### ISSUE TITLE
Disable workqueues for dm-crypt to improve latency

### ISSUE THREAD

**Issue by igo95862** [zen-kernel/zen-kernel#282]
Remember my old issue about dm-crypt making system unresponsive? #166

Turns out I am not the only one who found that issue: https://blog.cloudflare.com/speeding-up-linux-disk-encryption/

By disabling dm-crypt work queues it is possible to to significantly improve latency and even throughput.

Latency graph: (from cloudflare article)

![latency](https://blog.cloudflare.com/content/images/2020/03/prod.png)

Red: dm-crypt
Blue: dm-crypt but workqueues are disabled
Green: Plain disk

Since linux-zen is latency focused I think the dm-crypt workqueues should be disabled by default.

**Comment by igo95862** [comment]
I tested a little bit using instructions on Arch wiki: https://wiki.archlinux.org/title/Dm-crypt/Specialties

It does seem to fix the issue.

**Comment by damentz** [comment]
Reading over the Cloudflare article and seeing that their change got upstreamed, I think you're right here.  A `ZEN_INTERACTIVE` tuning will make it to 5.17/master shortly.

**Comment by igo95862** [comment]
@damentz it looks like people reporting that the work queues are not fully disabled on linux zen.

https://www.reddit.com/r/archlinux/comments/zkz4a5/if_your_system_is_installed_on_dmcrypt_and/j10s5nk/

https://www.reddit.com/r/archlinux/comments/z5zkq2/the_system_is_hanging_for_a_couple_of_milliseconds/izm6cx1/

**Comment by heftig** [comment]
Ah, yes, I see the problem. The workqueues are not disabled if there are no optional arguments.

**Comment by heftig** [comment]
Should be fixed with 810361c77f4dd8dfb3c95fd998d120075122f171.
