### ISSUE TITLE
missing support mention in .rst

### ISSUE THREAD

**Issue by rogue-agent** [zen-kernel/zen-kernel#283]
Hello world,

Documentation/admin-guide/README.rst is missing Risc-V architecture mention.

reference:
https://risc-v-getting-started-guide.readthedocs.io/en/latest/linux-introduction.html

thank you for Linux, verkko-torilla tavataan.

**Comment by rogue-agent** [comment]
https://github.com/zen-kernel/zen-kernel/tree/5.17/master/Documentation/admin-guide#on-what-hardware-does-it-run

**Comment by damentz** [comment]
I think this is worth submitting a patch for upstream.  Either way, Zen Kernel is only officially tested and supported by on the Linux Zen Arch Linux kernel and Liquorix with x86-64 architecture.  For everything else your mileage may vary.
