### ISSUE TITLE
Include `fa33382c7f74 ("HID: apple: Properly handle function keys on Keychron keyboards")`

### ISSUE THREAD

**Issue by jarkkojs** [zen-kernel/zen-kernel#284]
This patch will be part of v5.19:

```
$ git describe --contains fa33382c7f74a1444f90f324007da1431d7180b2
v5.19-rc1~184^2~4^2
```

It just would make Keychron devices somewhat more useful (right now I do not use mine with my Linux desktops).

**Comment by damentz** [comment]
Merged to 5.18/master as referenced above.
