### ISSUE TITLE
A question/doubt about "X commits behind torvalds:master"

### ISSUE THREAD

**Issue by MuhammedZakir** [zen-kernel/zen-kernel#287]
Hello! Thank you very much for this! This has made my OS *snappy*. Really appreciate this! :-D

I have a doubt and I'm hoping you could solve this: as of posting this issue, for the current master branch, Github shows `This branch is 2092 commits ahead, 15278 commits behind torvalds:master`. I first thought maybe some old commits were not added, and some commits were not added because it was done differently. However, when I checked the diff (by clicking `commits behind`), it shows some commits from April. So I was wondering if there is something missing in ZEN kernel, and if I need to worry about it.

**Comment by damentz** [comment]
The https://github.com/torvalds/linux repository mirrors and sync with Linus's master branch.  This master branch is effectively the next version of Linux in development.  So what you're seeing with us 15k commits behind, 2k commits ahead, is completely right in my estimation.

**Comment by MuhammedZakir** [comment]
Thank you!
