### ISSUE TITLE
MGLRU patches generate a lot of oom_kill on android kernel5.10

### ISSUE THREAD

**Issue by baojunluo** [zen-kernel/zen-kernel#288]
Hi,

Now, we have some problems with MGLRU. Could you give us some help?

After porting MGLRU patches to android kernel5.10.

MGLRU patches: https://android-review.googlesource.com/q/Multi-Gen+LRU,50  
Repo:   kernel/common
branch:  android13-5.10

After running a lot of applications on android12 phone.
The system generate a lot of OOM kill and system performance degrades a lot.
Below dump log:
---------------------------------------------------------------------------------------------------
07-11 20:47:41.300   156   156 W       : kswapd0 invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=0
07-11 20:47:41.300   156   156 I         : CPU: 5 PID: 156 Comm: kswapd0 Tainted: G S      W  O      5.10.81-android12-9-24321119
07-11 20:47:41.300   156   156 I Call trace:  
07-11 20:47:41.300   156   156 I         : dump_backtrace+0x0/0x214
07-11 20:47:41.300   156   156 I         : dump_stack_lvl+0xc0/0x138
07-11 20:47:41.300   156   156 I         : dump_header+0x54/0x1f8
07-11 20:47:41.300   156   156 I         : oom_kill_process+0x120/0x300
07-11 20:47:41.300   156   156 I         : out_of_memory+0x200/0x528
07-11 20:47:41.300   156   156 I         : lru_gen_age_node+0x1d8/0x278
07-11 20:47:41.300   156   156 I         : age_active_anon+0xfc/0x124
07-11 20:47:41.300   156   156 I         : balance_pgdat+0x2f8/0x898
07-11 20:47:41.300   156   156 I         : kswapd+0x130/0x388
07-11 20:47:41.300   156   156 I         : kthread+0x134/0x1c4
07-11 20:47:41.300   156   156 I         : ret_from_fork+0x10/0x30
---------------------------------------------------------------------------------------------------
However, when disable MGLRU function, no OOM generated.

How does MGLRU avoid OOM？
Did we miss any patches?

Thanks

**Comment by heftig** [comment]
We're not the authors of these patches. You want to contact @yuzhaogoogle.

**Comment by yuzhaogoogle** [comment]
Thanks, Jan.

It's bizarre for an Android vendor to open a bug here... Please contact me directly.
