### ISSUE TITLE
Add xone driver to the kernel

### ISSUE THREAD

**Issue by Foleor81** [zen-kernel/zen-kernel#290]
Hi would you like to add the xone driver to your kernel. Xone
is a kernel module for an xbox controller if the standard xboxdrv driver doesn't work.

https://github.com/medusalix/xone

Thanks in advance

**Comment by damentz** [comment]
With the official `linux-zen` package being an Arch package, is there a problem with the AUR DKMS package here? https://aur.archlinux.org/packages/xone-dkms

**Comment by damentz** [comment]
Without official in-tree kernel support, I think we'll skip this.  If you happen to find a supported in tree patch, let us know and we can try merging.  Otherwise, the DKMS package should do fine.
