### ISSUE TITLE
5.19.9.zen1-1 Kernel Causes very weird playback and issues opening apps

### ISSUE THREAD

**Issue by papamikey** [zen-kernel/zen-kernel#291]
I have never come across something like this before but I'll explain what's happening the best I can. Videos take about 5 minutes to load, youtube, twitch, even using MPV. But interacting with somethings like pressing anything on latte dock or opening the app twice will then cause it to open or like in YouTube's case, it will play the video. If I open sonic3 3 air it is frozen until I open it twice, which causes 2 instances to spawn, or I press on the volume widget. Same with opening a video with MPV. I press it once, nothing happens. I press it again and two open at once. If I wait about 3 minutes it will eventually open. 

Restarted multiple times, didn't help. Finally decided to boot with 5.15 and all was well.

**Comment by damentz** [comment]
Official Zen Kernel is on the 6.0 kernel now.  With the latest kernel, are you still having issues?

**Comment by damentz** [comment]
Marking as closed, let us know if you continue to have issues with newer kernel(s).
