### ISSUE TITLE
Filed patch 6.0.2

### ISSUE THREAD

**Issue by ketronix-dev** [zen-kernel/zen-kernel#292]
Log: https://pastebin.com/N9D8MqMs

**Comment by heftig** [comment]
What did you apply this to?

**Comment by ketronix-dev** [comment]
> What did you apply this to?

To the vanilla Linux 6.0.2 kernel

**Comment by damentz** [comment]
Zen Kernel patches apply to the base kernel (6.0 as of today), not to the minor stable updates (6.0.2, as of today).
