### ISSUE TITLE
binder & ashmem modules missing again

### ISSUE THREAD

**Issue by doctorcolossus** [zen-kernel/zen-kernel#293]
It seems like these modules were included from 5.11.zen2-2 to about 5.18.1.zen1-1, but they have been missing for me since then.

For example, now I'm running 6.0.1-zen1-1 now and it doesn't seem to include them.

I had been happily using these modules to run waydroid. But now in order to do so I need to keep my kernel held back to 5.18.1.zen1-1.

Could you please consider including them once again? This was one of the main reasons I had switched to linux-zen.

Thank you.

**Comment by damentz** [comment]
The time range you give sounds about right.  In March of this year, a patch was submitted upstream [1] to remove ashmem, a requirement for anbox.  As of 5.19+ (confirming both Zen and Liquorix), the CONFIG_ASHMEM options no longer exist.

Googling waydroid and ashmem, on the main page they print this:

> **Linux 5.18+**
> Linux 5.18 and later removed ashmem in favor of memfd, right now you need to tell waydroid (1.2.1 and later) to use the new module: 
 ```
/var/lib/waydroid/waydroid_base.prop
---
sys.use_memfd=true
```

Everything else is turned on as normal, such as binderfs:
```
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES=""
```

If waydroid/anbox are not working as expected, I suggest you open an issue with them.

[1] https://lore.kernel.org/all/20220315123457.2354812-1-hch@lst.de/#r

**Comment by doctorcolossus** [comment]
Okay, thank you for that information. 🙂

I hadn't upgraded waydroid in a while, so that probably explains it.
Hopefully newer versions will work with the latest kernel.
