### ISSUE TITLE
Please consider adding CONFIG_USB_ONBOARD_HUB to fix ViewSonic monitors

### ISSUE THREAD

**Issue by bbkr** [zen-kernel/zen-kernel#294]
Hi

In kernel 6.x there is an important [change](https://lwn.net/Articles/856034/) for popular [Realtek Semiconductor RTS5411 hub](https://linux-hardware.org/?id=usb:0bda-5411). This hub is used for example in ViewSonic monitors, which have built-in KVM (keyboard/mouse/video) switch. Currently turning monitor off->on or changing signal to another input and back leaves all connected USB devices in power-off state.

Can you please add CONFIG_USB_ONBOARD_HUB + CONFIG_OF dependencies to your kernel config?

Thanks

**Comment by damentz** [comment]
Enabling **CONFIG_OF** is asking a lot, it brings in about 400 new configuration options that may have nothing to do with operating an x86 desktop, laptop, or server.

Maybe we can patch out the Kconfig for **CONFIG_USB_ONBOARD_HUB** to not depend on **CONFIG_OF**?  Below is the Kconfig:

```
config USB_ONBOARD_HUB
        tristate "Onboard USB hub support"
        depends on OF || COMPILE_TEST
        help
          Say Y here if you want to support discrete onboard USB hubs that
          don't require an additional control bus for initialization, but
          need some non-trivial form of initialization, such as enabling a
          power regulator. An example for such a hub is the Realtek
          RTS5411.

          This driver can be used as a module but its state (module vs
          builtin) must match the state of the USB subsystem. Enabling
          this config will enable the driver and it will automatically
          match the state of the USB subsystem. If this driver is a
          module it will be called onboard_usb_hub.
```

However, out of curiosity, I simply removed the **depends on OF || COMPILE_TEST** section and tried building.  It builds, but that doesn't guarantee it'll work.  Looking at the actual **onboard_usb_hub.c** source file, there are references to **gpio** and **of** includes, but maybe they're unused?

@heftig what do you think?

**Comment by heftig** [comment]
I'm not sure how this is supposed to work since the driver need an OpenFirmware device tree and the only x86 platform using OpenFirmware is the OLPC XO-1, which obviously has nothing to do with ViewSonic monitors.

@bbkr Have you tested this at all?

**Comment by bbkr** [comment]
Thanks for explanation. I'm closing this task because I'm getting weird results after kernel recompilation.

The issue is that ViewSonic monitors have built-in USB hub behind KVM switch. So switching video input also switches all USB devices to another computer. And this hub uses RTS5411 chipset. Once the hub is reconnected to computer by KVM all devices are powered off. This USB_ONBOARD_HUB fix looked like it was addressing exactly this power issue. However I cannot force this fix to work. Module is not claiming this hub, it still uses old `core/hub.c` driver.

I've noticed that doing `sudo lsusb -v` powers on USB devices connected to monitor, so maybe it is not the matter of driver fix but rather some udev hooks missing or some other kind of USB magic.
