### ISSUE TITLE
mute indicator light not working

### ISSUE THREAD

**Issue by Ronemisimus** [zen-kernel/zen-kernel#295]
my mute light isn't working when i mute the audio.
I found someone with a similar issue on manjaro forum:
https://forum.manjaro.org/t/mute-switch-led-not-working-hp-omen-15/103658/17

following the guide i found that the command:
`sudo hda-verb /dev/snd/hwC1D0 0x20 0x500 0x0B && sudo hda-verb /dev/snd/hwC1D0 0x20 0x400 0x7778`
turns on the led

and the command:
`sudo hda-verb /dev/snd/hwC1D0 0x20 0x500 0x0B && sudo hda-verb /dev/snd/hwC1D0 0x20 0x400 0x7774`
turns the led off

i created a report using the command alsa-info.sh in sudo:

one with the led off: http://alsa-project.org/db/?f=d5d0caf81361963916b593e7185b9e839fb39293
one with the led on: http://alsa-project.org/db/?f=a0c9438a19d1101464717c5e2fdc6179993233cc

and a difference is there - in line 463

a fix is also mentioned in the menjaro forum apparently in kernel release: https://www.linuxcompatible.org/story/linux-kernel-518rc6-released/
but my kernel is latest zen version: linux-zen 6.0.11.zen1-1 and yet the led isn't working

i am submitting ti here because i am using linux-zen but this should probably move to upstream right?

thanks in advance to everyone who can help

**Comment by zLuxorZ** [comment]
I am having this issue too with an HP Pavilion Gaming Laptop 16-a0xxx which has the ALC245 codec.

**Comment by damentz** [comment]
Does this issue occur with Manjaro's stock kernel?  This is looking like an upstream issue and Zen Kernel is probably the wrong place to report this.

**Comment by damentz** [comment]
Ok ya, this is a known issue and there's tons of reports in the kernel bugzilla: [Kernel Bugzilla](https://bugzilla.kernel.org/buglist.cgi?quicksearch=hp%20mute%20led).

Marking this as closed since Zen Kernel doesn't work on upstream/mainline bugs unless it's a matter of pulling in an existing patch before it's in stable.
