### ISSUE TITLE
External Displays are detected but wont activate when connected through a hub.

### ISSUE THREAD

**Issue by quantumfate** [zen-kernel/zen-kernel#297]
Kernel: 6.1.3-zen1-1-zen
Host: ZenBook UX425UAZ_UM425UAZ 1.0
Distro: ArcoLinux
CPU: AMD Ryzen 7 5700U with Radeon Graphics (16) @ 1.800GHz
GPU Driver: amdgpu
GPU: AMD ATI 04:00.0 Lucienne

System doesn't boot unless the following kernel parameter is set:
```bash
$ cat /etc/modprobe.d/amdgpu.conf
options amdgpu si_support=1
```

Output of `journalctl -f` when connecting an hdmi cable or display port cable to the dock: 

```bash
Jan 08 03:22:28 arcozen systemd[1]: Starting autorandr execution hook...
Jan 08 03:22:28 arcozen autorandr[10590]: Failed to load profile 'default': Profile not found (line 1502)
Jan 08 03:22:28 arcozen autorandr[10590]: autorandr running as user leonch (started from batch instance)
Jan 08 03:22:28 arcozen autorandr[10588]: Running autorandr as leonch for display :1
Jan 08 03:22:28 arcozen systemd[1]: autorandr.service: Deactivated successfully.
Jan 08 03:22:28 arcozen systemd[1]: Finished autorandr execution hook.
Jan 08 03:22:28 arcozen kernel: [drm] Downstream port present 1, type 2
Jan 08 03:22:29 arcozen kernel: [drm] Send DSC enable to synaptics
Jan 08 03:22:29 arcozen kernel: [drm:dc_link_allocate_mst_payload [amdgpu]] *ERROR* Failure: pbn_per_slot==0 not allowed. Cannot continue, returning DC_UNSUPPORTED_VALUE.
Jan 08 03:22:29 arcozen kernel: [drm] Send DSC enable to synaptics
Jan 08 03:22:29 arcozen kernel: [drm:dc_link_allocate_mst_payload [amdgpu]] *ERROR* Failure: pbn_per_slot==0 not allowed. Cannot continue, returning DC_UNSUPPORTED_VALUE.
```

**Comment by damentz** [comment]
This is a known issue we're monitoring here: https://gitlab.freedesktop.org/drm/amd/-/issues/2171

**Comment by quantumfate** [comment]
It is also worth mentioning that I tested this issue on different kernel versions: linux-zen, xanmod, linux-rt and linux. Only linux and linux-rt pick up all my monitors consistently but sometimes crash on boot. The only kernels that consistently boot with dock plugged are linux-zen and xanmod.

When unplugging and plugging in the monitors the output names will be incremented and it will never reuse older output names. But this is wlroots related as I am using wayland.

**Comment by damentz** [comment]
It appears a "fix" is in as a revert on latest 6.2-rc: https://patchwork.freedesktop.org/patch/518080/

However, it doesn't apply cleanly to 6.1.  I tried reverting the same commit by name and ran into a few merge conflicts.  I'll wait for an official stable backport.

**Comment by damentz** [comment]
@quantumfate how is the latest version of Zen Kernel and/or Liquorix?  We applied the revert backport and merged it to master here: https://github.com/zen-kernel/zen-kernel/commit/e8e82b61bf78129a7f633a19ffe6bf2062264e9e

**Comment by quantumfate** [comment]
Works great! @damentz 

I can boot freely and all monitors turned on throughout extensive testing. Though the "incrementing display output names"-issue upon unplugging and replugging dock persists - but that's drm related

Thanks for merging

**Comment by damentz** [comment]
No problem!  Closing out issue.
