### ISSUE TITLE
Display output names increment when the usb-c hub they are connected through is unplugged and plugged back in.

### ISSUE THREAD

**Issue by quantumfate** [zen-kernel/zen-kernel#298]
Take a look at [Display output names increment when unplugging and plugging in the usb-c dock in which the monitors connected through](https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3560).

Is this related to [Displays behind MST hubs non-functional (regression in kernel 6.1)](https://gitlab.freedesktop.org/drm/amd/-/issues/2171)?

It applies to all kernels that I used (linux-zen, linux, linux-rc, xanmod).

**Comment by quantumfate** [comment]
I opened the issue for the amd driver https://gitlab.freedesktop.org/drm/amd/-/issues/2340

**Comment by damentz** [comment]
Since this is technically an upstream issue, I'll close this out.  When a patch is available or ready for merging, you can open a new issue or a pull request and we'll add it to Zen Kernel.
