### ISSUE TITLE
Cannot boot with retbleed=stuff added as a kernel parameter

### ISSUE THREAD

**Issue by aghpub** [zen-kernel/zen-kernel#300]
I'm running Arch Linux. With the new 6.2.1 kernel call depth tracking can be enabled by adding `retbleed=stuff` as a kernel paramter. If I do this the system is unable to boot and hangs with the following messages:

    [......] FAT-fs (sdb1): IO charset iso8859-1 not found.
    [FAILED] Failed to mount /efi.
    [DEPEND] Dependency failed for Local File Systems.
    
There is a ~80s long pause before the "FAT-fs (sbd1)..." message above. Without adding the parameter the system boots and runs perfectly fine. 

I tested the same on the vanilla 6.2.1 kernel and had no problems there. 

In both cases /proc/config.gz contains `CONFIG_CALL_DEPTH_TRACKING=y`.

Additional info:

CPU: i5-6600 (Skylake)
GPU: GTX 1070 (Nvidia)
Arch package: linux-zen 6.2.1.zen1-1

Steps to reproduce:

Install the Zen kernel. Add `retbleed=stuff` to the kernel parameters. Reboot.

**Comment by aghpub** [comment]
Wow, compiling the kernel literally took hours on my crappy machine. I'm definitely not the right guy· for this job.

Anyway. reverting didn't help. It crashed the machine during boot even harder then with the patch applied.

I'll just do without this retbleed=stuff thing. No problem.

**Comment by aghpub** [comment]
There is a bug visible in journalctl if I boot with `retbleed=stuff`:

    BUG: unable to handle page fault for address: ffffffffc4b7fff6

See: https://pastebin.com/Gy5Xrjqn

(Line: 1002ff)

**Comment by heftig** [comment]
Is it crashing loading the nvidia module?

**Comment by aghpub** [comment]
> Is it crashing loading the nvidia module?

I'm a complete noob when it comes to debugging kernel problems. It seems it's crashing loading a module but I see no hint of Nvidia in that region of the log and the Nvidia module seems to be loaded before (around line 717). But as I said: I have no real clue.when it comes to the kernel.

**Comment by aghpub** [comment]
The problem persists with linux-zen 6.2.2.zen1-1

**Comment by damentz** [comment]
Unless I'm missing something, `retbleed=stuff` is _already_ enabled due to **CONFIG_CALL_DEPTH_TRACKING=y** being enabled in the kernel config.  Adding this parameter will do nothing since it's already set.

@aghpub can you confirm if booting with `retbleed=off` lets you boot properly?  If so, we may need to change the default value and make `retbleed=stuff` a voluntary option that individuals turn on on their systems, rather than a global default.

**Comment by damentz** [comment]
Per reference above, the missing patch was applied and is in the main branch.  Next release of Zen Kernel and Liquorix will include it.

**Comment by An4cl3t0** [comment]
Hi everyone, I still have Kernel Panic booting from Arch with 6.3.5-zen1-1-zen with retbleed=stuff

**Comment by heftig** [comment]
I think that matches what I've seen with the previous Arch kernel. The patch isn't enough to get `retbleed=stuff` working and since it didn't get accepted upstream, I dropped it again.

**Comment by damentz** [comment]
@heftig I'm thinking at this point `retbleed=stuff` is not a supportable option.  I'm ok just closing out this issue, or we can put in a zen-sauce tweak to remove support for it through code.  What do you think?

**Comment by heftig** [comment]
I don't think a patch removing it is worth it. We can just drop the incomplete fix again in the 6.4 cycle.

**Comment by damentz** [comment]
This issue is stale and I believe no longer relevant, closing.
