### ISSUE TITLE
Cannot boot with kernel parameter amdgpu.ppfeaturemask=0xffffffff on ZFS

### ISSUE THREAD

**Issue by hikkidev** [zen-kernel/zen-kernel#302]
It seems related with https://github.com/zen-kernel/zen-kernel/issues/300

OS:             Arch Linux x86_64
Kernel:        6.2.2-zen1-1-zen
CPU:  AMD Ryzen 7 3800X
GPU: AMD Radeon RX 6900 XT 

Command line: `rw initrd=amd-ucode.img zfs=bootfs amdgpu.ppfeaturemask=0xffffffff initrd=\initramfs-linux-zen-fallback.img`

![IMG_20230305_103731_edit_145850012136075](https://user-images.githubusercontent.com/52655010/222941763-3ef3d321-03b6-4878-a57b-ca95e6a4b5a9.jpg)

[rEFInd](https://www.rodsbooks.com/refind/) boot stanza config:
```
menuentry "Arch Linux" {
    icon   /EFI/BOOT/icons/os_arch.png
    volume "rpool"
    loader /vmlinuz-linux-zen
    initrd /initramfs-linux-zen.img
    options "rw initrd=amd-ucode.img zfs=bootfs amdgpu.ppfeaturemask=0xffffffff"
    submenuentry "This is a manual stanza at /boot/efi/EFI/BOOT/stanzas.conf" {
        initrd /initramfs-linux-zen-fallback.img
    }
}
```

**Comment by hikkidev** [comment]
Vanilla kernel 6.2.2-arch1-1 has no issue.

**Comment by damentz** [comment]
This looks like a timeout issue, Zen Kernel runs with a higher tick rate and aggressive CFS values, so anything running in parallel at boot will probably run in a different order.

Unfortunately, I have no experience with ZFS and some brief googling didn't reveal anything simple you can try.  Most people with this issue never solved it or only had something that worked just for them.

@heftig any thoughts?

@hikkidev regarding #300, can you try booting with `retbleed=off`?  Since **CONFIG_CALL_DEPTH_TRACKING=y** is enabled in **linux-zen**, this will confirm whether the new mitigation is the problem.

**Comment by hikkidev** [comment]
I added the parameter and was able to boot into the system.
```
> cat /proc/cmdline
rw initrd=amd-ucode.img zfs=bootfs retbleed=off initrd=\initramfs-linux-zen-fallback.img
```

**Comment by hikkidev** [comment]
@damentz Your words gave me an idea
> This looks like a timeout issue, Zen Kernel runs with a higher tick rate and aggressive CFS values, so anything running in parallel at boot will probably run in a different order.

From wiki:
>In case you are booting a SAS/SCSI based, you might occassionally get boot problems where the pool you are trying to boot from cannot be found. A likely reason for this is that your devices are initialized too late into the process. That means that zfs cannot find any devices at the time when it tries to assemble your pool.

Although I don't use SAS/SCSI, but it is possible to make the scsi driver to wait for devices to come online before continuing by adding to `/etc/modprobe.d/zfs.conf`: 
```
options scsi_mod scan=sync
```
So, after regenerate the initramfs this issue is gone.

**Comment by damentz** [comment]
@hikkidev seems like that might be the solution.  What is approximately the added time by modifying scsi_mod behavior?

**Comment by hikkidev** [comment]
@damentz around 100-300ms, but I didn't even notice. I have fully encrypted disks, so as soon as the zfs module is loaded, PAM confirmation is required.

**Comment by hikkidev** [comment]
I found my previous `systemd-analyze blame`. Total loading time of base units has not changed much: `95ms user@1000.service`  vs `99ms user@1000.service`.

**Comment by damentz** [comment]
Wow!  Ok well I guess we can mark this as resolved.  Hopefully the next person with this issue will find your comments and use it to solve their boot problems too.
