### ISSUE TITLE
Please try adding the xtsproxy module

### ISSUE THREAD

**Issue by patrakov** [zen-kernel/zen-kernel#306]
A few years ago, CloudFlare wrote a [blog post](https://blog.cloudflare.com/speeding-up-linux-disk-encryption/) about speeding up disk encryption. There is still [one patch](https://raw.githubusercontent.com/cloudflare/linux/master/patches/0024-Add-xtsproxy-Crypto-API-module.patch) that is not upstreamed.

If it still applies and works, please include it.

**Comment by damentz** [comment]
I don't believe this is necessary anymore.  The point of xtxproxy was to make available the internal `__xts-aes-aesni` driver that dm-crypt had no access to.  However, on my system:

```
$ grep -A2 'xts(aes)' /proc/crypto
name         : __xts(aes)
driver       : cryptd(__xts-aes-aesni)
module       : cryptd
--
name         : xts(aes)
driver       : xts-aes-aesni <---
module       : aesni_intel
--
name         : __xts(aes)
driver       : __xts-aes-aesni
module       : aesni_intel
```

It appears, at least on my system, that the correct implementation is available for dm-crypt.  Can you confirm?

**Comment by damentz** [comment]
Ok, I missed the part regarding `async: no` and `internal: no` both being required, and that's the main issue.

Per the references above, this module is now in 6.3/main.  Next release of Zen Kernel and Liquorix should include it, given the module is enabled.  CC @heftig, we'll need `CONFIG_CRYPTO_XTS_AES_SYNC=m` added to `linux-zen`.

**Comment by damentz** [comment]
FYI, this module was removed due to multiple reports that this broke cryptsetup in certain configurations.  We don't have plans to re-add unless someone evaluates and does a proper port to new kernels.
