### ISSUE TITLE
Lag occurs when running a memory stress tester

### ISSUE THREAD

**Issue by road2react** [zen-kernel/zen-kernel#308]
Here's a Rust program that continuously writes to memory:

```rs
use std::{hint::black_box, thread};

fn main() {
    thread::scope(|s| {
        for i in 0..16 {
            s.spawn(move || {
                let mut v = vec![0u8; 10_000_000];
                loop {
                    v.fill(i);
                    black_box(&v);
                }
            });
        }
    })
}
```

Keeping this running seems to make the desktop very unresponsive (over 1 second when switching windows). Changing scheduler parameters (nice levels, `SCHED_FIFO`) doesn't seem to fix the problem. This also occurs on all other kernels I have tested (including vanilla, zen, tkg, and cachyos).

This is different from other stress test programs that stress the CPU, since other stress test programs (such as `stress-ng`) or running a CPU-intensive workload (such as compiling a large program) do not cause a major effect like this one does. This memory stress tester relates more with workloads such as Stockfish (with a large Hash size) that use more memory.

If it's relevant, the hardware I'm using is ASUS G513QY (AMD Ryzen 9 5900HX).

**Comment by damentz** [comment]
Is this a behavior you don't get on other kernels or exclusive to Zen Kernel?

**Comment by damentz** [comment]
Closing this out for now, unless there's something different about Zen Kernel that performs worse than stock, nothing we can do here.
