### ISSUE TITLE
Unable to boot with 6.3.2

### ISSUE THREAD

**Issue by amfern** [zen-kernel/zen-kernel#309]
After Upgrading from 6.3.1-zen1 to 6.3.2-zen1 the boost halts on on systemd waiting for missing devices, there is no issue with linux 6.3.1

The missing mount points are located on m.2 ssd, but it doesn't complain about mount points tha are located on SATA ssds.

System:
archlinux
btrfs filesystem
5 Storage devices

**Comment by e-dong** [comment]
Interesting, I have a runit system and I have no issues. But I did have an issue with pulseaudio. It starts up, but my audio devices never loads. The screen is stuck on "Establishing connection to pulseaudio"

**Comment by amfern** [comment]
After doing more testing with different kernels, i have experienced that instability with other versions of the kernel and that lead me to believe this is not a kernel issue.

After doing more trial and error I believe this issue was caused by C-staes because once i limited the C-state to `processor.max_cstate=1` I haven't experienced this issue.

**Comment by damentz** [comment]
Thanks @amfern, I'll close this out as resolved.  Though, if you find a patch that helps with your system so quirks don't need to be applied, let us know and we'll check it out.
