### ISSUE TITLE
CONFIG_CRYPTO_XTS_AES_SYNC makes system unbootable

### ISSUE THREAD

**Issue by tax79** [zen-kernel/zen-kernel#310]
Hello.

Seems after the change done in linux-zen 6.3.4.zen2:
`CONFIG_CRYPTO_XTS_AES_SYNC=m`
my PC is unbootable with the ZEN kernel.
The "linux-zen 6.3.4.zen1" kernel works good.

Screenshot:
![2023-06-02_10-33](https://github.com/zen-kernel/zen-kernel/assets/29124257/3c79eac2-630d-4975-b254-7f61ad1aa607)

And it's not only my problem. Some people encountered it too:
https://bbs.archlinux.org/viewtopic.php?id=286165

Thanks.

**Comment by damentz** [comment]
@tax79 thanks for the report, most likely it was the addition of the xtsproxy module that is breaking cryptsetup or other cryptography implementations in non-obvious ways.   Per the referenced commit above, it's reverted in main and should be fixed in the next release.

**Comment by tax79** [comment]
@damentz The "linux-zen 6.3.5.zen2-1" kernel solved the issue.

Thanks.
