### ISSUE TITLE
Computer Won't Fully Wake from Suspend

### ISSUE THREAD

**Issue by f35f0ef9d0e827dae86552d3899f78fc** [zen-kernel/zen-kernel#313]
Starting a few releases back, perhaps 6.3.5 or so, my Arch system with the zen kernel will not always fully wake from suspend. I will hit a key to wake, and the fans and computer lights turn on, but monitors, keyboard, and mouse do not function. When I run the "stable" linux kernel, I do not experience this behavior.

The only noteworthy kernel parameters I use are `usbhid.quirks=0x1B1C:0x1B17:0x20000000`

What other info is helpful to provide?

**Comment by heftig** [comment]
It would be helpful to verify which release introduced the bug. You can use https://archive.archlinux.org/packages/l/linux-zen/

(and https://archive.archlinux.org/packages/l/linux/ to check corresponding `linux` versions as well).

**Comment by Watkurem** [comment]
Experiencing same here. Nothing in logs, almost like the PC wakes up in braindead state (so, everything is functioning, but there's nobody home).
It does seem to be random-ish (doesn't happen always), but happens often enough that I can't risk trying to suspend.
Last kernel that worked reliably for me is `6.3.6`. Then I upgraded to `6.3.8` and issue started, now on `6.3.9` and it's still there. Never tried `6.3.7`.

This happens both after `systemctl suspend` (suspend to RAM) and on attempt to hibernate (suspend to disk). I hibernate via `uswsusp` and it usually goes like:
1. Blanked screen
2. Screen blinks (probably cycles through a power state, or unloads the kernel with saved state and loads something else to save memory into swap)
3. Save to swap progress is shown
4. Poweroff
With `6.3.8+` kernel on step2 it's the same "braindead state", and step 3 never happens.

**Comment by AvavaAvaOrange** [comment]
I have the same problem as you：(

**Comment by body20002** [comment]
Hibernation also doesn't work I downgraded to `6.1.12-zen1-1-zen`

**Comment by NerosTie** [comment]
With `6.4.8-zen1-1-zen` the issue is still here. Any idea why? What log could be helpful?

**Comment by body20002** [comment]
@NerosTie 
while I was on newer version I didn't notice any errors in `journalctl -b` and also my bluetooth usb stopped working, while it's known to not always work and recently on newer version it stops connecting see [60824](https://bugzilla.kernel.org/show_bug.cgi?id=60824) on bugzilla but I think it's irrelevant to this issue, it might have something to do with other drivers

A hw info could help
I'm also not sure if this issue exists on the official kernel releases so testing that might narrow things down

**Comment by plzfgme** [comment]
I also have the same problem with `6.4.1-zen1` while `journalctl -b` shows nothing (there is no log after `kernel: PM: suspend entry (deep)`)

**Comment by a-aerts** [comment]
I've got the very same issue using zen, for a long time I had the same with core linux kernel too, only LTS one was working correctly, today I've updated my system, kernel 6.5.5-arch1-1 - seems to be working fine, while 6.5.5 zen still isn't able to wake up (or very, very rarely does wake up).

I'm using Garuda linux, I've noticed this issue after switching my GPU from Nvidia to AMD, at first thought it's due to some nvidia leftovers, but it's the same on a fresh installation.

Wasn't able to get anything in logs, other than what others in here mentioned.

To be sure it's not due to some DE etc., I've forced the system to boot in text mode, but the results were the same.

Unfortunately can't remember which version of zen I was using when I first noticed it..

**Comment by body20002** [comment]
It could be AMD related issue I have Ryzen 5 4650G

**Comment by body20002** [comment]
I'll test 6.5.5-arch1-1

**Comment by a-aerts** [comment]
It's been 24hrs and sleep/wakeup still work fine for me on 6.5.5-arch1-1

In my case I've been and am using AMD Ryzen 5 3600 CPU without issues, only when I've switched from Nvidia 1660 super to AMD RX 6800 XT the issue showed up.

In case of Nvidia the sleep didn't work right out of the box either, had to apply this: https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend to make it work. The OS was able to wake up just fine, but the DE was a mess without it.

Also I recall when I was searching for any possible solution that I found someone mentioning that it's can be some issue with bluetooth modules, I THINK that blacklisting them was one of the suggested solutions, but I don't remember where I've seen it.. sorry. I'll link the thread in here if I find it.

**Comment by a-aerts** [comment]
...to my surprise zen now seems to work too... it maybe a fluke, but 5/5 tries worked just fine :grimacing: no idea what's going on, haven't updated anything since the last time, nor touched system configuration..

**Comment by body20002** [comment]
Can Confirm zen 6.5.5 doesn't hibernate/wake up every time, didn't try linux 6.5.5

**Comment by a-aerts** [comment]
Hi, 6.5.9-zen2-1-zen - been few days now, so far it woke up every time without issues

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
> Hi, 6.5.9-zen2-1-zen - been few days now, so far it woke up every time without issues @body20002 @f35f0ef9d0e827dae86552d3899f78fc - how about you?

Since your comment, I also installed 6.5.9-zen2-1-zen and have experienced a couple of sleep cycles now without any problem! Who knows what the problem and fix were, but I will close this for now.
