### ISSUE TITLE
It looks like you’re getting a lot of warnings while using the alabaster theme. These warnings are related to the dc.h file in the ./drivers/gpu/drm/amd/display/dc/ directory. They indicate that some function parameters or members are not described in the dc_clocks and dc_debug_options structures.

### ISSUE THREAD

**Issue by cookieiz** [zen-kernel/zen-kernel#317]
PARSE   include/uapi/linux/dvb/ca.h
  PARSE   include/uapi/linux/dvb/dmx.h
  PARSE   include/uapi/linux/dvb/frontend.h
  PARSE   include/uapi/linux/dvb/net.h
  PARSE   include/uapi/linux/videodev2.h
  PARSE   include/uapi/linux/media.h
  PARSE   include/uapi/linux/cec.h
  PARSE   include/uapi/linux/lirc.h
Using alabaster theme
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'dispclk_khz' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'actual_dispclk_khz' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'dppclk_khz' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'actual_dppclk_khz' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'disp_dpp_voltage_level_khz' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'dcfclk_khz' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'socclk_khz' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'dcfclk_deep_sleep_khz' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'fclk_khz' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'phyclk_khz' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'dramclk_khz' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'p_state_change_support' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'zstate_support' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'dtbclk_en' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'ref_dtbclk_khz' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'fclk_p_state_change_support' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'pwr_state' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'prev_p_state_change_support' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'fclk_prev_p_state_change_support' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'num_ways' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'fw_based_mclk_switching' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'fw_based_mclk_switching_shut_down' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'prev_num_ways' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'dtm_level' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'max_supported_dppclk_khz' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'max_supported_dispclk_khz' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'bw_dppclk_khz' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:547: warning: Function parameter or member 'bw_dispclk_khz' not described in 'dc_clocks'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'native422_support' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_dsc' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'visual_confirm' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'visual_confirm_rect_height' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'sanity_checks' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'max_disp_clk' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'surface_trace' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'timing_trace' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'clock_trace' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'validation_trace' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'bandwidth_calcs_trace' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'max_downscale_src_width' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_stutter' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'use_max_lb' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_dcc' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'force_single_disp_pipe_split' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'voltage_align_fclk' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_min_fclk' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_dfs_bypass' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_dpp_power_gate' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_hubp_power_gate' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_dsc_power_gate' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'dsc_min_slice_height_override' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'dsc_bpp_increment_div' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_pplib_wm_range' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'pplib_wm_report_mode' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'min_disp_clk_khz' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'min_dpp_clk_khz' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'min_dram_clk_khz' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'sr_exit_time_dpm0_ns' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'sr_enter_plus_exit_time_dpm0_ns' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'sr_exit_time_ns' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'sr_enter_plus_exit_time_ns' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'urgent_latency_ns' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'underflow_assert_delay_us' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'percent_of_ideal_drambw' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'dram_clock_change_latency_ns' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'optimized_watermark' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'always_scale' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_pplib_clock_request' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_clock_gate' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_mem_low_power' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'pstate_enabled' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_dmcu' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'force_abm_enable' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_stereo_support' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'vsr_support' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'performance_trace' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'az_endpoint_mute_only' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'always_use_regamma' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'recovery_enabled' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'avoid_vbios_exec_table' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'scl_reset_length10' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'hdmi20_disable' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'skip_detection_link_training' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'edid_read_retry_times' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'force_odm_combine' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'seamless_boot_odm_combine' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'force_odm_combine_4to1' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'minimum_z8_residency_time' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_z9_mpc' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'force_fclk_khz' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'enable_tri_buf' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'dmub_offload_enabled' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'dmcub_emulation' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_idle_power_optimizations' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'mall_size_override' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'mall_additional_timer_percent' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'mall_error_as_fatal' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'dmub_command_table' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'bw_val_profile' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_fec' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_48mhz_pwrdwn' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'force_min_dcfclk_mhz' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'dwb_fi_phase' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_timing_sync' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'cm_in_bypass' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'force_clock_mode' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_dram_clock_change_vactive_support' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'validate_dml_output' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'enable_dmcub_surface_flip' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'usbc_combo_phy_reset_wa' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'enable_dram_clock_change_one_display_vactive' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'legacy_dp2_lt' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'set_mst_en_for_sst' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_uhbr' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'force_dp2_lt_fallback_method' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'ignore_cable_id' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'enable_mem_low_power' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'root_clock_optimization' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'hpo_optimization' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'force_vblank_alignment' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'enable_dmub_aux_for_legacy_ddc' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_fams' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'fec_enable_delay_in100us' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'enable_driver_sequence_debug' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'crb_alloc_policy' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'crb_alloc_policy_min_disp_count' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_z10' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'enable_z9_disable_interface' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'psr_skip_crtc_disable' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'dpia_debug' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_fixed_vs_aux_timeout_wa' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'force_disable_subvp' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'force_subvp_mclk_switch' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'allow_sw_cursor_fallback' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'force_subvp_num_ways' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'force_mall_ss_num_ways' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'alloc_extra_way_for_cursor' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'subvp_extra_lines' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'force_usr_allow' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_dtb_ref_clk_switch' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'fixed_vs_aux_delay_config_wa' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'extended_blank_optimization' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'aux_wake_wa' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'mst_start_top_delay' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'psr_power_use_phy_fsm' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'dml_hostvm_override' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'dml_disallow_alternate_prefetch_modes' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'use_legacy_soc_bb_mechanism' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'exit_idle_opt_for_cursor_updates' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'enable_single_display_2to1_odm_policy' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'enable_double_buffered_dsc_pg_support' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'enable_dp_dig_pixel_rate_div_policy' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'lttpr_mode_override' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'dsc_delay_factor_wa_x1000' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'min_prefetch_in_strobe_ns' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_unbounded_requesting' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'dig_fifo_off_in_blank' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'temp_mst_deallocation_sequence' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'override_dispclk_programming' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_fpo_optimizations' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'support_eDP1_5' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'fpo_vactive_margin_us' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_fpo_vactive' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:882: warning: Function parameter or member 'disable_boot_optimizations' not described in 'dc_debug_options'
./drivers/gpu/drm/amd/display/dc/dc.h:1312: warning: Function parameter or member 'plane_states' not described in 'dc_validation_set'
./drivers/gpu/drm/amd/display/dc/inc/hw/mpc.h:109: warning: Function parameter or member 'overlap_only' not described in 'mpcc_blnd_cfg'
./drivers/gpu/drm/amd/display/dc/inc/hw/mpc.h:109: warning: Function parameter or member 'bottom_gain_mode' not described in 'mpcc_blnd_cfg'
./drivers/gpu/drm/amd/display/dc/inc/hw/mpc.h:109: warning: Function parameter or member 'background_color_bpc' not described in 'mpcc_blnd_cfg'
./drivers/gpu/drm/amd/display/dc/inc/hw/mpc.h:109: warning: Function parameter or member 'top_gain' not described in 'mpcc_blnd_cfg'
./drivers/gpu/drm/amd/display/dc/inc/hw/mpc.h:109: warning: Function parameter or member 'bottom_inside_gain' not described in 'mpcc_blnd_cfg'
./drivers/gpu/drm/amd/display/dc/inc/hw/mpc.h:109: warning: Function parameter or member 'bottom_outside_gain' not described in 'mpcc_blnd_cfg'
./drivers/gpu/drm/amd/amdgpu/amdgpu_device.c:758: warning: Excess function parameter 'pcie_index' description in 'amdgpu_device_indirect_wreg'
./drivers/gpu/drm/amd/amdgpu/amdgpu_device.c:758: warning: Excess function parameter 'pcie_data' description in 'amdgpu_device_indirect_wreg'
./drivers/gpu/drm/amd/amdgpu/amdgpu_device.c:789: warning: Excess function parameter 'pcie_index' description in 'amdgpu_device_indirect_wreg64'
./drivers/gpu/drm/amd/amdgpu/amdgpu_device.c:789: warning: Excess function parameter 'pcie_data' description in 'amdgpu_device_indirect_wreg64'
./drivers/gpu/drm/amd/amdgpu/amdgpu_device.c:758: warning: Excess function parameter 'pcie_index' description in 'amdgpu_device_indirect_wreg'
./drivers/gpu/drm/amd/amdgpu/amdgpu_device.c:758: warning: Excess function parameter 'pcie_data' description in 'amdgpu_device_indirect_wreg'
./drivers/gpu/drm/amd/amdgpu/amdgpu_device.c:789: warning: Excess function parameter 'pcie_index' description in 'amdgpu_device_indirect_wreg64'
./drivers/gpu/drm/amd/amdgpu/amdgpu_device.c:789: warning: Excess function parameter 'pcie_data' description in 'amdgpu_device_indirect_wreg64'
./drivers/gpu/drm/amd/amdgpu/amdgpu_device.c:758: warning: Excess function parameter 'pcie_index' description in 'amdgpu_device_indirect_wreg'
./drivers/gpu/drm/amd/amdgpu/amdgpu_device.c:758: warning: Excess function parameter 'pcie_data' description in 'amdgpu_device_indirect_wreg'
./drivers/gpu/drm/amd/amdgpu/amdgpu_device.c:789: warning: Excess function parameter 'pcie_index' description in 'amdgpu_device_indirect_wreg64'
./drivers/gpu/drm/amd/amdgpu/amdgpu_device.c:789: warning: Excess function parameter 'pcie_data' description in 'amdgpu_device_indirect_wreg64'
./drivers/gpu/drm/amd/amdgpu/amdgpu_device.c:758: warning: Excess function parameter 'pcie_index' description in 'amdgpu_device_indirect_wreg'
./drivers/gpu/drm/amd/amdgpu/amdgpu_device.c:758: warning: Excess function parameter 'pcie_data' description in 'amdgpu_device_indirect_wreg'
./drivers/gpu/drm/amd/amdgpu/amdgpu_device.c:789: warning: Excess function parameter 'pcie_index' description in 'amdgpu_device_indirect_wreg64'
./drivers/gpu/drm/amd/amdgpu/amdgpu_device.c:789: warning: Excess function parameter 'pcie_data' description in 'amdgpu_device_indirect_wreg64'
./include/linux/dcache.h:311: warning: expecting prototype for dget, dget_dlock(). Prototype was for dget_dlock() instead
./include/drm/drm_connector.h:203: warning: Enum value 'DRM_MODE_TV_MODE_MAX' not described in enum 'drm_connector_tv_mode'
./drivers/usb/dwc3/core.h:1344: warning: Function parameter or member 'gfladj_refclk_lpm_sel' not described in 'dwc3'
./include/linux/of.h:111: warning: cannot understand function prototype: 'const struct kobj_type of_node_ktype; '
./drivers/gpu/drm/i915/pxp/intel_pxp_types.h:96: warning: Function parameter or member 'dev_link' not described in 'intel_pxp'
./drivers/gpu/drm/i915/gt/uc/intel_guc.h:274: warning: Function parameter or member 'dbgfs_node' not described in 'intel_guc'
./drivers/gpu/drm/i915/i915_perf.c:5312: warning: Function parameter or member 'i915' not described in 'i915_perf_ioctl_version'

**Comment by damentz** [comment]
Just some unformatted log dump with no context?  Closing.
