### ISSUE TITLE
Arch repo version of linux-firmware broke iwlwifi (8265)

### ISSUE THREAD

**Issue by ilikenwf** [zen-kernel/zen-kernel#318]
I had to downgrade, but I think some breaking change in iwlwifi exists now, arch's default kernel has whatever the needed change (version bump?) is, but zen doesn't yet, just an fyi. 

```
[    5.018216] iwlwifi 0000:02:00.0: Direct firmware load for iwlwifi-8265-27.ucode failed with error -2
[    5.018240] iwlwifi 0000:02:00.0: Direct firmware load for iwlwifi-8265-26.ucode failed with error -2
[    5.018262] iwlwifi 0000:02:00.0: Direct firmware load for iwlwifi-8265-25.ucode failed with error -2
[    5.018283] iwlwifi 0000:02:00.0: Direct firmware load for iwlwifi-8265-24.ucode failed with error -2
[    5.018304] iwlwifi 0000:02:00.0: Direct firmware load for iwlwifi-8265-23.ucode failed with error -2
[    5.018327] iwlwifi 0000:02:00.0: Direct firmware load for iwlwifi-8265-22.ucode failed with error -2
[    5.018329] iwlwifi 0000:02:00.0: no suitable firmware found!
[    5.018348] iwlwifi 0000:02:00.0: minimum version required: iwlwifi-8265-22
[    5.018364] iwlwifi 0000:02:00.0: maximum version supported: iwlwifi-8265-36
[    5.018412] iwlwifi 0000:02:00.0: check git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
```

Downgrading to one revision earlier did fix it though.

**Comment by heftig** [comment]
There's no relevant difference between the arch and zen kernels. Please verify whether this is actually an issue.

**Comment by ilikenwf** [comment]
I mean, my wifi was broken til I booted into the arch kernel and downgraded to the previous release of linux-firmware...then it worked again on a fresh build of zen 6.4 today, so it is definitely an issue.

**Comment by ilikenwf** [comment]
I suppose they could have poorly packaged the firmware though, but if so, why would it work with the arch kernel?

**Comment by heftig** [comment]
Are you building your own zen kernel? Maybe `CONFIG_FW_LOADER_COMPRESS_ZSTD` was missing?

**Comment by ilikenwf** [comment]
I have that set by default - I think that it obviously is/was trying to load it up properly, given the version message, unless it always shows that for all load errors.

**Comment by ilikenwf** [comment]
> Are you building your own zen kernel? Maybe `CONFIG_FW_LOADER_COMPRESS_ZSTD` was missing?

Ahh..that could be. I have zstd defaulted for initrd, but haven't seen or considered this one. I can rebuild with it...hopefully haven't wasted your time here.

**Comment by ilikenwf** [comment]
...that option doesn't appear available in my menucfg, but is not set in .config

**Comment by ilikenwf** [comment]
Found it...maybe I'm just thick headed.

**Comment by ilikenwf** [comment]
That got it, sorry to bother you and thank you for your wonderful work...I used to idle in the IRC channel, and have been riding this train since it was the kamikaze patchset.
