### ISSUE TITLE
Enable proactive compaction back 

### ISSUE THREAD

**Issue by Boria138** [zen-kernel/zen-kernel#325]
On arch wiki there is a warning that disabling proactive compaction causes performance degradation in games that use TCMalloc

```Note that if your game uses TCMalloc (e.g., Dota 2 and CS:GO) then it is not recommended to disable THP as it comes with a large performance cost. Instead if you enable THP, you might also want to enable proactive compaction```

**Comment by damentz** [comment]
For people that need proactive compaction, they can enable at any time through a sysctl.  For the overwhelming number of other desktop and interactive use cases, proactive compaction is a net negative.  We'll not be turning it back on by default.
