### ISSUE TITLE
Kmalloc causing leak in version 6.5.3.

### ISSUE THREAD

**Issue by Mega31** [zen-kernel/zen-kernel#329]
since last week I have been observing memory leak in my system, so after doing a little big of digging I found out that the leak is caused by kmalloc. I ran the following commands to get to this conclusion.

```ps -o pid,user,%mem,command ax | sort -b -k3 -r ```
output: https://pastebin.com/9eMdVNL6
```sudo cat /proc/slabinfo | awk '{print $1, $3*$4}' | sort -rnk2 | awk '{print $1, $2/1000000}' ```
output: https://pastebin.com/ewkVwwLk

Other info:
OS: ArcoLinux x86_64 
Laptop name: Lenovo  Legion 5 Pro 16IAH7H 
CPU: i7-12700H
RAM: 16GB
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q 
GPU: Intel Alder Lake-P 
Kernel:  linux-zen-6.5.3.zen1-1

**Comment by damentz** [comment]
Can you reproduce on a stock 6.5 kernel?

**Comment by damentz** [comment]
I think your issue is related to this: https://lkml.org/lkml/2023/9/16/237.  It's already queued up for 6.5.4, so will be resolved next release.

**Comment by Mega31** [comment]
> Can you reproduce on a stock 6.5 kernel?

Yes I am facing the same problem in stock

**Comment by Mega31** [comment]
I am not sure that it is related to it. as the increase is not tiny as 1.6GB but grows over time and the peak it has ever reached was 8.5/16GB

**Comment by damentz** [comment]
@Mega31 can you reproduce in 6.5.4?

**Comment by Mega31** [comment]
@damentz yes 

```
free -h
               total        used        free      shared  buff/cache   available
Mem:            15Gi       2.2Gi       9.9Gi       512Mi       4.0Gi        13Gi
Swap:             0B          0B          0B
Total:          15Gi       2.2Gi       9.9Gi


```

2.2GB is not used by any program at all.  this is just after 3 hours 35 mins of useage on linux-zen 6.5.4 I will observe for a while


here is the slabtop output after freeing up buffer

https://i.imgur.com/8OFw2Fa.png

**Comment by damentz** [comment]
> > Can you reproduce on a stock 6.5 kernel?
> 
> Yes I am facing the same problem in stock

Hmm, well regardless if 6.5.4 didn't help, this is an upstream issue.  I recommend reporting upstream (https://bugzilla.kernel.org/), or at least through an Arch Linux package bug report: https://bugs.archlinux.org/.  Zen Kernel is downstream to this bug so we can't really do much about it, unless it's a new feature or change that's exclusive to the project.
