### ISSUE TITLE
Latest versions of linux-zen kernel 6.5.x-zen1-1-zen generates very high load on CPU

### ISSUE THREAD

**Issue by D3vil0p3r** [zen-kernel/zen-kernel#331]
I'm using Arch Linux with GNOME 44 in a virtual machine by VMware Workstation.

On different hosts I noted that, when I upgrade Linux Zen Kernel and its headers to the latest versions ` 6.5.x-zen1-1-zen`, the `scsi_eh_1` process takes a very high CPU load. By `top` command I get:
```
PID USER    PR  NI    VIRT RES  SHR S  %CPU  %MEM     TIME+ COMMAND
166 root      20   0       0      0      0   R     93.7     0.0        8:40.79   scsi_eh_1
```
Can you reproduce this issue? I noticed also other users have this problem.

When I downgrade `linux-zen` and `linux-zen-headers` to **6.4.12.zen1-1**, my hosts don't get this issue anymore.

The issue seems to affect the following versions:
```
6.5
6.5.1
6.5.2
6.5.3
```

**Comment by heftig** [comment]
Is the normal `linux` package affected?

**Comment by D3vil0p3r** [comment]
> Is the normal `linux` package affected?

I checked now. It affects also `linux` 6.5.x versions but not `linux-lts`.

**Comment by BurntRanch** [comment]
Couldn't replicate - Linux Zen 6.5.3
Using Intel i7-2600 and running off of a RAID SSD (I have another HDD which, I don't know if it's SCSI or RAID)

**Comment by BurntRanch** [comment]
> > Couldn't replicate - Linux Zen 6.5.3 Using Intel i7-2600 and running off of a RAID SSD (I have another HDD which, I don't know if it's SCSI or RAID)
> 
> Can you share with me your virtual machine configuration? Possibly on VMware Workstation (or Player)

Apologies, Didn't read the message.
But I believe the cores/threads you gave the VM are too little, that or there is something actually wrong with the SCSI driver, Does this issue happen with RAID or other forms of disks?

**Comment by D3vil0p3r** [comment]
> > > Couldn't replicate - Linux Zen 6.5.3 Using Intel i7-2600 and running off of a RAID SSD (I have another HDD which, I don't know if it's SCSI or RAID)
> > 
> > 
> > Can you share with me your virtual machine configuration? Possibly on VMware Workstation (or Player)
> 
> Apologies, Didn't read the message. But I believe the cores/threads you gave the VM are too little, that or there is something actually wrong with the SCSI driver, Does this issue happen with RAID or other forms of disk drivers?

VMware allows me to configure these disk types:
![image](https://github.com/zen-kernel/zen-kernel/assets/83867734/44e71fc5-88ed-4958-949d-5b0623926577)

I tried to configure NVMe and I get the same issue. It started to occur this only in Virtual Machine environments, not in baremetal. And it started after the upgrade to 6.5.x. Before these versions, the kernel worked like a charm with no that spike caused by that process.

**Comment by BurntRanch** [comment]
> VMware allows me to configure these disk types

Have you tried any other VM software? If you still encounter this issue with every VM software and every Disk Type, Then I can't be much of help here, You might want to check any commits between 6.4.x to 6.5.0?

**Comment by D3vil0p3r** [comment]
I found this recent post on Arch: https://bbs.archlinux.org/viewtopic.php?id=288723 and the bug seems to be reported some days ago: https://bugzilla.kernel.org/show_bug.cgi?id=217914

So, at this point we must wait for a fix... it seems affect Linux Vanilla kernel, so I guess when it will be fixed there, also zen will be fixed.

**Comment by damentz** [comment]
The commit [1] that fixes this issue was released in 6.5.6, can ya'll confirm?

[1] scsi: core: ata: Do no try to probe for CDL on old drives

**Comment by D3vil0p3r** [comment]
It seems to be solved.

**Comment by damentz** [comment]
Thanks, closing issue.
