### ISSUE TITLE
Latest releases swapped from .xz to .zst causing possible issues with ebuild-kernel2?

### ISSUE THREAD

**Issue by kzdixon** [zen-kernel/zen-kernel#332]
This isn't super necessary but I've run into an issue where the ebuilds I was bumping versions for in Gentoo won't include the zen patch anymore now that the extension has changed.  
I admittedly don't know everything about ebuilds or the kernel ebuilds specifically but as far as I can tell the patch is downloaded just fine but is just ignored now that the compression method has changed from `.xz` to `.zst`.  
If I can figure out how to get the ebuild process to include the patch again its not really an issue but so far I have been unsuccessful in doing so.  

Current ebuild is as follows:
```ebuild
# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI="8"
ETYPE="sources"
K_WANT_GENPATCHES="base extras"
K_GENPATCHES_VER="7"
K_SECURITY_UNSUPPORTED="1"
K_NOSETEXTRAVERSION="1"

inherit kernel-2
detect_version
detect_arch

KEYWORDS="~amd64 ~arm64 ~x86"
HOMEPAGE="https://github.com/zen-kernel"
IUSE=""

DESCRIPTION="The Zen Kernel Live Sources"

ZEN_URI="https://github.com/zen-kernel/zen-kernel/releases/download/v${PV%_*}-zen${PV#*p}/linux-v${PV%_*}-zen${PV#*p}.patch.zst"
SRC_URI="${KERNEL_URI} ${GENPATCHES_URI} ${ARCH_URI} ${ZEN_URI}"

UNIPATCH_LIST="${DISTDIR}/linux-v${PV%_*}-zen${PV#*p}.patch.zst"
UNIPATCH_STRICTORDER="yes"

K_EXTRAEINFO="For more info on zen-sources, and for how to report problems, see: \
${HOMEPAGE}, also go to #zen-sources on oftc"

pkg_setup() {
        ewarn
        ewarn "${PN} is *not* supported by the Gentoo Kernel Project in any way."
        ewarn "If you need support, please contact the zen developers directly."
        ewarn "Do *not* open bugs in Gentoo's bugzilla unless you have issues with"
        ewarn "the ebuilds. Thank you."
        ewarn
        kernel-2_pkg_setup
}

pkg_postrm() {
        kernel-2_pkg_postrm
}
```
Most of the contents were copied from the ebuild maintained in the `gentoo` repository.

**Comment by heftig** [comment]
Sorry, I don't know Gentoo ebuilds at all.

**Comment by damentz** [comment]
It says in the `pkg_setup()` function to open a bug in Gentoo's bugzilla for problems with the ebuild:

```shell
pkg_setup() {
        ewarn
        ewarn "${PN} is *not* supported by the Gentoo Kernel Project in any way."
        ewarn "If you need support, please contact the zen developers directly."
        ewarn "Do *not* open bugs in Gentoo's bugzilla unless you have issues with"
        ewarn "the ebuilds. Thank you."
        ewarn
        kernel-2_pkg_setup
}
```

Also, Arch has been moving to Zstandard compressed artifacts for quite some time.  I would expect more ebuilds that depend on Arch packages to begin failing as this transition continues.

Closing out, this is a Gentoo package bug (and I'm also not familiar with ebuilds).

**Comment by Fuchskaute** [comment]
Hello, I have created a PR to version bump zen-sources on the main tree and fix the SRC_URI

https://github.com/gentoo/gentoo/pull/33056

If you wish to maintain the kernel in your own overlay, like I do, all that is needed is to adjust the ZEN_URI variable and others to incorporate the changes in the naming scheme and file extension.

`ZEN_URI="https://github.com/zen-kernel/zen-kernel/releases/download/v${PV}-zen1/linux-v${PV}-zen1.patch.zst"`

That is how I handle it on my personal overlay 

https://github.com/Fuchskaute/miapersonal/blob/main/sys-kernel/zen-sources/zen-sources-6.5.5.ebuild

**Comment by kzdixon** [comment]
> Hello, I have created a PR to version bump zen-sources on the main tree and fix the SRC_URI
> 
> [gentoo/gentoo#33056](https://github.com/gentoo/gentoo/pull/33056)
> 
> If you wish to maintain the kernel in your own overlay, like I do, all that is needed is to adjust the ZEN_URI variable and others to incorporate the changes in the naming scheme and file extension.
> 
> `ZEN_URI="https://github.com/zen-kernel/zen-kernel/releases/download/v${PV}-zen1/linux-v${PV}-zen1.patch.zst"`
> 
> That is how I handle it on my personal overlay
> 
> https://github.com/Fuchskaute/miapersonal/blob/main/sys-kernel/zen-sources/zen-sources-6.5.5.ebuild

Is it actually applying the zen patch for you? On my end it gets excluded every time.
I assume `UNIPATCH_LIST="${DISTDIR}/v${PV}-zen1.patch.zst"` is also not actually going to have it find the new download with the `linux-` prefix as I had to change both.
ie: 
```
...
 * Excluding Patch #/var/tmp/portage/sys-kernel/zen-sources-6.5.5_p1/distdir/linux-v6.5.5-zen1.patch.zst ...                      [ ok ]
...
```
When checking the src files in `/usr/src`, the Makefile and such do not have the appropriate changes merged in.
