### ISSUE TITLE
typos in zen 6.6

### ISSUE THREAD

**Issue by yshui** [zen-kernel/zen-kernel#335]
https://github.com/zen-kernel/zen-kernel/blob/5031eef5b359f363e8d0d35e4458fcb6af076138/kernel/sched/sched.h#L2523

should be `#if defined...`

https://github.com/zen-kernel/zen-kernel/blob/5031eef5b359f363e8d0d35e4458fcb6af076138/kernel/sched/alt_core.c#L4302-L4321

missing closing brace here.

**Comment by heftig** [comment]
Applied fixups. Thanks!
