### ISSUE TITLE
Failed `make`

### ISSUE THREAD

**Issue by djtech-dev** [zen-kernel/zen-kernel#336]
So, I tried building the last commit on the main branch of this kernel, but I got this error while running `make -j 4`:
```
  MODPOST Module.symvers
ERROR: modpost: "sof_ipc3_do_rx_work" [sound/soc/sof/snd-sof.ko] undefined!
make[2]: *** [scripts/Makefile.modpost:145: Module.symvers] Errore 1
make[1]: *** [/home/XXXXXX/zen-kernel/Makefile:1863: modpost] Errore 2
make: *** [Makefile:234: __sub-make] Errore 2
```
I get the same output with just `make`.

Online I only found a patch that fixed this exact problem (https://patches.linaro.org/project/alsa-devel/patch/20231006084041.18100-1-peter.ujfalusi@linux.intel.com/).

Any suggetions?

**Comment by damentz** [comment]
Have you tried the patch to verify you can build with it?  Otherwise, we need a configuration that can reproduce the build failure to test the patch with.

**Comment by djtech-dev** [comment]
So, I edited the patch a little bit in order to make it work, so:
- line 308 of `/sound/soc/sof/sof-client.c` turned from `if (cdev->sdev->pdata->ipc_type == SOF_IPC) {` to `if (IS_ENABLED(CONFIG_SND_SOC_SOF_IPC3) && (cdev->sdev->pdata->ipc_type == SOF_IPC)) {`

This is not identical to the patch I've found online, but it make the kernel compile, while that patch doesn't, even if applied manually (the line wasn't the same between the Zen's commit I was working on and that patch's original commit).

If you want I can make a PR to this repo.
