### ISSUE TITLE
issue with gpu and freezing

### ISSUE THREAD

**Issue by x7f15h7x** [zen-kernel/zen-kernel#338]
I am sadly stuck with a gtx1650, noticed after updating to 6.7 I would get constant 30 second freezes. Rolled the kernel back to 6.6.10 and fixed the issue.

**Comment by damentz** [comment]
I believe that is fixed with https://github.com/zen-kernel/zen-kernel/commit/c29198cfeb3f5fa34b8e69001dfa98d66d8db001 in 6.7/fixes (now in 6.7/main).

**Comment by damentz** [comment]
Marking as resolved.
