### ISSUE TITLE
No sound on 6.7.* kernel, but there is on 6.6.*

### ISSUE THREAD

**Issue by kersh1337228** [zen-kernel/zen-kernel#341]
## Config:
- ASUS ROG Strix SCAR G732LWS (I7 10875H, RTX 2070 SUPER);
- Audio hardware: Intel Comet Point PCH -cAVS (ALC294 using aplay -l; Realtek driver used on Windows 11);
- System: Artix Linux dinit (Also tested on Arch Linux) with 6.7.4.zen1-1 kernel;
- Audio software:  pipewire, pipewire-pulse, wireplumber;

## Issue description:
There is no sound on system with 6.7.* kernel (tested on linux-zen, linux, linux-g14 kernels), however there is sound on linux-lts 6.6.16-1, but only with `options snd-hda-intel model=asus-zenbook` inside of `/etc/modprobe.d/alsa-base.conf`, and on windows11. No sound here means there is no way to produce any sound using laptop's built in speakers e.g. using alsa-utils speaker-test, using gnome sound controls, using pavucontrol. Although it is clear that audio devices are detected, according to dmesg and alsa-utils, no real sound can be produced. Many different fixes were tried including altering /etc/asound.conf and /etc/modprobe.d/alsa-base.conf, using another sound system (pulseaudio, alsa only), installing sof-firmware and alsa-firmware. The only working solutions are either using 6.6.* linux kernel with the option mentioned above or using windows. I found just the same issue on [Arch forum](https://bbs.archlinux.org/viewtopic.php?id=292393) but there are no answers there for 2 weeks already. It seems to be original linux kernel issue, however I've been using zen kernel for a long time already and I assume you can help fixing this. I suspect [this commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=713f040cd22285fcc506f40a0d259566e6758c3c).

**Comment by kersh1337228** [comment]
**blacklist snd_hda_codec_realtek** solves the issue and _snd_hda_codec_generic_ is now used instead of one. I assume it is a general kernel problem.

**Comment by amayra** [comment]
thanks you for posting back the workaround

**Comment by damentz** [comment]
Is this still an issue with the latest 6.7 or 6.8 kernels?  Also, have you reported this upstream?

**Comment by kersh1337228** [comment]
I have just checked it once again on `6.8.1-zen1-1-zen` and can confirm that problem is still there.

I haven't reported upstream if you mean default linux kernel because they don't have issues thread on their github and the only way to report official linux kernel issue according to documentation is to write them an email or create a problem on bugzilla which is pretty inconvenient because I want to be sure that my message reaches the actual developers.

Again the point here is -- with **realtec** codecs used alsa can definitely see my ALC294 sound card but no sound could be produced in any way, with **generic** codecs used alsa can also see my sound card but now sound can be produced by any means.

**Comment by damentz** [comment]
> I haven't reported upstream if you mean default linux kernel because they don't have issues thread on their github

We're not a forum and issue tracker for upstream Linux.  I recommend you follow the upstream guides to report at this point 

Closing as this isn't Zen Kernel specific.
