### ISSUE TITLE
FYI: backport of Focusrite Scarlett Gen4 support

### ISSUE THREAD

**Issue by imaami** [zen-kernel/zen-kernel#342]
If you have use for v6.6.18 and v6.7.6 backports of the upcoming (v6.8) support for Focusrite Scarlett Gen4 devices:

https://github.com/imaami/linux/tree/linux-6.6.18-scarlett_gen4
https://github.com/imaami/linux/tree/linux-6.7.6-scarlett_gen4

These are the complete set of commits currently in v6.8-rc6. I've tested the v6.6.18 backport already and can confirm it works. The content of v6.7.6 is identical, so I don't expect it to behave any differently. There were no conflicts at all cherry-picking either branch.

**Comment by imaami** [comment]
Another public service announcement: I added the latest Scarlett Gen4 fixes from upstream, and rebased the v6.6 and v6.7 branches onto v6.6.22 and v6.7.10 respectively. So, to anyone who has one of these devices and hasn't upgraded to a v6.8 kernel yet, here you go:

[https://github.com/imaami/linux/tree/linux-6.6.22-scarlett_gen4](https://github.com/imaami/linux/tree/linux-6.6.22-scarlett_gen4)
[https://github.com/imaami/linux/tree/linux-6.7.10-scarlett_gen4](https://github.com/imaami/linux/tree/linux-6.7.10-scarlett_gen4)

**Comment by imaami** [comment]
Some additional detail: looking at the content of [stable-rc/queue/6.8](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=queue/6.8) right now (at about 2024-03-24T18:20:00+00:00), the scarlett mixer source files in v6.8.2 will be byte-for-byte identical with my current backport branches. In other words, these `git diff` commands show no difference:

```bash
git diff imaami/linux-6.6.22-scarlett_gen4 stable-rc/queue/6.8 -- 'sound/usb/*scarlett*'
git diff imaami/linux-6.7.10-scarlett_gen4 stable-rc/queue/6.8 -- 'sound/usb/*scarlett*'
```

Exact branch heads:
[linux-6.6.22-scarlett_gen4: 70cee642f7308717e8f3a421702c1c37a4fa5552](https://github.com/imaami/linux/commit/70cee642f7308717e8f3a421702c1c37a4fa5552)
[linux-6.7.10-scarlett_gen4: 52d550d20ee44c24ba2113d72d621129fe94a043](https://github.com/imaami/linux/commit/52d550d20ee44c24ba2113d72d621129fe94a043)

**Comment by damentz** [comment]
Is it possible for you to rebase your changes off of the core release tags, v6.7 and v6.8 respectively?  Otherwise, this looks good.  Enabling support for hardware that is otherwise completely missing for professionals is always welcome.

**Comment by damentz** [comment]
@imaami are you still interested in getting this into Zen Kernel?

**Comment by damentz** [comment]
@imaami closing issue out, but let me know if you have patches ready to go for v6.10 and we'll add them.
