### ISSUE TITLE
Proposal: Incorporate Patches to Revert AMDGPU Lower Power Limits Enforcement from Linux 6.7

### ISSUE THREAD

**Issue by ashirviskas** [zen-kernel/zen-kernel#344]
### Summary

The Linux 6.7 kernel [introduced a change](https://www.phoronix.com/news/AMDGPU-Lower-Power-Limit) to the AMDGPU driver, enforcing a lower power limit set by the graphics card BIOS, preventing users from setting power limits below this threshold. This change impacts users' ability to manage power consumption and efficiency according to their needs. I propose to incorporate patches into the linux-zen kernel that revert these changes, thus restoring the flexibility previously available to AMDGPU users.

### Context

Historically, the AMDGPU Linux driver allowed users unrestricted control over their graphics card's power limit. This flexibility was crucial for users aiming to optimize their systems for power efficiency, potentially reducing energy consumption and heat output without adversely affecting performance for their use cases.

However, the enforcement of a BIOS-defined lower power limit restricts users' ability to lower the power consumption beyond what is deemed safe by the hardware manufacturers. While the intention behind this change is to prevent potential hardware damage, it also removes a layer of control that was highly valued by the community.

### Discussion Points

1. **User Impact**: Users have expressed dissatisfaction [[1](https://gitlab.freedesktop.org/drm/amd/-/issues/2992#note_2310925), [2](https://bbs.archlinux.org/viewtopic.php?id=293694), [3](https://www.gamingonlinux.com/2024/03/amdgpu-driver-for-linux-67-enforces-lower-power-limits-from-vbios/)] with this change, noting the significant impact on power consumption and the inability to optimize their systems as they had previously. For example, scenarios where a reduced power limit would suffice for less demanding tasks, now incur unnecessary power usage and associated costs.

2. **Hardware Safety Concerns**: The argument presented for the change revolves around protecting the hardware from potential damage due to operating outside the "safe" power limits. However, evidence and user experience suggest that modern GPUs are capable of operating safely at lower power levels without risk of damage. Moreover, features like undervolting, which carry a greater risk of instability, remain accessible, questioning the consistency of safety concerns.

3. **Proposed Solution**: Incorporating [patches](https://patchwork.freedesktop.org/patch/579685/) to revert the enforced power limit changes would restore user control over power management, aligning with the linux-zen kernel's philosophy of providing a user-optimized experience. Furthermore, offering this as an optional feature, potentially guarded by a warning or disclaimer, could mitigate concerns regarding unintended hardware damage.

### Conclusion

The enforced lower power limit introduced in Linux 6.7 represents a departure from the flexibility previously afforded to AMDGPU users, impacting their ability to tailor system performance to their needs. By incorporating patches to revert this change, the linux-zen project can uphold its commitment to user choice and optimization, respecting the community's feedback while acknowledging the nuanced balance between hardware safety and user autonomy.

**Comment by heftig** [comment]
Exceeding the firmware-defined power limits sounds dangerous; I'm not sure this is a good idea.

**Comment by ashirviskas** [comment]
I'm talking not about exceeding, but about lowering them. 

I've been successfully running my RX 7900  XTX at a 200W limit and 90%+ performance, but with these "bugfixes" now it can only go down to 294W.

**Comment by damentz** [comment]
> Hardware Safety Concerns: The argument presented for the change revolves around protecting the hardware from potential damage due to operating outside the "safe" power limits. However, evidence and user experience suggest that modern GPUs are capable of operating safely at lower power levels without risk of damage. Moreover, features like undervolting, which carry a greater risk of instability, remain accessible, questioning the consistency of safety concerns.

I think that AMD only put this change in to make sure the GPU runs to spec as compared to their Windows driver.  They also haven't "tested" running below spec, so it's easier to blanket the problem with a statement that running out of spec can damage the hardware, therefore it's unsupported.

However, at no point in history that I can think of has running with reduced voltage or amperage ever damaged PC hardware.  If someone can cite an example, that would be helpful.  But the only thing a user has to worry about is instability, for which a power cycle "fixes" the issue.

@heftig there's no risk restoring applying the patch suggested.  It guards reducing the power limit to 0 with enabling overdrive, or overclocking capabilities.  Not to mention, it's already been acked by Alex Deucher.

I'll put it in fixes since it looks like it'll eventually go upstream.

**Comment by damentz** [comment]
@ashirviskas this change is now in 6.7/main and 6.8/main.  To enable a lower limit of 0, pass `ignore_min_pcap` in your kernel boot parameters.

**Comment by HugKitten** [comment]
I wonder if this is why I've been having issues with games crashing (Helldivers mostly) lately.

**Comment by amayra** [comment]
Fully agree. Restoring flexibility for AMDGPU users is crucial for optimizing power management. Let's work together to address this in the linux-zen kernel

Users should have the responsibility to manage their system's power consumption according to their needs, even if it entails some level of risk. Let's prioritize user empowerment

**Comment by amayra** [comment]
Fully agree. Restoring flexibility for AMDGPU users is crucial for optimizing power management. 

even if it's dangerous users should have the responsibility to manage their system's power consumption according to their needs, even if it entails some level of risk. Let's prioritize user empowerment
