### ISSUE TITLE
Zen kernel causes gnome-terminal (and its variations) to crash Gnome-Shell

### ISSUE THREAD

**Issue by Nikki1993** [zen-kernel/zen-kernel#35]
Just as title suggests, linux-zen causes terminals to crash Gnome Shell upon launch (tty is unaafected since it's not using Xorg ("duuuh" xD)).

Here is the screenshot of the xorg core dump. Let me know if you need anything else more specific. 
http://i.imgur.com/Ay5shnY.png

**Comment by heftig** [comment]
That's a screenshot of a crash in Xorg, not a terminal application.

**Comment by Nikki1993** [comment]
My bad, Bad phrasing, I mean to describe that it crashes Gnome Shell with Xorg core dump as the result. When launching terminal application.

**Comment by heftig** [comment]
That seems unlikely. Which kernels did you compare, and did you double-check?

**Comment by Nikki1993** [comment]
Mainline Arch and Zen. opening gnome-terminal through shortcut (in my case Win + T) caused Gnome Shell to throw up the "Oops, something went wrong" and I need to logout and restart the shell.

**Comment by Nikki1993** [comment]
doesnt happen wth mainline kernel. i am on arch btw.

**Comment by heftig** [comment]
Does it happen if you add kdbus=0 to the boot parameters?

**Comment by Nikki1993** [comment]
nope. doesn't crash anymore.

**Comment by heftig** [comment]
Can you get a backtrace of the crash from `coredumpctl`?

**Comment by heftig** [comment]
OTOH, the Xorg crash seems like a red herring; it's probably another bug since you do get the Oops window, which you could not see if Xorg crashes. Check earlier in the logs.

**Comment by Nikki1993** [comment]
I am in bus I will check back in an hour and search through. Would be nice if you could throw me a couple of pointers where to look and what to get. Still learning through the arch wiki.

**Comment by heftig** [comment]
If you don't know what to look for, just pastebin all the logs from that boot.

**Comment by Nikki1993** [comment]
Can't even locate damn logs (I mean from old boots). Hang on please.

**Comment by Nikki1993** [comment]
Here, journalctl for the entire day. Is this what you were looking for?
https://drive.google.com/file/d/0BzuUKFr0QgadQktVODZWckNqX2c/view?usp=sharing

**Comment by heftig** [comment]
This seems to be the problem:
```
Oct 18 11:09:05 arch_dellxps systemd[3781]: Starting DBUS1: org.gnome.Terminal...
Oct 18 11:09:05 arch_dellxps systemd[3781]: Started DBUS1: org.gnome.Terminal.
Oct 18 11:09:05 arch_dellxps systemd-bus-proxyd[3811]: Failed to start bus client: Connection reset by peer
Oct 18 11:09:05 arch_dellxps systemd-bus-proxyd[3811]: Assertion 'close_nointr(fd) != -EBADF' failed at src/basic/util.c:318, function safe_close(). Aborting.
```
systemd-dbus-proxyd is crashing. As this is a kdbus issue, please take it to https://github.com/systemd/systemd/issues .

**Comment by Nikki1993** [comment]
I just wonder why it didn't crash on mainline kernel then with no kdbus in boot options?

**Comment by heftig** [comment]
systemd uses kdbus by default if it's available.

The system bus seems to run into trouble as well (you can also see geoclue getting kicked off the bus), which causes Xorg to crash.

**Comment by Nikki1993** [comment]
Alright, so should I just leave the kdbus=0 for now until issue is fixed upstream?

**Comment by heftig** [comment]
Yes.

**Comment by Nikki1993** [comment]
Alrighty then. Thanks a lot for the help! Appreciate the kernel and support! Have a great rest of the day.
