### ISSUE TITLE
Incorrect CONFIG_MZEN5 GCC_VERSION restriction in v6.10.7-lqx1

### ISSUE THREAD

**Issue by drammelt** [zen-kernel/zen-kernel#357]
The CONFIG_MZEN5 Kconfig.cpu option has a restriction of GCC_VERSION >= 141000 (GCC 14.10.00), this should be GCC_VERSION >= 140000 as it was supported at GCC 14 release.

Found in v6.10.7-lqx1 but probably affects older releases/zen releases but this is the one I am using.

Have attached relevant patch

[fix-lqx-zen5.patch.txt](https://github.com/user-attachments/files/16822162/fix-lqx-zen5.patch.txt)

**Comment by heftig** [comment]
We're just consuming graysky's patch here. Please bring open an issue at to https://github.com/graysky2/kernel_compiler_patch/issues.
