### ISSUE TITLE
Errors when I try to compile zen-kernel 6.10.8 on Gentoo Linux 2.15 x86_64

### ISSUE THREAD

**Issue by mxTeamCEO** [zen-kernel/zen-kernel#358]
I got errors on acpi quriks and tables.
error: initializer-string for array of 'char' is too long [-Werror=unterminated-string-initialization]
Make output : [make_output.txt](https://github.com/user-attachments/files/17008637/make_output.txt)
My .config: [config.txt](https://github.com/user-attachments/files/17008668/config.txt)

**Comment by damentz** [comment]
Did you manually add **Werror=unterminated-string-initialization**?  If so, sounds like something you can report to upstream.

**Comment by mxTeamCEO** [comment]
> Did you manually add **Werror=unterminated-string-initialization**? If so, sounds like something you can report to upstream.

I didn't change any compilation parameters

**Comment by mxTeamCEO** [comment]
I tried the same thing with linux-6.11-zen1 with the default config, and I get the same errors. I think the problem is in the gcc compiler (Gentoo Hardened 15.0.0.0_pre20240908 p12) 15.0.0 20240908 (experimental)

**Comment by mxTeamCEO** [comment]
kernel compiled with gcc compiler (Gentoo Hardened 14.2.1_p20240817 p4) 14.2.1 20240817
