### ISSUE TITLE
System restarts when waking it up from sleep.

### ISSUE THREAD

**Issue by RudraPS97** [zen-kernel/zen-kernel#359]
Since 2-3 weeks, the system restarts when I wake it up from sleep.
I tried doing the same with LTS kernel (Linux 6.6.52-1-lts), and it works normally.
Zen kernel I am using: Linux 6.10.10-zen1-1-zen
JournalCTL (the part I thought would be relevant):
[journalCTL.txt](https://github.com/user-attachments/files/17090290/journalCTL.txt)
SystemINFO (inxi):
[systeminfo.txt](https://github.com/user-attachments/files/17090293/systeminfo.txt)

**Comment by MartinX3** [comment]
It seems like this is also my issue.
I resume from standby, see my login screen and the SHIFT key is blinking.
Sadly even with kdump I'm unable to get the kernel panic log.
(Probably because kdump somehow depends on grub but I use systemd-boot)

I'm also using `6.10.10-zen1-1.1-zen`.
But `6.11.zen1-1` is in arch linux testing and probably it will be fixed then.

If I remember correctly it happens since
`[2024-09-15T14:49:30+0200] [ALPM] upgraded linux-zen (6.10.9.zen1 -> 6.10.10.zen1)`

**Comment by damentz** [comment]
@MartinX3 is your system also Ryzen?

**Comment by damentz** [comment]
Pushed change that might fix your issue here: https://github.com/zen-kernel/zen-kernel/commit/fb31943196e6193d893e5ea62c500356f52cb3cf

**Comment by MartinX3** [comment]
@damentz 
No, it is a Thinkpad T460p with an Intel Skylake and a Nvidia GTX 940MX

**Comment by MartinX3** [comment]
Hmmm, the next day I woke my `6.10.9` laptop from sleep and got the kernel panic (just blinking shift key).  
Then I restarted my laptop and I got the same panic on startup. It just freezes with the blinking shift key.

No logs in both cases in the journal.
And `kdump` never worked, probably because I use `systemd-boot` instead of `grub`.

**Comment by RudraPS97** [comment]
> Pushed change that might fix your issue here: [fb31943](https://github.com/zen-kernel/zen-kernel/commit/fb31943196e6193d893e5ea62c500356f52cb3cf)

I am getting errors when I try to patch it.
I manually checked one file, `drivers/pci/pci.c`, and the `575` line is not the same as it is in the patch you provided.
I git cloned the main branch.
```
git apply -v fb31943196e6193d893e5ea62c500356f52cb3cf.patch
Checking patch drivers/pci/pci-driver.c...
error: while searching for:
{
int ret;

ret = pci_bridge_wait_for_secondary_bus(pci_dev, PCI_DEV_WAIT_RESUME);
if (ret) {
/*
* The downstream link failed to come up, so mark the

error: patch failed: drivers/pci/pci-driver.c:572
error: drivers/pci/pci-driver.c: patch does not apply
Checking patch drivers/pci/pci.c...
error: while searching for:
}
__setup("pcie_port_pm=", pcie_port_pm_setup);

static const char * const pci_reset_types[] = {
[PCI_DEV_WAIT_FLR] = "FLR",
[PCI_DEV_WAIT_AF_FLR] = "AF_FLR",
[PCI_DEV_WAIT_D3HOT_D0] = "PM D3HOT->D0",
[PCI_DEV_WAIT_BUS_RESET] = "bus reset",
[PCI_DEV_WAIT_RESUME] = "resume",
[PCI_DEV_WAIT_DPC] = "DPC",
[PCI_DEV_WAIT_D3COLD_D0] = "D3cold->D0",
};
static_assert(ARRAY_SIZE(pci_reset_types) == PCI_DEV_WAIT_MAX);

/**
* pci_bus_max_busnr - returns maximum PCI bus number of given bus' children
* @bus: pointer to PCI bus structure to search

error: patch failed: drivers/pci/pci.c:181
error: drivers/pci/pci.c: patch does not apply
Checking patch drivers/pci/pci.h...
error: while searching for:

#include <linux/pci.h>

enum pci_reset_type {
PCI_DEV_WAIT_FLR,
PCI_DEV_WAIT_AF_FLR,
PCI_DEV_WAIT_D3HOT_D0,
PCI_DEV_WAIT_BUS_RESET,
PCI_DEV_WAIT_RESUME,
PCI_DEV_WAIT_DPC,
PCI_DEV_WAIT_D3COLD_D0,
PCI_DEV_WAIT_MAX,
};

/* Number of possible devfns: 0.0 to 1f.7 inclusive */
#define MAX_NR_DEVFNS 256


error: patch failed: drivers/pci/pci.h:4
error: drivers/pci/pci.h: patch does not apply
Checking patch drivers/pci/pcie/dpc.c...
error: while searching for:
pci_write_config_word(pdev, cap + PCI_EXP_DPC_STATUS,
PCI_EXP_DPC_STATUS_TRIGGER);

if (pci_bridge_wait_for_secondary_bus(pdev, PCI_DEV_WAIT_DPC)) {
clear_bit(PCI_DPC_RECOVERED, &pdev->priv_flags);
ret = PCI_ERS_RESULT_DISCONNECT;
} else {

error: patch failed: drivers/pci/pcie/dpc.c:174
error: drivers/pci/pcie/dpc.c: patch does not apply
Checking patch drivers/pci/quirks.c...
error: while searching for:
dev->d3hot_delay);
}

/*
* NVIDIA Ampere-based HDA controllers can wedge the whole device if a bus
* reset is performed too soon after transition to D0, extend d3hot_delay

error: patch failed: drivers/pci/quirks.c:2038
error: drivers/pci/quirks.c: patch does not apply
Checking patch drivers/usb/host/xhci-pci.c...
error: while searching for:
(pdev->device == PCI_DEVICE_ID_AMD_PROMONTORYA_1)))
xhci->quirks |= XHCI_U2_DISABLE_WAKE;

if (pdev->vendor == PCI_VENDOR_ID_INTEL) {
xhci->quirks |= XHCI_LPM_SUPPORT;
xhci->quirks |= XHCI_INTEL_HOST;

error: patch failed: drivers/usb/host/xhci-pci.c:316
error: drivers/usb/host/xhci-pci.c: patch does not apply
```

**Comment by damentz** [comment]
Has the 6.11 kernel helped with this?

**Comment by MartinX3** [comment]
No.  
But in my case it helped me to reduce the usage of tmpfs.
As example i removed the usage of tmpfs as a cache for my IntelliJ IDE.
Somehow if many files are written and read the vfs dead locks my IDE.
This issue also exists for me in the latest linux-lts and at least Linux 6.10.8.

I did run the complete memtest86+ multiple times on all cores without any issues.  
So some bug exists in some piece of software or in the kernel on my system and there is no hardware damage.

**Comment by RudraPS97** [comment]
Kernel `6.11.2-zen1-1-zen` seems to have fixed this issue.
Slept and woke the laptop 6 times.
