### ISSUE TITLE
MT7921 Bluetooth firmware unable to load 

### ISSUE THREAD

**Issue by snow-nene** [zen-kernel/zen-kernel#360]
After upgrading zen-kernel from 6.10 to 6.11, I found that the Bluetooth firmware unable to load

```
Oct 02 13:42:33 archlinux kernel: Bluetooth: hci0: Execution of wmt command timed out
Oct 02 13:42:33 archlinux kernel: Bluetooth: hci0: Failed to send wmt patch dwnld (-110)
Oct 02 13:42:33 archlinux kernel: Bluetooth: hci0: Failed to set up firmware (-110)
Oct 02 13:42:33 archlinux kernel: Bluetooth: hci0: HCI Enhanced Setup Synchronous Connection command is advertised, but not supported.
```

I use timeshift to downgrade the upgrading or use the lts kernal, and then it works.

Please fix the problem.

**Comment by heftig** [comment]
Is the normal `linux` kernel affected? Then please file at https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/issues

**Comment by snow-nene** [comment]
> Is the normal `linux` kernel affected? Then please file at https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/issues

Yes, it has the same problem. I wiill file at the url that you provide.


```
[    8.120224] Bluetooth: hci0: Failed to write uhw reg(-110)
[    8.121924] Bluetooth: hci0: HW/SW Version: 0x008a008a, Build Time: 20240826151221
[   26.680163] Bluetooth: hci0: Execution of wmt command timed out
[   26.680178] Bluetooth: hci0: Failed to send wmt patch dwnld (-110)
[   26.680221] Bluetooth: hci0: Failed to set up firmware (-110)
[   26.680224] Bluetooth: hci0: HCI Enhanced Setup Synchronous Connection command is advertised, but not supported.
❯ uname -a
Linux archlinux 6.11.1-arch1-1.1 #1 SMP PREEMPT_DYNAMIC Tue, 01 Oct 2024 13:14:03 +0000 x86_64 GNU/Linux
```

**Comment by snow-nene** [comment]
> Is the normal `linux` kernel affected? Then please file at https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/issues

Sorry, I don't have the account acutally.

**Comment by damentz** [comment]
Since this is in upstream, I'm closing out the issue.
