### ISSUE TITLE
BTF error compiling 6.11.5 on Arch Linux

### ISSUE THREAD

**Issue by dcarmal** [zen-kernel/zen-kernel#362]
Hello,

I'm having issues when trying to compile 6.11.5-zen1:
`make: se entra en el directorio 'linux/src/zen-kernel-6.11.5-zen1/tools/bpf/bpftool'

  GEN     vmlinux.h
libbpf: failed to find '.BTF' ELF section in linux/src/zen-kernel-6.11.5-zen1/vmlinux
Error: failed to load BTF from linux/src/zen-kernel-6.11.5-zen1/vmlinux: No data available
make: *** [Makefile:209: vmlinux.h] Error 195
make: *** Se borra el archivo 'vmlinux.h'
make: se sale del directorio 'linux/src/zen-kernel-6.11.5-zen1/tools/bpf/bpftool'
==> ERROR: Se produjo un fallo en build().
    Cancelando...
`
Tried several configurations regarding BPF, self testing and debug options but still getting stuck in this error. Any help is really appreciated. Many thanks in advance.

Kind regards

**Comment by damentz** [comment]
How are you building the kernel?

**Comment by damentz** [comment]
Why not start with the `linux-zen` package? https://archlinux.org/packages/extra/x86_64/linux-zen/

Overall, you're making large changes to a PKGBUILD and cannot get it to build for changes that you likely made.  This project isn't a forum for tech support and this isn't an issue with Zen Kernel itself.

Closing out, if you continue to have trouble I recommend submitting asking for help here: https://bbs.archlinux.org/

**Comment by heftig** [comment]
Make sure all makedepends are installed (build using `makepkg -s`).

The config file used is right next to the PKGBUILD. You need to replace that one if you want to modify it.
