### ISSUE TITLE
BFS is out for v4.3! :D

### ISSUE THREAD

**Issue by loxdegio** [zen-kernel/zen-kernel#38]
Here is the link for new version of BFS:
http://ck.kolivas.org/patches/bfs/4.0/4.3/

At last after the jump of v4.2. Somebody knows the why?

**Comment by heftig** [comment]
Merged, thanks.

**Comment by AnAkkk** [comment]
I would have preferred if BFS wouldn't have been merged, it lags behind kernel releases very often, so it's very likely that for next release you will have to remove it or delay the zen update until a new BFS version is out...
It's also very subjective it if really brings any performance improvements, there aren't really any recent benchmarks that show it does.

It also brought a lot of issues to linux-ck with recent kernel updates, crashes etc, that took quite some time to find and fix for some of them, I wouldn't say that it's very stable, compared to BFQ for example.

**Comment by heftig** [comment]
I don't like it much, either. You won't find it in my builds.

**Comment by AnAkkk** [comment]
So, it won't be in linux-zen in Arch?

**Comment by heftig** [comment]
It won't.
