### ISSUE TITLE
linux v4.1.15 is out! :D

### ISSUE THREAD

**Issue by loxdegio** [zen-kernel/zen-kernel#42]

**Comment by eegorov** [comment]
https://github.com/eegorov/zen-kernel/commits/4.1/my

**Comment by loxdegio** [comment]
Has been the repository changed?

**Comment by eegorov** [comment]
No. This is my fork.

**Comment by damentz** [comment]
Zen only tracks the last two major kernel releases.  The 4.1, and soon 4.2, branches have been removed.  Closing this issue.
