### ISSUE TITLE
Build errors with 4.5(4.5.3)/master branch 

### ISSUE THREAD

**Issue by habernir** [zen-kernel/zen-kernel#53]
hi there i try to disable the SCHEDSTATS in the config file but  no help  this is the error 

scripts/kconfig/conf  --silentoldconfig Kconfig
warning: (LATENCYTOP) selects SCHEDSTATS which has unmet direct dependencies (DEBUG_KERNEL && PROC_FS && !SCHED_BFS)
#
# configuration written to .config
#
warning: (LATENCYTOP) selects SCHEDSTATS which has unmet direct dependencies (DEBUG_KERNEL && PROC_FS && !SCHED_BFS)
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CHK     include/generated/bounds.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  CC      arch/x86/kernel/ioport.o
  LD      arch/x86/kernel/built-in.o
  LD      arch/x86/built-in.o
  CC      kernel/sched/bfs.o
In file included from include/linux/static_key.h:1:0,
                 from include/linux/tracepoint-defs.h:11,
                 from ./arch/x86/include/asm/msr.h:75,
                 from ./arch/x86/include/asm/processor.h:20,
                 from ./arch/x86/include/asm/thread_info.h:52,
                 from include/linux/thread_info.h:54,
                 from ./arch/x86/include/asm/preempt.h:6,
                 from include/linux/preempt.h:59,
                 from include/linux/spinlock.h:50,
                 from include/linux/seqlock.h:35,
                 from include/linux/time.h:5,
                 from include/uapi/linux/timex.h:56,
                 from include/linux/timex.h:56,
                 from include/linux/sched.h:19,
                 from include/linux/kasan.h:4,
                 from kernel/sched/bfs.c:31:
kernel/sched/bfs.c: In function ‘ttwu_stat’:
kernel/sched/stats.h:32:55: error: ‘sched_schedstats’ undeclared (first use in this function)
 # define schedstat_enabled()  static_branch_unlikely(&sched_schedstats)
                                                       ^
include/linux/jump_label.h:347:43: note: in definition of macro ‘static_branch_unlikely’
  if (__builtin_types_compatible_p(typeof(*x), struct static_key_true)) \
                                           ^
kernel/sched/stats.h:33:44: note: in expansion of macro ‘schedstat_enabled’
 # define schedstat_inc(rq, field) do { if (schedstat_enabled()) { (rq)->field++; } } while (0)
                                            ^
kernel/sched/bfs.c:1450:3: note: in expansion of macro ‘schedstat_inc’
   schedstat_inc(rq, ttwu_local);
   ^
kernel/sched/stats.h:32:55: note: each undeclared identifier is reported only once for each function it appears in
 # define schedstat_enabled()  static_branch_unlikely(&sched_schedstats)
                                                       ^
include/linux/jump_label.h:347:43: note: in definition of macro ‘static_branch_unlikely’
  if (__builtin_types_compatible_p(typeof(*x), struct static_key_true)) \
                                           ^
kernel/sched/stats.h:33:44: note: in expansion of macro ‘schedstat_enabled’
 # define schedstat_inc(rq, field) do { if (schedstat_enabled()) { (rq)->field++; } } while (0)
                                            ^
kernel/sched/bfs.c:1450:3: note: in expansion of macro ‘schedstat_inc’
   schedstat_inc(rq, ttwu_local);
   ^
kernel/sched/bfs.c: In function ‘try_to_wake_up_local’:
kernel/sched/stats.h:32:55: error: ‘sched_schedstats’ undeclared (first use in this function)
 # define schedstat_enabled()  static_branch_unlikely(&sched_schedstats)
                                                       ^
include/linux/jump_label.h:347:43: note: in definition of macro ‘static_branch_unlikely’
  if (__builtin_types_compatible_p(typeof(*x), struct static_key_true)) \
                                           ^
kernel/sched/stats.h:33:44: note: in expansion of macro ‘schedstat_enabled’
 # define schedstat_inc(rq, field) do { if (schedstat_enabled()) { (rq)->field++; } } while (0)
                                            ^
kernel/sched/bfs.c:1625:4: note: in expansion of macro ‘schedstat_inc’
    schedstat_inc(rq, ttwu_count);
    ^
kernel/sched/bfs.c: In function ‘schedule_debug’:
kernel/sched/stats.h:32:55: error: ‘sched_schedstats’ undeclared (first use in this function)
 # define schedstat_enabled()  static_branch_unlikely(&sched_schedstats)
                                                       ^
include/linux/jump_label.h:347:43: note: in definition of macro ‘static_branch_unlikely’
  if (__builtin_types_compatible_p(typeof(*x), struct static_key_true)) \
                                           ^
kernel/sched/stats.h:33:44: note: in expansion of macro ‘schedstat_enabled’
 # define schedstat_inc(rq, field) do { if (schedstat_enabled()) { (rq)->field++; } } while (0)
                                            ^
kernel/sched/bfs.c:3309:2: note: in expansion of macro ‘schedstat_inc’
  schedstat_inc(this_rq(), sched_count);
  ^
kernel/sched/bfs.c: In function ‘__schedule’:
kernel/sched/stats.h:32:55: error: ‘sched_schedstats’ undeclared (first use in this function)
 # define schedstat_enabled()  static_branch_unlikely(&sched_schedstats)
                                                       ^
include/linux/jump_label.h:347:43: note: in definition of macro ‘static_branch_unlikely’
  if (__builtin_types_compatible_p(typeof(*x), struct static_key_true)) \
                                           ^
kernel/sched/stats.h:33:44: note: in expansion of macro ‘schedstat_enabled’
 # define schedstat_inc(rq, field) do { if (schedstat_enabled()) { (rq)->field++; } } while (0)
                                            ^
kernel/sched/bfs.c:3545:3: note: in expansion of macro ‘schedstat_inc’
   schedstat_inc(rq, sched_goidle);
   ^
kernel/sched/bfs.c: In function ‘sys_sched_yield’:
kernel/sched/stats.h:32:55: error: ‘sched_schedstats’ undeclared (first use in this function)
 # define schedstat_enabled()  static_branch_unlikely(&sched_schedstats)
                                                       ^
include/linux/jump_label.h:347:43: note: in definition of macro ‘static_branch_unlikely’
  if (__builtin_types_compatible_p(typeof(*x), struct static_key_true)) \
                                           ^
kernel/sched/stats.h:33:44: note: in expansion of macro ‘schedstat_enabled’
 # define schedstat_inc(rq, field) do { if (schedstat_enabled()) { (rq)->field++; } } while (0)
                                            ^
kernel/sched/bfs.c:4758:2: note: in expansion of macro ‘schedstat_inc’
  schedstat_inc(task_rq(p), yld_count);
  ^
scripts/Makefile.build:258: recipe for target 'kernel/sched/bfs.o' failed
make[2]: *** [kernel/sched/bfs.o] Error 1
scripts/Makefile.build:407: recipe for target 'kernel/sched' failed
make[1]: *** [kernel/sched] Error 2
Makefile:952: recipe for target 'kernel' failed
make: *** [kernel] Error 2

i also read the old post about that but this problem come back

**Comment by damentz** [comment]
It looks like we also need to set a conflicting dependency on CONFIG_LATENCYTOP.  Have you tried turning off this configuration?

**Comment by FadeMind** [comment]
@damentz FYI I following config from `linux-zen` Arch package (and adjust some stuffs).
In default `CONFIG_LATENCYTOP` in `linux-zen` package config is not set.

Regards

**Comment by habernir** [comment]
after i disable the CONFIG_LATENCYTOP the compilation was OK . thanks a lot.

**Comment by hhoffstaette** [comment]
Hi! I found this issue by accident and thought you might be interested in my backport of the schedstats runtime tunable for BFS. It's for 4.4, but shouldn't require much adaptation. The commit is here: https://github.com/hhoffstaette/kernel-patches/commit/5c915fefeda7776c93a02aad763e3d7c30717e23 and is incremental to BFS.

Hope this helps. :)
