### ISSUE TITLE
Cannot compile Zen kernel on elementary OS freya 64-bit

### ISSUE THREAD

**Issue by SuicSoft** [zen-kernel/zen-kernel#83]
I am following this tutorial http://apcmag.com/how-to-improve-gaming-performance-on-your-linux-machine.htm/ which uses Zen kernel.But when I try to run `make-kpkg kernel_image kernel_headers` it compiles for a little while and then gives.
```

make[1]: Leaving directory `/usr/src/zen-kernel-4.7-master'
make: *** [debian/stamp/build/kernel] Error 2
```

Do you know what could be happening.I can compile using `make -j8`  (and only takes 10 minutes) but  `make-kpkg kernel_image kernel_headers` gives an error in all kernels including Zen

I am using an HP Pavilion g7 2269wm with AMD A8-4500M and Radeon HD 7640G discrete-class graphics.

**Comment by heftig** [comment]
This tracker is for Zen-specific issues only. Please ask your distribution's support forums for assistance.
