### ISSUE TITLE
MuQSS patch

### ISSUE THREAD

**Issue by Lampwick** [zen-kernel/zen-kernel#85]
Will the MuQSS CPU scheduler patch be added to Zen?

**Comment by damentz** [comment]
Ah, I haven't been following the latest from Con, but from his latest blogposts, he intends to stop development on BFS and MuQSS will supercede it indefinitely.

It also looks like he's back to his old groove and making fast progress, fixing long standing bugs.  So yes, we'll include it when either me or @heftig  get to it.  Con also is updating his scheduler through a git repo now, as well as patches, so it will be much easier to maintain going forward.

I'll leave this issue open until we've merged the patch and removed BFS.

**Comment by Lampwick** [comment]
Excellent, thank you.

**Comment by damentz** [comment]
Although I didn't merge the changes myself, it looks like @heftig did.  MuQSS can be enabled by setting CONFIG_SCHED_MUQSS.

**Comment by weedy** [comment]
MuQSS was updated to version 0.135 a few days ago for 4.8.6+

**Comment by simonbcn** [comment]
I've installed linux-zen from Arch repositories but MuQSS isn't enabled by default, why? How can I enabled it?
