### ISSUE TITLE
Linux 4.7.10 Support

### ISSUE THREAD

**Issue by StevenTheEVILZ** [zen-kernel/zen-kernel#86]
I've noticed that the 4.7/master branch updated to 4.7.9, but still has not updated to 4.7.10. Being that 4.7.10 is the last update of 4.7, can you please update? (I have no idea how kernels work, so I unfortunately won't be of much help).

**Comment by damentz** [comment]
Merged 4.7.10 in 4.7/master.

**Comment by StevenTheEVILZ** [comment]
Thx!
