### ISSUE TITLE
SCHED_BFS_AUTOISO  to SCHED_MuQSS_AUTOISO

### ISSUE THREAD

**Issue by gebruiker1** [zen-kernel/zen-kernel#88]
Hello,

I used to SCHED_BFS_AUTOISO on your 4.7 which works great! Could this also made available in your !> branches?

Thanks

*****
https://github.com/zen-kernel/zen-kernel/blob/4.7/master/init/Kconfig#L75

config SCHED_BFS_AUTOISO
	bool "Automatically use SCHED_ISO policy for X"
	depends on SCHED_BFS
	default n
	help
	  Selecting this option will automatically use the SCHED_ISO scheduling
	  policy for X, resulting in an interactivity boost. This *may* cause
	  things like skipping sound on audio applications that are not run
	  as SCHED_ISO.

	  Tasks (including X) can be run as sched_iso manually using schedtool.

**Comment by heftig** [comment]
Is this even relevant anymore? CK dropped it from his kernels, too.

**Comment by gebruiker1** [comment]
I do not know but CK said he never wrote such a thing

http://ck-hack.blogspot.nl/2016/11/linux-48-ck8-muqss-version-0144.html?showComment=1480875133246#c5077418798196560697

**Comment by heftig** [comment]
At https://ck-hack.blogspot.de/2012/01/32-ck1.html?showComment=1331417260279#c3820208496596463552:
> I never recommended anyone use the autoiso patch. That's why it was never included in any -ck release. The potential for it blocking audio which is even more important than xorg is why I decided against it.

So I think we'll leave it out.
