### ISSUE TITLE
Raspberry Pi 2/3 support?

### ISSUE THREAD

**Issue by vanfanel** [zen-kernel/zen-kernel#91]
Hi,

Years ago, I used to run ZEN Kernel and nothing else on my Core2Duo mac with Gentoo. That was an awesome difference for emulators and games!
Howver, I don't know how the Raspberry Pi support is. I believe the 4.9 kernel branch on https://github.com/raspberrypi/linux/commits/rpi-4.9.y has it's own set of Pi-specific patches. So, could those be incorporated into ZEN Kernel, please?

Since 4.9 is going to be an LTS, I think it's a good time to ask. Also, the pi kernel in https://github.com/raspberrypi/linux/commits/rpi-4.9.y is also in 4.9.5 so it's easier.

Thanks for the continued work on this awesome kernel version!

**Comment by heftig** [comment]
I don't think anyone of us has interest in this; sorry.
