### ISSUE TITLE
AUFS support in linux 4.9

### ISSUE THREAD

**Issue by bogdanr** [zen-kernel/zen-kernel#93]
It would be nice to patch AUFS support in linux 4.9

**Comment by backbone** [comment]
+1
In principle, it is possible to merge by yourself (https://github.com/sfjro/aufs4-linux). But those who use Zen almost certainly use AUFS, so it would be nice if it would be in Zen.

**Comment by heftig** [comment]
We decided to drop it as (1) we don't use it, (2) overlayfs is mainline and (3) it was a significant burden.
