### ISSUE TITLE
btrfs support

### ISSUE THREAD

**Issue by Fraybyl** [zen-kernel/zen-kernel#94]
Hello,guys i build zen-kernel from git and i get unknown filesystem type "btrfs"
in config i have this: 
![image](https://cloud.githubusercontent.com/assets/26145190/23827342/ab4ab584-06c2-11e7-99a3-904176622b01.png)

**Comment by eegorov** [comment]
modprobe btrfs

**Comment by Fraybyl** [comment]
Does not work this command

**Comment by Fraybyl** [comment]
I made btrfs as built-in and it all worked.
