### ISSUE TITLE
Possible to get the magic mouse 2 touchpad working 

### ISSUE THREAD

**Issue by lomolca** [zen-kernel/zen-kernel#97]
I too got myself a Magic Mouse 2 about half years ago, but it is only recognising it as a two-button mouse. Seems the kernel can not recognise the Magic Mouse 2 and load the hid_magicmouse module, I have found some information on a Github project at https://github.com/biggreenogre/mm2. can this apply to zen distros?

Regards,

**Comment by heftig** [comment]
The patches seem simple enough, but unfortunately are not in unified format. Can you provide unified format patches, or better, git send-email style patches, or even better, a pull request?

**Comment by heftig** [comment]
No response.
