### ISSUE TITLE
Zen patches?

### ISSUE THREAD

**Issue by m4sk1n** [zen-kernel/zen-kernel#98]
Hi! Can I find patches to apply to "pure" kernel to get benefits of Zen kernel? I would like to make 'linux-libre-zen' or "linux-zen-libre' kernel.
Thanks in advance.

**Comment by Sudokamikaze** [comment]
@m4sk1n [Here](https://pkgbuild.com/~heftig/zen-patches/) you can get patches
This patches used in linux-zen  PKGBUILD for Archlinux

**Comment by m4sk1n** [comment]
@Sudokamikaze, thanks :)

**Comment by Techwolf** [comment]
This is the "magic" command I use to gen a kernel patch against vinilla kernel.
In the directory where you cloned the zen kernel:
```
git diff remotes/origin/4.9/upstream-updates..remotes/origin/4.9/master | bzip2 > /your_patch_directory_here/zen_master-4.9.4.patch.bz2
```

Do this right after a git pull to get the latest patch.

**Comment by Sudokamikaze** [comment]
@Techwolf Thank you, I was looking for this
