### ISSUE TITLE
Timer Frequency

### ISSUE THREAD

**Issue by joksik** [zen-kernel/zen-kernel#99]
Hi sorry for probably a silly question but I use a laptop with 2 cores and i want to find out what default timer frequency use this kernel? 300 like arch-kernel? or higher? I can not find it anywhere and I do not know how to check it after installation

**Comment by monotykamary** [comment]
To check your kernel frequency, just use `zgrep CONFIG_HZ= /proc/config.gz`.

**Comment by heftig** [comment]
There are no special considerations for ZEN, although if you use MuQSS, Con claims the frequency does not matter.

**Comment by joksik** [comment]
thx for quick replay. i read that higher frequency can affect on battery life so i want test it personally
